### ISSUE TITLE
Source file is not exposed to fzf

### ISSUE THREAD

**Issue by Avi-D-coder** [liuchengxu/vista.vim#10]
![screenshot_20190217_220413](https://user-images.githubusercontent.com/29133776/52925598-09dce980-3300-11e9-8001-ee258fe8e135.png)

When using a preview window with fzf, fzf should preview the file the ctags came from.

**Comment by Avi-D-coder** [comment]
This appears not to be possible in the general sense, I'll add a option.

**Comment by liuchengxu** [comment]
Should be closed in favor of https://github.com/liuchengxu/vista.vim/pull/11
