### ISSUE TITLE
Support mouse

### ISSUE THREAD

**Issue by mnrce** [liuchengxu/vista.vim#100]
**Is your feature request related to a problem? Please describe.**
When browsing code, I usually use mouse to navigate but `vista.vim` doesn't seem to support it (I have `set mouse=a` in my `init.vim`).

**Describe the solution you'd like**
- When click on kind of tags or LSP symbols, fold/unfold it.
- When double click on a tag or LSP symbol, jump to it (like when pressing enter)

Thanks.

**Comment by liuchengxu** [comment]
I don't use mouse personally, but you can try this:

- fold/unfold: map the mouse click key to `za`, see `:h za`.

- jump to the tag: map double click key to `vista#cursor#FoldOrJump()`, like `<CR>` does.

https://github.com/liuchengxu/vista.vim/blob/8157620ef111559458bb39acef5a355e351abbef/ftplugin/vista.vim#L42

**Comment by mnrce** [comment]
> I don't use mouse personally, but you can try this:
> 
>     * fold/unfold: map the mouse click key to `za`, see `:h za`.
> 
>     * jump to the tag: map double click key to `vista#cursor#FoldOrJump()`, like `<CR>` does.
> 
> 
> https://github.com/liuchengxu/vista.vim/blob/8157620ef111559458bb39acef5a355e351abbef/ftplugin/vista.vim#L42

Thanks, I can make the jump to tag works with this mapping:
```vim
autocmd FileType vista_kind map <buffer> <silent> <2-LeftMouse> :<c-u>call vista#cursor#FoldOrJump()<CR>
```

But when I double click on the tag kind, all the other kinds are folded too, is there any way to make it only fold/unfold the one that gets clicked on?

**Comment by liuchengxu** [comment]
Can you post a gif? I haven't seen your problem in my machine.

**Comment by mnrce** [comment]
>  And have you mapped `za` for the fold/fold function?

No, I only have the map for double click I mentioned earlier since I don't know how to detect if the line being clicked on is a tag kind. But I think the double click mapping is enough as long as the fold works as intended.

> Can you post a gif? I haven't seen your problem in my machine.

Here it is:
[![asciicast](https://asciinema.org/a/4kf1t6gK3MflFRSwgyjoW8jzg.svg)](https://asciinema.org/a/4kf1t6gK3MflFRSwgyjoW8jzg)

- I pressed enter on the **Function** tag kind and all other tag kinds also got folded.
- I had to press enter twice on the **Field** tag kind to unfold it.

**Comment by liuchengxu** [comment]
Try the latest commit. `vista#cursor#FoldOrJump()` will fold/unfold the children when the cursor is at the top level tag line, otherwise jump to the tag in the source file.

**Comment by mnrce** [comment]
> Try the latest commit. `vista#cursor#FoldOrJump()` will fold/unfold the children when the cursor is at the top level tag line, otherwise jump to the tag in the source file.

It still behaves the same for me:

> 
> - I pressed enter on the Function tag kind and all other tag kinds also got folded.
> - I had to press enter twice on the Field tag kind to unfold it.

Maybe it's something related to my setup, I will try to reproduce this with a minimal vimrc.
