### ISSUE TITLE
[Feature request] Vista focus command

### ISSUE THREAD

**Issue by cdelledonne** [liuchengxu/vista.vim#101]
Hey there, very very nice plugin.

### Is your feature request related to a problem? Please describe.

I often like jumping between a window containing some code and the Vista window.

### Describe the solution you'd like.

What about adding a command to _focus_ the Vista window when in a different window, and to switch back to the previous window (containing code) when in the Vista window. Something like
```vim
command! VistaFocus call vista#sidebar#Focus()
```

that calls
```vim
function! vista#sidebar#Focus() abort
  if exists("t:vista") && winnr() == t:vista.winnr()
    wincmd p
  else
    call vista#sidebar#Open()
  endif
endfunction
```

### Describe alternatives you've considered.

Clearly one could just use `:Vista` from a window to focus the Vista window, and then `CTRL-W CTRL-P` to jump back and forth from the Vista window and the code window. But it seems nicer to me to have a single command that can be mapped to a single key combination to achieve that.

**Comment by cdelledonne** [comment]
### Side notes for when the Vista window is focused

#### Note 1
When the Vista window is focused, and we want to close it, I believe it would be better to jump to the previously active window, rather than just closing Vista and ending up in the window that was closest to it. For instance, the function [`vista#sidebar#Close()`](https://github.com/liuchengxu/vista.vim/blob/d6a295432b50d7af08a0bdd382e3ff5dcf997300/autoload/vista/sidebar.vim#L78) could be extended with 3 lines in the beginning
```vim
function! vista#sidebar#Close() abort
  " Begin new code
  if exists("t:vista") && winnr() == t:vista.winnr()
    wincmd p
  endif
  " End new code

  if exists('t:vista.bufnr')
    let winnr = t:vista.winnr()
    if winnr != -1
      noautocmd execute winnr.'wincmd c'
    endif

    silent execute  t:vista.bufnr.'bwipe!'
    unlet t:vista.bufnr
  endif

  call s:ClearAugroups('VistaCoc', 'VistaCtags')

  call vista#floating#Close()
endfunction
```
so as to jump to the last active window before closing Vista.

#### Note 2
By default, the key `q` maps to `:close<CR>` in vista buffers. Is this the desired behaviour, instead of mapping it to `:call vista#sidebar#Close()<CR>`? Why?

**Comment by liuchengxu** [comment]
- Note 1: that makes sense.
- Note 2: `q` is more like hiding the vista sidebar, `:Vista!` has been used for closing the vista window actually.

So, what you really want is to be able to jump back and forth between the vista window and the source code window?

**Comment by cdelledonne** [comment]
> So, what you really want is to be able to jump back and forth between the vista window and the source code window?

Yes that's the idea, but consider it only if you think it might be useful at all. Thanks!

**Comment by liuchengxu** [comment]
I do think it's useful, but I'm not sure that I'm satisfied with `focus` wording. Do you have some other options? Or could you convince me it's appropriate :(?

**Comment by cdelledonne** [comment]
I'm also not convinced with it :). Some alternatives I can think of:

| Function | Command | Description |
|:---|:---|:---|
| `vista#sidebar#ToggleFocus` | `VistaToggleFocus` | Focus Vista window, or focus previous window when already in Vista window |
| `vista#sidebar#Alternate` | `VistaAlt` | Alternate between code window and Vista window |
| `vista#sidebar#Jump` | `VistaJump` | Jump to Vista window and back |

sorted by decreasing preference.

**Comment by liuchengxu** [comment]
Try the latest commit with `:Vista focus`.

**Comment by cdelledonne** [comment]
Works as intended, thanks!
