### ISSUE TITLE
How do I toggle Vista while entering a Buf

### ISSUE THREAD

**Issue by crispgm** [liuchengxu/vista.vim#102]
**Describe the bug**

**Environment:**
- OS: macOS
- Vim/Neovim version: Neovim 0.3.4
- This plugin version: 0826fab7c7ce024e72c4673af2e6388b48877d94 

**My Problem** (I guess it's not a bug)

I tried with:
```
augroup vista
    autocmd BufEnter *.go :Vista
augroup end
```

It seems doesn't work, what else should I do to toggle Vista while entering a Buf?

**Comment by liuchengxu** [comment]
works for me.
