### ISSUE TITLE
Redundant error messages when executive not available

### ISSUE THREAD

**Issue by cdelledonne** [liuchengxu/vista.vim#103]
### Describe the bug

When an executive is not available, and the user tries to launch the Vista window (e.g., with `:Vista`), an error is shown, and that's fine. For instance, for LanguageClient-neovim, the error is
```
[vista.vim]No result via LanguageClient#textDocument_documentSymbol()
```

Now, every time the user writes the buffer, or leaves and enters the buffer again, the error is shown again, even though the Vista window is not open and the user did not try to open it again. The events that trigger the error are
https://github.com/liuchengxu/vista.vim/blob/0826fab7c7ce024e72c4673af2e6388b48877d94/autoload/vista/autocmd.vim#L60-L61

### Environment

- OS: Ubuntu 18.04
- Neovim version 0.3.7
- This plugin version: 0826fab7c7ce024e72c4673af2e6388b48877d94

### Vista info

```
    Current FileType: c
Avaliable Executives: ['ctags', 'lcn']
    Global Variables:
    let g:vista#executives = ['coc', 'ctags', 'lcn', 'vim_lsp']
    let g:vista#renderer#enable_icon = 0
    let g:vista_blink = [0, 0]
    let g:vista_cursor_delay = 0
    let g:vista_executive_for = {'vim': 'lcn', 'c': 'lcn', 'rust': 'lcn', 'cpp': 'lcn', 'python': 'lcn'}
    let g:vista_fzf_preview = ['right:25%']
    let g:vista_top_level_blink = [0, 0]
```

### Steps to reproduce given the above info

1. Use `'lcn'` as executive for C files, as from **Vista info** (does this happen with other executives as well?)
2. `$ echo "int main() {}" > /tmp/test.c`
3. `$ nvim /tmp/test.c`
4. Disable LanguageClient-neovim with `:LanguageClientStop`
5. Try to launch vista.vim with `:Vista`, and confirm that the error is shown
6. Now `:write` the buffer, and confirm that, although the Vista window is not open, the error is shown again

### Expected behavior (better, preferred behavior)

Printing an error when invoking Vista with the executive not available is sensible, but repeating the error message for events not related to any invocation of Vista can be annoying. Can this be considered for fixing?

### Additional note

As an OCD-affected person, I'd like to point out that errors printed using the `vista#error#()` function have the following formatting
```
[vista.vim]Error message
```
whilst errors printed using other error functions, e.g., `vista#error#Need()`, have the following formatting
```
[vista.vim] Error message
```

In the former case, there's no space between `[vista.vim]` and the error string, whilst in the latter case there is.

Can this be made more consistent, by, for example, changing this
https://github.com/liuchengxu/vista.vim/blob/0826fab7c7ce024e72c4673af2e6388b48877d94/autoload/vista/error.vim#L56-L59
to this
```vim
function! vista#error#(msg) abort
  call s:Echo('ErrorMsg', '[vista.vim]')
  call s:Echon('Normal', ' '.a:msg)
endfunction
```
?

**Comment by cdelledonne** [comment]
@liuchengxu thank you for being so responsive.

Nevertheless, not all corner cases are covered. Try this:

1. Use `'lcn'` as executive for C files, as from **Vista info**
2. `$ echo "int main() {}" > /tmp/test.c`
3. `$ nvim /tmp/test.c`
4. Enable LanguageClient-neovim with `:LanguageClientStart`
5. Launch vista.vim with `:Vista`, and confirm that there is no error
6. Hide the Vista window with `q` (or close it with `:Vista!`)
7. Disable LanguageClient-neovim with `:LanguageClientStop`
8. Now `:write` the buffer, and confirm that, although the Vista window is not open, the error is shown

Instead of manually disabling LanguageClient-neovim, you can also trigger this behaviour by opening a file of a type that LanguageClient does not handle. For instance, try to replace the above points 7 and 8 with `:e /tmp/test.txt` and confirm that, although the Vista window is not open, the error is shown.

I think that "silencing" the error (`let t:vista.silent = v:true`) after it is shown once is not enough. Perhaps it should also be silenced when hiding (`q`) or closing (`:Vista!`) the Vista window. What do you think?

**Comment by liuchengxu** [comment]
PR is welcome.
