### ISSUE TITLE
failure to use '/' search in vista bar (vista/fzf/vim_lsp)

### ISSUE THREAD

**Issue by vsiles** [liuchengxu/vista.vim#104]
**Describe the bug**
Using vim8 / vista / vim_lsp / fzf (installed via git), I can't search in the vista bar.
I'm starting vista with `:Vista vim_lsp`, and move to the vista window and press `/`. I'm getting the following error message:
```
[vista.vim] Fail to run ctags: ctags --format=2 --excmd=pattern --fields=nksSaf --extras= --file-scope=yes --sort=no --append=no  -f- /tmp/vy9uYvV/12.ml
Error detected while processing function vista#finder#fzf#Run[31]..vista#executive#ctags#Run[1]..<SNR>176_Dispatch[12]..<SNR>176_Run:
line   11:
E121: Undefined variable: s:data
Press ENTER or type command to continue
```

Since I'm working on ocaml, I don't have ctags information.

**Environment:**
- OS: linux / centos
- VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 17 2019 00:45:18) 
- vista version 02ab82f79e2ab57e475c9932a7fb9297dbd99d3a

**Vista info**

Current FileType: ocaml
Avaliable Executives: ['ctags', 'vim_lsp']
    Global Variables:
    let g:vista#executives = ['coc', 'ctags', 'lcn', 'vim_lsp']

**Steps to reproduce given the above info**
- open file
- `:Vista vim_lsp`
- move to vista window
- press `/`

**Expected behavior**
search for my input

**Actual behavior**
error message and closing vista window

**Comment by vsiles** [comment]
`:Vista finder` triggers the same error

**Comment by liuchengxu** [comment]
Cannot reproduce with this minimal vimrc:

```vim
call plug#begin('~/.vim/plugged')
Plug 'liuchengxu/vista.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
call plug#end()

let g:vista#executives = ['coc', 'ctags', 'lcn', 'vim_lsp']
```

**Comment by vsiles** [comment]
In order to vim-lsp to work, I need a couple more plugin. Here is a minimal vimrc to repro:
```
set nocp

call plug#begin('~/.vim/plugged')
Plug 'liuchengxu/vista.vim'
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
call plug#end()

let g:vista#executives = ['coc', 'ctags', 'lcn', 'vim_lsp']

if executable('ocaml-language-server')
  au User lsp_setup call lsp#register_server({
        \ 'name': 'ocaml-language-server',
        \ 'cmd': {server_info->[&shell, &shellcmdflag, 'opam config exec -- ocaml-language-server --stdio']},
        \ 'whitelist': ['reason', 'ocaml'],
        \ })
endif
```

**Comment by vsiles** [comment]
Here is a live demo if you don't have any ocaml handy: https://asciinema.org/a/QSoAK9W3lcSiEevShEMpJ9Hnq

**Comment by liuchengxu** [comment]
The error you posted is related to `ctags`, not `ocaml-language-server`.

**Comment by vsiles** [comment]
sorry, that's how I repro it. I guess my ctag binary is hold (work managed server, no one is using that). Is there a way to disable ctag usage in vista ?

**Comment by CPWeaver** [comment]
I have the same problem, using vista with `coc` as source. Very occasionally the search will work properly but usually I get a ctags error. I don't want to use ctags at all but I have an old out of date ctags binary on my system. I just want vista to complete and search from coc/lsp.

**Comment by liuchengxu** [comment]
Actually you can always use`:Vista finder coc` to stick with doc, just like `:Vista coc`.

Any you could also try this to use coc solely in the vista finder:

```vim
let g:vista_finder_alternative_executives = ['coc']
```

**Comment by vsiles** [comment]
@liuchengxu After updating the plugin and use `vista_finder_alternative_executives`, I still get the same error / behavior. Is there a way to disable ctags explicitely from being used ? ctags is totally irrelevant in my case and I don't want it to be called at all.

**Comment by liuchengxu** [comment]
Pull the latest commit and ensure `let g:vista_default_executive = 'vim_lsp'` and `let g:vista_finder_alternative_executives = ['coc']`, then ctags won't be called any more.

**Comment by vsiles** [comment]
Thanks, I was missing the `coc` part. Now the plugin no longer crash but I'm getting a `[vista.vim] Empty data for finder` message. I'll investigate that on my setup.
