### ISSUE TITLE
Toggle and open to current function

### ISSUE THREAD

**Issue by mnussbaum** [liuchengxu/vista.vim#107]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to assign a single shortcut key to open Vista to the function closest to the cursor, or close Vista if it's already open.

**Describe the solution you'd like**
One solution might be to have `Vista!!` take `show` as an argument to combine both toggle and show behaviors.

**Describe alternatives you've considered**
As far as I can tell there's no way to combine `show` behavior with toggling. I hope I haven't missed anything in the docs about this!

**Comment by liuchengxu** [comment]
The default behavior now is to jump to the nearest tag when opening the vista window if possible.

**Comment by mnussbaum** [comment]
Thanks!!
