### ISSUE TITLE
close vista window automatically when it's the last window open

### ISSUE THREAD

**Issue by frescoraja** [liuchengxu/vista.vim#108]
i would like the vista window to automatically close if i execute `:quit` from the window it's displaying symbols from.. current behavior seems to leave it open, even if it's the last window.
is this a bug on my machine, or intended behavior?
thanks

**Comment by liuchengxu** [comment]
Vista.vim doesn't have this feature.

**Comment by frescoraja** [comment]
thanks,
just in case anyone is interested, i used the following autocmd to implement this behavior:

`autocmd BufEnter * if winnr("$") == 1 && vista#sidebar#IsVisible() | execute "normal! :q!\<CR>" | endif`

**Comment by 675816156** [comment]
> thanks,
> just in case anyone is interested, i used the following autocmd to implement this behavior:
> 
> `autocmd BufEnter * if winnr("$") == 1 && vista#sidebar#IsVisible() | execute "normal! :q!\<CR>" | endif`

since IsVisible is not supported, try this:

`autocmd bufenter * if winnr("$") == 1 && vista#sidebar#IsOpen() | execute "normal! :q!\<CR>" | endif`

**Comment by ternenges** [comment]
in case someone comes looking  if that doesn't work then try this
```
# lua

local auc = vim.api.nvim_create_autocmd

auc("BufEnter",{
pattern = "*",
callback = function()
   local win = #vim.api.nvim_list_wins() == 1
   local name = vim.api.nvim_buf_get_name(0) == "$HOMEPATH/.config/nvim/__vista__"

  if win and name then 
    vim.cmd "silent! q!"
  end
end
})
```

**Comment by WanGong** [comment]
This is work for me:

```
vim.api.nvim_create_autocmd({ "BufEnter" }, {
	pattern = { "*" },
	callback = function()
		local is_only_one_win = vim.fn.winnr("$") == 1
		local is_vista_open = vim.fn["vista#sidebar#IsOpen"]() == 1

		if is_only_one_win and is_vista_open then
			vim.cmd("silent! q!")
		end
	end,
})
```
