### ISSUE TITLE
open Vista sidebar automatically for certain filetypes that use coc executive

### ISSUE THREAD

**Issue by frescoraja** [liuchengxu/vista.vim#109]
**Is your feature request related to a problem? Please describe.**
I would like Vista sidebar to open automatically when opening certain filetypes... something like:
`autocmd BufWinEnter *.go,*.proto Vista`
unfortunately, since the executive for my go files is `coc`, i think the symbols have not yet been loaded by the time the bufwinenter event has fired. so vista sidebar does not appear. (it is hidden or something , because i have to execute Vista!! twice in order for vista sidebar to appear once symbols have loaded/coc is running)

**Describe the solution you'd like**
open vista sidebar even if coc hasn't loaded yet, and "reload" once coc has loaded symbols.

**Describe alternatives you've considered**
i've tried other events to trigger Vista command with no success

thanks for looking into it, let me know if it's not possible

**Comment by liuchengxu** [comment]
That needs time to take care of the details. I'm not sure when I can get these time.
