### ISSUE TITLE
"E121: Undefined variable: t:vista" on :Vista!!

### ISSUE THREAD

**Issue by oblitum** [liuchengxu/vista.vim#110]
**Describe the bug**

Calling `:Vista!!` without calling `:Vista` at least once generates the following error:

```
Error detected while processing function vista#:
line    7:
E121: Undefined variable: t:vista
```

Calling `:Vista` once avoids the issue.

**Environment:**
- OS: ArchLinux
- Vim/Neovim version: NVIM v0.4.0-1051-g149dcbf2c
- This plugin version: c265aae

**Vista info**

```
    Current FileType: cpp
Avaliable Executives: ['coc', 'ctags']
    Global Variables:
    let g:vista#executives = ['coc', 'ctags', 'lcn', 'vim_lsp']
    let g:vista_executive_for = {'typescript': 'coc', 'go': 'coc', 'c': 'coc', 'javascript': 'coc', 'html': 'coc', 'rust': 'coc', 'cpp': 'coc', 'css': 'coc', 'python': 'coc'}
    let g:vista_icon_indent = ['╰─🞂 ', '├─🞂 ']
    let g:vista_sidebar_width = 61
```

**Steps to reproduce given the above info**

1. Open nvim
2. `:Vista!!`

**Expected behavior**

No errors.

**Actual behavior**

```
Error detected while processing function vista#:
line    7:
E121: Undefined variable: t:vista
```

**Comment by liuchengxu** [comment]
Please pull the latest commit, should be fixed.
