### ISSUE TITLE
vista.vim does not work with exuberant-ctags (Ubuntu 18.04)

### ISSUE THREAD

**Issue by graves501** [liuchengxu/vista.vim#112]
**vista.vim does not work with exuberant-ctags (Ubuntu 18.04)**

First of all, **thank you** for this awesome plugin!

After running this command
```
sudo apt install ctags
```
`exuberant-ctags` gets installed on Ubuntu-based systems.
This ctags implementation doesn't seem to work with `vista.vim`. There are no tags for in the sidebar for `JavaScript` or `Java` files and many other filetypes.

A possible workaround/solution is installing removing `exuberant-ctags` and `universal-ctags`.
A short script for installing `universal-ctags`:
```
git clone https://github.com/universal-ctags/ctags.git
cd ctags
./autogen.sh
./configure
make
sudo make install
```

**Environment:**
- OS: Ubuntu 18.04
- Neovim version: 
    NVIM v0.3.7
    Build type: Release
- This plugin version: 31d770c601a291d1e2a334bcdd016b8d73e8d310

**Comment by liuchengxu** [comment]
As the README declares, vista.vim is only guaranteed to work with universal-ctags.

> View tags and LSP symbols in a sidebar.
>    -  universal-ctags

**Comment by graves501** [comment]
@liuchengxu Thank you for your reply. Maybe mention in the README that `exuberant-ctags` will NOT work in the Ubuntu section since it is the default that gets installed. 
I might not be the last one to run into this problem and people should be able to instantly enjoy this plugin :)
