### ISSUE TITLE
Show parent class with vista_nearest_method_or_function or add currentag function

### ISSUE THREAD

**Issue by petobens** [liuchengxu/vista.vim#114]
Hi! Consider the following simple python file:
```python
class Foo:
    def __init__(self, x):
        self.x = x
````
If I place the cursor at `self.x` and run `:echo b:vista_nearest_method_or_function` I get an empty result whereas if I use Tagbar's `:echo tagbar#currenttag('%s', '', 'f')` I get `Foo.__init__()`. So my question is: is it possible to make `vista_nearest_method_or_function` more similar to Tagbar's `currentag`? Or introduce a new currenttag function that works like Tagbar's one. Thanks!!

**Comment by liuchengxu** [comment]
`b:vista_nearest_method_or_function` means it's only for the tag whose kind is method(and member) or function. `currenttag` of Tagbar seems to be any kind of tag. The semantic is different.

https://github.com/liuchengxu/vista.vim/blob/268a88df5a62fa35b5f4794df5ee60a0be9ba1f7/autoload/vista/parser/ctags.vim#L28-L35

**Comment by petobens** [comment]
I see. That's why I asked if something like `currentag` could be implemented (it would be useful for statusline plugins and, I would personally use it, to run modular unit test (i.e only by class, method, etc)). Any chance of adding it?

**Comment by liuchengxu** [comment]
See #121. But it still won't return `Foo.__init__()`, but a raw nearest symbol `__init__`.

**Comment by petobens** [comment]
Thank you. I've made a comment in the PR.

**Comment by syphar** [comment]
@liuchengxu 
first of all, thanks for vista! it's really awesome and fast :) 

secondly Nearest symbol here already helps me with my workflow (though it's then not async any more? )
But is there any way to add the parent so I can see the class I'm in? 

I understand the combination of hierarchy and ctags is tricky, but tagbar solved it somehow?

**Comment by liuchengxu** [comment]
>though it's then not async any more? )

The raw external tags info is always fetched in async. Finding the nearest symbol from these raw tags is sync, but should be fast enough normally.

>But is there any way to add the parent so I can see the class I'm in?

Not now. https://github.com/liuchengxu/vista.vim/pull/211 may help, but it's still a WIP and I do know when it will be merged.

>I understand the combination of hierarchy and ctags is tricky, but tagbar solved it somehow?

Not sure about that.
