### ISSUE TITLE
Add option to control initial fold level

### ISSUE THREAD

**Issue by petobens** [liuchengxu/vista.vim#115]
Is it possible to add an option to control the initial fold level? AFAICT vista starts with everything unfolded but it would be nice to add something like `g:vista_foldlevel`. Thanks!

**Comment by liuchengxu** [comment]
I'm not interested in this feature and it may need some work. I basically won't implement it myself, but PR is welcome.

**Comment by teto** [comment]
I am not fond of overriding legacy vim folding, for instance zO/zC don't work out of the box. And the default tree takes too much space.
I would vote for reliying on basic vim folds. With  https://github.com/neovim/neovim/pull/11568, you might even get similar styling.
