### ISSUE TITLE
Disable folding in preview window

### ISSUE THREAD

**Issue by petobens** [liuchengxu/vista.vim#116]
Is it possible to disable folding in the preview window? Currently folds are enabled which makes the preview window less useful since one cannot actually see the code:

![image](https://user-images.githubusercontent.com/2583971/60934964-96cc1380-a29e-11e9-8d72-2b25ec37b17f.png)

**Comment by liuchengxu** [comment]
Please fill the issue template and post the reproducible minimal vimrc and steps.

**Comment by petobens** [comment]
Thank you
