### ISSUE TITLE
Add denite source to search/filter symbols

### ISSUE THREAD

**Issue by petobens** [liuchengxu/vista.vim#117]
It would be really nice to have denite source to fiter/search tags similarly to fzf. If you can suggest a few pointers I can try to implement it myself. Thanks!

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/vista.vim/blob/b576f1914722c4407f45066ab8bffd7438377589/autoload/vista/finder/fzf.vim#L208-L223

I have extracted `vista#finder#GetSymbols()` for easily adding new finder for vista.vim, which returns:

- `s:data`: a Dict of various symbols, key is the tag/symbol kind, value is the list of the tag/symbols whose kind is the key. `col` field doesn't exist for the ctags executive, but for LSP executvies for now. Example for `s:data`:
  
 ```
 {  
   'Method':[  
      {  
         'lnum':51,
         'col':26,
         'text':'ValidateBody'
      },
      {  
         'lnum':80,
         'col':26,
         'text':'ValidateState'
      }
   ],
   'Function':[  
      {  
         'lnum':39,
         'col':6,
         'text':'NewBlockValidator'
      },
      {  
         'lnum':108,
         'col':6,
         'text':'CalcGasLimit'
      }
   ],
   'Field':[  
      {  
         'lnum':33,
         'col':2,
         'text':'config'
      },
      {  
         'lnum':34,
         'col':2,
         'text':'bc'
      },
      {  
         'lnum':35,
         'col':2,
         'text':'engine'
      }
   ],
   'Class':[  
      {  
         'lnum':32,
         'col':6,
         'text':'BlockValidator'
      }
   ]
}
   ```
- `s:cur_executive`: the provider of the return symbols.
- `s:using_alternative`: is using the alternative executive, not the one called explicitly.

Once you get all the symbols, you could feed them into your denite finder.

**Comment by petobens** [comment]
Ok thanks! I'll give it a shot when I find some time.

**Comment by weilbith** [comment]
Any update?
