### ISSUE TITLE
Keep cursor in original window when quitting vista

### ISSUE THREAD

**Issue by petobens** [liuchengxu/vista.vim#118]
Consider the following minimal init.vim file (named `vimrc_min`):
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/liuchengxu/vista.vim
filetype plugin indent on

let g:vista_sidebar_position = 'vertical topleft'
```
Now, as in the GIF, do:
1. Open nvim and edit the `vimrc_min` file.
2. Open a vertical split with `:vsp` and move to the right window with `<C-w>l` mapping
3. Run `:Vista`
4. Once the `Vista` buffer opens quit it with `q` mapping

After 4. I expect the cursor to be on the right window (which is the window that called the vista buffer); instead it's on the left.

![vista-cursor](https://user-images.githubusercontent.com/2583971/60981594-0547ba80-a30d-11e9-8ceb-c62797378a66.gif)

**Comment by liuchengxu** [comment]
`q` mapping is a plain `close` command by default which won't wipe the buffer actually. You could use `:Vista!!` for toggling the vista sidebar by wiping the buffer. Or remap `q`:

```vim
autocmd FileType vista nnoremap <buffer> q :call vista#sidebar#Close()<CR>
```

**Comment by petobens** [comment]
Awesome. Thanks
