### ISSUE TITLE
Random red highlights in fzf 

### ISSUE THREAD

**Issue by Avi-D-coder** [liuchengxu/vista.vim#12]
![ezgif-2-f32cefb30b35](https://user-images.githubusercontent.com/29133776/52943224-acb25980-333a-11e9-9624-e9e2ba76ce0a.gif)

**Comment by liuchengxu** [comment]
I never run into this issue. Maybe it's just related your own config? Can you provide a minimal vimrc to try with?

**Comment by Avi-D-coder** [comment]
Your right this seems only occur with https://github.com/liuchengxu/vista.vim/pull/11

**Comment by liuchengxu** [comment]
Confirmed, I also see this issue occasionally with #11.
