### ISSUE TITLE
Tempdir code tries writing to root owned path

### ISSUE THREAD

**Issue by jrudess** [liuchengxu/vista.vim#124]
The new tempdir code in 310ca5b9e98acf4f1ce841e11a33cf840c2621de is trying to access a root owned path using Vim 8.1 in linux.

The problem is a missing / between the temp-directory and sha-hash so the paths end up in the form "/tmp3ab83353affetcetc"

The following patch appears to solve it for my environment which has $TMPDIR set to '/tmp'

```
let tmp = '/' . sha256(fnamemodify(bufname(t:vista.source.bufnr), ":p"))
```

**Comment by daveyarwood** [comment]
I'm experiencing this issue as well, even after updating to e08bb0b.

I can see why e08bb0b doesn't fix the issue. On my system, `TMPDIR` is set to a directory that doesn't have a slash on the end -- which makes sense, I think, as a convention:

```
$ echo $TMPDIR
/tmp/user/1000
```

I think the slash was added in the wrong place, i.e. vista.vim should assume that TMPDIR does _not_ end in a slash, and prepend a slash to the route being added to it. Hopefully that makes sense.

**Comment by daveyarwood** [comment]
![2019-07-17-124656_1727x115_scrot](https://user-images.githubusercontent.com/4909079/61394384-f921a700-a890-11e9-85dd-8c7bb942b471.png)

^ This is the symptom.

**Comment by liuchengxu** [comment]
I have pushed a commit to catch the error and fall back to the safe `tempname()` way. Hopefully it could fix your issue. @dav

**Comment by petobens** [comment]
When running `:Vista` I'm now seeing the following:
```viml
Error detected while processing function vista#[24]..vista#sidebar#Open[12]..vista#executive#ctags#Execute[2]..<SNR>168_Dispatch[12]..<SNR>168_Execute[3]..<SNR>168_ApplyExecute[1]..<SNR>168_IntoTemp:
line   38:
E121: Undefined variable: tmp
E116: Invalid arguments for function writefile
E15: Invalid expression: writefile(lines, tmp) == 0
```

**Comment by liuchengxu** [comment]
@petobens Can you provide a minimal vimrc? I can't reproduce.

**Comment by daveyarwood** [comment]
That commit fixes the issue for me.

**Comment by joshuarubin** [comment]
Same issue as @petobens, `$TMPDIR` is not set so there is nothing to `catch` as a result `tmp` is never initialized.

**Comment by liuchengxu** [comment]
Thanks @petobens @joshuarubin . Please pull the latest commit, should be fixed.

**Comment by joshuarubin** [comment]
looks good, thx

**Comment by petobens** [comment]
Thanks!
