### ISSUE TITLE
Document how to set up nested class outline

### ISSUE THREAD

**Issue by gmolau** [liuchengxu/vista.vim#127]
**Is your feature request related to a problem? Please describe.**
This looks like a great plugin, but I'm a bit confused about the default module/class/variable/function outline structure. I thought the whole point of a tool like this was to give an overview of the objects in a file as they are defined, i.e.

```
- Class1
    - Method1
    - Method2

- globalFunc1

- Class2
    - Method1
```

**Describe the solution you'd like**
Looking through older issues it seems that it is possible to configure Vista that way, but it is not documented and I have not gotten it to work. It would be nice if this could be mentioned in the README. 

**Describe alternatives you've considered**
To be honest, I don't quite get why this isn't the default. In Tagbar it isn't even possible to list all methods of all classes under one node, is there a reason why anyone want this?

**Comment by liuchengxu** [comment]
Tagbar doesn't support LSP, while vista.vim does. Only the ctags executive supports the nested display, try it via `:Vista ctags`. The other LSP executives only supports the `kind` renderer which lists all items under some group for now.

**Comment by gmolau** [comment]
Hm, if this is an LSP limitation then that's how it is, but I feel like this should still be mentioned in the docs somewhere. To me it seems like getting a nested module->class->method outline is the whole point of a tool like Tagbar, and since Vista is marketed as a modern alternative to Tagbar I find it rather surprising that this is not actually possible. One or two sentences in the readme would have saved me a few hours of tinkering here.

**Comment by liuchengxu** [comment]
> Nested display for ctags.

Maybe more explicit?

The other feature of vista.vim that tagbar doesn't have is the builtin finder, which could take advantage of both ctags and LSP.

**Comment by gmolau** [comment]
Maybe one could highlight that ctags supports a tree view whereas LSPs is more like a list (i.e. `Nested tree display for ctags, list by symbol type for LSP` or something similar).

Another idea would be to include screenshots of the different renderers side-by-side, maybe as a new sibling node next to `Usage > Options`.

**Comment by liuchengxu** [comment]
Feel free to open up a PR.
