### ISSUE TITLE
How to setup to work with fzf?

### ISSUE THREAD

**Issue by lourenci** [liuchengxu/vista.vim#13]
How can I get this plugin working with fzf?

I didn't find anything relevant in the README.md.

Thanks.

**Comment by liuchengxu** [comment]
If you have both installed [fzf](https://github.com/junegunn) and [vista.com](https://github.com/liuchengxu/vista.vim), `:Vista finder` would invoke fzf to filter symbols/tags. 

`:Vista finder` is essentially `:Vista finder ctags`, tags generated by ctags is used by default. 

You could specify an executive for the finder. `:Vista finder coc` could filter document symbols from coc.nvim. Currently only `coc` and `ctags` are supported.

If you would like to enable the preview feature of fzf, ensure the related preview tools have been set up already and add `let g:vista_fzf_preview = ['right:50%']` in your .vimrc.
