### ISSUE TITLE
The Vista sidebar does not update when adding a new function

### ISSUE THREAD

**Issue by gbcreation** [liuchengxu/vista.vim#130]
**Describe the bug**

The Vista sidebar does not update to show a newly created JavaScript function.

**Environment:**
- OS: ArchLInux
- Neovim version: NVIM v0.3.8 - Build type: Release
- This plugin version: 1b37a698d7255d403fb385f2e2934166168ee3c1

**Vista info**

```
Current FileType: javascript
Avaliable Executives: ['coc']
    Global Variables:
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'vim_lsp']
    let g:vista#renderer#ctags = 'default'
    let g:vista#renderer#enable_icon = 1
    let g:vista#renderer#icons = {'subroutine': '洛', 'method': '', 'func': '', 'variables': '', 'namespace': '', 'field': '綠', 'interface': '禍', 'type': '', 'packages': '', 'proper
ty': '襁', 'implementation': '', 'default': '', 'augroup': 'פּ', 'macro': '', 'enumerator': '', 'const': '', 'macros': '', 'map': 'פּ', 'fields': '綠', 'functions': '', 'enum': '', 'f
unction': '', 'target': '', 'typedef': '', 'variable': '', 'modules': '', 'constant': '', 'struct': 'פּ', 'types': '', 'module': '', 'typeParameter': '', 'package': '', 'class': '
', 'member': '', 'var': '', 'union': '鬒'}
    let g:vista_default_executive = 'coc'
```

**Steps to reproduce given the above info**

1. Open a JavaScript file
2. Open the Vista sidebar
3. Add a new function to the JavaScript file (don't save the file)

**Expected behavior**

The newly created JavaScript function should appear in the Vista sidebar.

**Actual behavior**

The newly created JavaScript function does not appear in the Vista sidebar.

**Comment by liuchengxu** [comment]
That's expected. See https://github.com/liuchengxu/vista.vim/blob/master/autoload/vista/autocmd.vim#L60 .

Let me know if you have better strategies.

**Comment by liuchengxu** [comment]
I have added an option `g:vista_update_on_text_changed` for ctags executive, `:h g:vista_update_on_text_changed`.

But for the LSP executives, there are not much things vista.vim can do.
