### ISSUE TITLE
tagbar w/ gotags is friendly then vista w/ lcn

### ISSUE THREAD

**Issue by butterflyfish** [liuchengxu/vista.vim#131]
![image](https://user-images.githubusercontent.com/14833825/61701853-693c9b00-ad71-11e9-8bd3-0748971e2191.png)

It's obvious tagbar w/ [gotags](https://github.com/jstemmer/gotags) provides better user experience.

demo file is from go library flag, go/1.12.1/libexec/src/flag/flag.go

**Comment by liuchengxu** [comment]
>Nested display for ctags, list display for LSP symbols.

Try `:Vista ctags`. But these is indeed a room for improvement, at least for the go files.

**Comment by butterflyfish** [comment]
"Vista ctags" is not friendly, because ctags can not parse go file ver well like gotags. Hope anyone can improve this. I'm just a user, don't know how to write vim script.

**Comment by liuchengxu** [comment]
If `gotags` is ctags compatible, you can try using `gotags` as the executable of ctags, `:h vista_ctags_cmd`.

**Comment by butterflyfish** [comment]
hope someone can send PR to improve output of 'vista lcn'. if so, I can drop tagbar

**Comment by liuchengxu** [comment]
As I've mentioned before, it's not easy to improve the LSP display. You can try the option `:h vista_ctags_cmd`.
