### ISSUE TITLE
Incorrect return after closing.

### ISSUE THREAD

**Issue by ur4ltz** [liuchengxu/vista.vim#132]
Hi!
Open 2 files vertical split.
"vim -O2 file.1 file.2"
Curent file.1 (left).
Call Vista!! "nnoremap <silent><F9> :Vista!!<CR>"
Close Vista!! <F9>
After closing, the current file became file.2 and not file.1 as expected!

Thank you for your work in writing this plugin!

**Comment by liuchengxu** [comment]
If you invoke `:Vista!!` in any non-vista window, you will stay where you are. But if you call `:Vista!!` in the vista window, then you will go to the _previous_ window since I don't know what the original window is.

**Comment by ur4ltz** [comment]
Please see this video.
https://drive.google.com/file/d/1sIARSTEdcLCW8AGXyXRNvHBshM8jK-_e/view?usp=sharing
Sorry for the quality.

**Comment by liuchengxu** [comment]
I have said that the current strategy is to go to the previous window if you call `:Vista!!` in the vista window. Show me your new ideas about this case.

**Comment by ur4ltz** [comment]
>> Show me your new ideas about this case.

See video!
Test 1. Return to "README.md" !!! BUG!!!
Test 2. Return to ":help vista" !!! BUG!!!
I was expecting a return to "minimal.vimrc-lua" !!!

**Comment by liuchengxu** [comment]
PR is welcome.
