### ISSUE TITLE
Default installation does not reflect screenshot in documentation

### ISSUE THREAD

**Issue by aste4** [liuchengxu/vista.vim#135]
**Describe the bug**
Default installation does not seem to reflect the [screenshot](https://user-images.githubusercontent.com/8850248/55805524-2b449f80-5b11-11e9-85d4-018c305a5ecb.png)
(missing` ["╰─▸ ", "├─▸ "] `not showing up)

**Environment:**
- OS: Debian Buster
- Vim/Neovim version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 16:41:15)
Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401

**Steps to reproduce given the above info**

```
FROM debian:buster

RUN apt-get update && apt-get install -y git cmake make g++ python-dev python3-dev curl vim

RUN mkdir -p ~/.vim/autoload /roo/.vim/bundle && \
    curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

RUN git clone https://github.com/liuchengxu/vista.vim.git /root/.vim/bundle/vista_vim
RUN apt-get -y install libjansson-dev git autoconf pkg-config
RUN git clone https://github.com/universal-ctags/ctags.git --depth=1
RUN cd ctags && ./autogen.sh --noconfigure && ./configure && make -j4 install

RUN echo "execute pathogen#infect()" >> ~/.vimrc
RUN echo "syntax on" >> ~/.vimrc
RUN echo "filetype plugin indent on" >> ~/.vimrc
RUN echo "set encoding=utf-8" >> ~/.vimrc
```

```
$ docker build -t my_test_image .
$ docker run -i -t my_test_image /bin/bash
$ vim /root/.vim/bundle/vista_vim/autoload/vista.vim
```

**Expected behavior**
The icon's showing up like in the screenshot
let g:vista_icon_indent = ["╰─▸ ", "├─▸ "]

**Actual behavior**
The icon's not showing up

Please let me know if you need any more information.

**Comment by liuchengxu** [comment]
`g:vista_icon_indent` only applies to the LSP executives. The command used in the screenshot is `:Vista ctags`.

**Comment by aste4** [comment]
Thank you very much! That works! 

If you can, could elaborate a little more on the difference between the 2 scenarios? What is an LSP executive/kind renderer? I am hoping to understand this plugin better. I'll read again through the Vista docs as well as ctags docs to better understand the behavior.

**Comment by liuchengxu** [comment]
See also #127. There is indeed a room for improvement for the docs, but I'm a little busy recently. Basiclly the LSP executive currently doesn't support the tree view and can use the `kind` renderer only. But the ctags executive supports tree view, thus both the `default` renderer(nested display) and `kind` renderer.
