### ISSUE TITLE
Vista finder error if buffer isn't saved

### ISSUE THREAD

**Issue by ranebrown** [liuchengxu/vista.vim#139]
If the buffer hasn't been saved I am seeing this error after selecting a tag with `Vista finder`. (It also messes up the syntax highlighting in the Vista sidebar and the open buffer.)

```vim
Error detected while processing function vista#[33]..vista#finder#fzf#Run[12]..<SNR>160_R
un[15]..<SNR>160_ApplyRun:
line   25:
E37: No write since last change (add ! to override)
```

Minimal vimrc:
```vim
set nocompatible

call plug#begin('~/.vim/plugged')
    Plug 'liuchengxu/vista.vim'
    Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
    Plug 'junegunn/fzf.vim'
call plug#end()

set hidden
let mapleader=','

let g:vista_executive_for = {
  \ 'cpp': 'ale',
  \ 'c': 'ale',
  \ 'markdown': 'toc',
  \ }
nmap <silent><leader>b :Vista!!<CR>
let g:vista_blink = [0,0]
let g:vista_top_level_blink = [0,0]
```

Vim version:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 21 2019 22:54:00)
macOS version
Included patches: 1-1722
```

**Comment by liuchengxu** [comment]
Can't reproduce with the vimrc you provided.

**Comment by liuchengxu** [comment]
Okay, I can reproduce it using vim, but not neovim.

**Comment by ranebrown** [comment]
The fix you added discards any local changes you have which isn't really desirable behavior. I would also argue against automatically saving the file since that might not be what the user wants either.

**Comment by liuchengxu** [comment]
I don't any other solutions.

**Comment by ranebrown** [comment]
What is the purpose of `s:Highlight()`? Trying to change the syntax highlighting definitions seems to be what causes the problem. Just removing [these lines](https://github.com/liuchengxu/vista.vim/blob/6d3ae09ebaf4614f9465d10dfa8855277a0f3643/autoload/vista/finder/fzf.vim#L131-L139) fixes the issue.

**Comment by liuchengxu** [comment]
It's used to add highlights to the fzf buffer.

**Comment by liuchengxu** [comment]
I have disabled the fzf highlight for vim. This seems to be a good solution for now.
