### ISSUE TITLE
How to use finder for the whole project?

### ISSUE THREAD

**Issue by gbrlsnchs** [liuchengxu/vista.vim#14]
Firstly, this plugin is awesome. Something that has been missing for Vim for some time. So thank you.

When I use `:Vista finder`, I can only retrieve the buffer tags, like `:BTags` from FZF. How can I use `:Vista finder` to find symbols for the whole project, just like `:Tags`?

**Comment by liuchengxu** [comment]
Hmm, vista currently doesn't have the `:Tags` support, but it's not very hard to implement.

**Comment by liuchengxu** [comment]
I add an initial sync version of `ctags -R` in [this branch](https://github.com/liuchengxu/vista.vim/tree/support-ctags-R). You could try it out via `:Vista finder!`. `ctags -R` is very slow for big projects, I personally won't use it on these projects :(.

**Comment by liuchengxu** [comment]
The branch has been merged into the master. Now you can pull the latest version and try it via `:Vista finder!` to use ctags recursively.

**Comment by gbrlsnchs** [comment]
Thanks! I won't open this issue again, I just want to know... does LSP implements project-wise tags? Or only for a single file?

**Comment by liuchengxu** [comment]
Yes, LSP has a similar concept `workspace symbols`, but vista.vim now only integrates the document symbols of LSP, which is only for a single file. The workspace symbols could also be easily introduced in vista.vim whenever I get some time.

**Comment by gbrlsnchs** [comment]
Cool. Maybe I'll open another issue to request such feature. Good job and thanks again!

**Comment by liuchengxu** [comment]
Feel free to file another one.

**Comment by ClashTheBunny** [comment]
Did you end up filing a bug for workspace symbols?  I'm comparing this to other projects and I think it would be a nice feature.

**Comment by gbrlsnchs** [comment]
> Did you end up filing a bug for workspace symbols? I'm comparing this to other projects and I think it would be a nice feature.

No, I ended up not opening the issue... please feel free to do so, it would be awesome!
