### ISSUE TITLE
Show TOC for pandoc filetype

### ISSUE THREAD

**Issue by xinhangliu** [liuchengxu/vista.vim#141]
Currently, vista.vim only support show TOC for markdown filetype.

Can vista.vim support other filetypes? For example, pandoc.

Or provide a customizable option.

**Comment by liuchengxu** [comment]
That's doable via a vista extension for pandoc, take https://github.com/liuchengxu/vista.vim/blob/master/autoload/vista/extension/markdown.vim as reference.

**Comment by sheriferson** [comment]
I have a followup question on this: I get a confusing error message when trying to run `:Vista toc` that implies that toc _only_ works for pandoc filetype:

```
:Vista toc
[vista.vim] Vista toc only exists in pandoc filetype.
```

Even though the current filetype is indeed pandoc

```
:set filetype?
 filetype=pandoc   
```

So is the error message misleading?

Changing the current filetype to markdown does allow toc to run

```
:set filetype=markdown
:Vista toc <-- this works
```

So there are multiple confusing things going on, but Vista does show a toc for pandoc filetypes if you just run `:Vista` without the added `toc`.

**Comment by liuchengxu** [comment]
The error message is indeed misleading.

I don't write pandoc, and I never tested if `:Vista toc` can work with it. Seems like pandoc also have the markdown like format?

**Comment by sheriferson** [comment]
> Seems like pandoc also have the markdown like format?

Yes. As far as I know, pandoc is just a filetype that some popular Markdown vim plugins set the file to (or expect the file to have) to make the things they do easier.

See [vim-pandoc](https://github.com/vim-pandoc/vim-pandoc) and [vim-pandoc-synctax](https://github.com/vim-pandoc/vim-pandoc-syntax). They work with Markdown files. Same extensions and same expected file format (at least as far as a table of content is concerned).

There are some advanced Markdown features that pandoc supports, but the base Markdown format works.

**Comment by liuchengxu** [comment]
Thanks for the info. I have updated the doc. You can try `let g:vista_executive_for = { 'pandoc': 'markdown' }` to reuse the markdown extension for pandoc filetype.
