### ISSUE TITLE
How to set show long types.kinds, not fold key

### ISSUE THREAD

**Issue by MrZhang123** [liuchengxu/vista.vim#144]
### Describe

When I open vista , I find the key is fold , not long , like this :

![image](https://user-images.githubusercontent.com/13158765/63517400-83f56180-c521-11e9-95cf-ffe83dcc8ef5.png)

I check the source code and find `types/uctags/javascript.vim' definite the `type.kinds`  like this:

![image](https://user-images.githubusercontent.com/13158765/63517278-442e7a00-c521-11e9-9810-2372d4e82477.png)

I want set to show `long` , like `function` not `f`, `global variables` not `v`, how to set ?

**Comment by liuchengxu** [comment]
`types/uctags/*` is only applicable to the ctags executive, try it via `:Vista ctags`.

**Comment by MrZhang123** [comment]
@liuchengxu I try to run `Vista ctags`, but it not work , still show fold key

**Comment by liuchengxu** [comment]
vista.vim supports both ctags and LSP executives, ensure you installed the requirements. Additionally, always fill the issue template please, otherwise I can't help.

**Comment by MrZhang123** [comment]
@liuchengxu Sorry for that,  i use `brew install --HEAD universal-ctags/universal-ctags/universal-ctags`  to install ctags , and run `Vista` in vim , this is  my vista info:

```
Current FileType: javascript.jsx
Avaliable Executives: ['ctags']
    Global Variables:
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'vim_lsp']
    let g:vista#renderer#ctags = 'vista_kind'
    let g:vista#renderer#enable_icon = 0
    let g:vista_default_executive = 'ctags'
```

### Environment

* MacOS 10.14.6
* Vim 8.1.1722

**Comment by MrZhang123** [comment]
@liuchengxu Sorry for that,  i use `brew install --HEAD universal-ctags/universal-ctags/universal-ctags`  to install ctags , and run `Vista` in vim , this is  my vista info:

```
Current FileType: javascript.jsx
Avaliable Executives: ['ctags']
    Global Variables:
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'vim_lsp']
    let g:vista#renderer#ctags = 'vista_kind'
    let g:vista#renderer#enable_icon = 0
    let g:vista_default_executive = 'ctags'
```

### Environment

* MacOS 10.14.6
* Vim 8.1.1722

**Comment by liuchengxu** [comment]
I suggest you using the default renderer for ctags, the other ones are not will maintained, I personally do not use them.

```vim
let g:vista#renderer#ctags = 'default'
```

`:h g:vista#renderer#ctags`.

**Comment by MrZhang123** [comment]
@liuchengxu It still not work , if i set 

```
let g:vista#renderer#ctags = 'default'
```
it's look like this :

![image](https://user-images.githubusercontent.com/13158765/63563594-23533c80-c594-11e9-9d9b-7af86bd882c3.png)

Otherwise , if show icons , I need to install `vim-devicons` ?

**Comment by liuchengxu** [comment]
Can't reproduce. No need to install `vim-devicons`, see `:h g:vista#renderer#enable_icon`.

![image](https://user-images.githubusercontent.com/8850248/63563838-1be06300-c595-11e9-8c3a-b13d1d9b3722.png)

Please provide the minimal vimrc and steps to reproduce.

**Comment by MrZhang123** [comment]
@liuchengxu I remove all the vista config use it default , but my tag bar look like this : 

![image](https://user-images.githubusercontent.com/13158765/63567411-13dbef80-c5a4-11e9-8ea5-6972ecc2d1b1.png)

the `vista info`

![image](https://user-images.githubusercontent.com/13158765/63567431-2ce4a080-c5a4-11e9-9f99-772356384253.png)

I install universal-ctags use `brew install --HEAD universal-ctags/universal-ctags/universal-ctags` . Do i need config universal-ctags or change font etc. ?

**Comment by liuchengxu** [comment]
The minimal vimrc and steps to reproduce.

**Comment by liuchengxu** [comment]
What's more, please read this section https://github.com/liuchengxu/vista.vim#compile-ctags-with-json-format-support .

```
brew install --with-jansson universal-ctags/universal-ctags/universal-ctags
```

**Comment by MrZhang123** [comment]
@liuchengxu I run `brew install --with-jansson universal-ctags/universal-ctags/universal-ctags` and  show the right , but icons not show , i think this maybe need change font to show ? maybe i need disable icons ... , anyway , thanks 😄
