### ISSUE TITLE
Popup window closes itself

### ISSUE THREAD

**Issue by crmtestresco** [liuchengxu/vista.vim#149]
**Describe the bug**
Popup window with preview of surroundings of selected method (Typescript code) closes itself without performing any action/movement after cca 1s.
This behavior does not manifest itself on e.g. variables.

Possible hints:

 - commenting out line in popup.vim [    autocmd CursorMoved <buffer> call s:ClosePopup()](https://github.com/liuchengxu/vista.vim/blob/b550b4ae6d91ac61f2ad41a484e0242da587e990/autoload/vista/popup.vim#L77) stops this behavior (however after that no new popup is opened anymore)
 - looks like playing with settings `g:vista_cursor_delay` and `g:vista_floating_delay` it is possible to use values that stop this behavior. In my case e.g.:
```
let g:vista_cursor_delay = 1000
let g:vista_floating_delay = 100
```
However the plugin is unusable with these settings.

**Environment:**
- OS: Ubuntu 18.04 WSL on Windows 10
- Vim/Neovim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep  6 2019 12:34:57)
Included patches: 1-1991
- This plugin version: b550b4ae6d91ac61f2ad41a484e0242da587e990

**Vista info**

```
    Current FileType: vista_kind
Avaliable Executives: ['coc', 'ctags', 'ale']
    Global Variables:
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'vim_lsp']
    let g:vista#finders = ['fzf', 'skim']
    let g:vista#renderer#ctags = 'default'
    let g:vista#renderer#enable_icon = 1
    let g:vista#renderer#icons = {'subroutine': '羚', 'method': '', 'func': '', 'variables': '', 'namespace': '', 'field': '', 'interface': '', 'type': '', 'packages': '', 'property': '襁', 'implementation': '', 'default': '', 'augroup': 'פּ', 'macro': '', 'enumerator': '', 'const': '', 'macros': '', 'map': 'פּ', 'fields': '', 'functions': '', 'enum': '', 'function': '', 'target': '', 'typedef': '', 'variable': '', 'modules': '', 'constant': '', 'struct': '', 'types': '', 'module': '', 'typeParameter': '', 'package': '', 'class': '', 'member': '', 'var': '', 'union': '鬒'}
    let g:vista_blink = [0, 0]
    let g:vista_cursor_delay = 1000
    let g:vista_default_executive = 'coc'
    let g:vista_echo_cursor_strategy = 'floating_win'
    let g:vista_floating_delay = 100
    let g:vista_top_level_blink = [0, 0]
```

**Steps to reproduce given the above info**

1.  Open Vista window using `:Vista!!`
2. Move to method name using standard vim navigation keys `j,k`
3. Popup window with method preview shows
4. Popup window closes itself without any interaction after cca 1s

**Expected behavior**
Popup window stays open until the cursor is moved from the method.

**Actual behavior**
Popup window closes automatically without moving away from the method.

Thank you for creating this plugin.

**Comment by liuchengxu** [comment]
I can't reproduce your issue locally, but did find a bug in popup :(. Please provide a minimal vimrc if your problem persists.

**Comment by crmtestresco** [comment]
Hi,

this is minimum .vimrc I can reproduce the bug with:

```
let g:pathogen_disabled = ['FastFold' , 'ale' , 'argtextobj.vim' , 'fzf' , 'fzf.vim' , 'goyo.vim' , 'haskell-vim' , 'limelight.vim' , 'setcolors.vim' , 'ultisnips' , 'undotree' , 'vim-airline' , 'vim-colorschemes' , 'vim-commentary' , 'vim-easymotion' , 'vim-expand-region' , 'vim-fugitive' , 'vim-gutentags' , 'vim-livedown' , 'vim-qf' , 'vim-repeat' , 'vim-ripgrep' , 'vim-sensible' , 'vim-signjump' , 'vim-sleuth' , 'vim-snippets' , 'vim-stay' , 'vim-surround' , 'vim-textobj-function' , 'vim-textobj-function-javascript' , 'vim-textobj-user' , 'vim-unimpaired' , 'vim-wordmotion' , 'vim-workspace']

call pathogen#infect()

filetype plugin indent on

" Vista plugin configuration
let g:vista_default_executive = 'coc'
let g:vista_cursor_delay = 1
let g:vista_floating_delay = 1
let g:vista_echo_cursor_strategy = 'floating_win'
```

I also noticed that with this config:

 - the first popup (navigating on first item) does not close itself
 - all next popups now close a bit later, in cca 3s
 - there is a message in Vim command line "--No lines in buffer--" at the same time the popup closes

**Comment by liuchengxu** [comment]
I can reproduce with the following vimrc in vim and I believe it's an issue of coc.nvim. If you disable coc.nvim via `:CocDisable`, the symptom disappears. If you enable it again via `:CocEnable`, the issue occurs.

```vim
set nocompatible

let $DOTVIM = expand('$HOME/.vim')

set runtimepath+=$DOTVIM/plugged/vista.vim
set runtimepath+=$DOTVIM/plugged/coc.nvim

filetype plugin indent on

" Vista plugin configuration
let g:vista_default_executive = 'coc'
let g:vista_cursor_delay = 1
let g:vista_floating_delay = 1
let g:vista_echo_cursor_strategy = 'floating_win'
```

After some investigation,  I think this line is related https://github.com/neoclide/coc.nvim/tree/5380d3639671d1e11949a41daea735da7cf1f0c5/plugin/coc.vim#L208 . This `autocmd` leads to the unexpected close.
