### ISSUE TITLE
Adjustable vista outline window?

### ISSUE THREAD

**Issue by diwangislucky** [liuchengxu/vista.vim#155]
Hi,

I was wondering if it was possible to adjust the window layout of the outline window shown by this plugin.

**Comment by liuchengxu** [comment]
What do you mean by `adjustable`?

**Comment by diwangislucky** [comment]
Change the size of the window that spawns after running ':Vista'.

**Comment by liuchengxu** [comment]
`:h g:vista_sidebar_width`
