### ISSUE TITLE
Vista fails to open if NERDTree is already open.

### ISSUE THREAD

**Issue by GideonWolfe** [liuchengxu/vista.vim#156]
**Describe the bug**
 I bound F7 to open NERDtree (left) and F8 to `Vista!!` which by default goes to the right.
Open any file in neovim. Press `F8`, then `F7`. Both windows should open successfully.
Now close them both.
Pres `F7`, `F8`. Nerdtree opens correctly with `NERDTreeToggle`, but `Vista!!` fails to open a right side Vista window.

**Environment:**
- OS: 
- Vim/Neovim version: 
- This plugin version: 
`Linux archlinux 5.3.1-arch1-1-ARCH`
```
NVIM v0.5.0-15-g1070c092c
Build type: RelWithDebInfo
```
Not sure of the plugin version, but I installed yesterday with vim-plug

**Vista info**

```
   Current FileType: startify
Avaliable Executives: ['coc', 'ctags']
    Global Variables:
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'vim_lsp']
    let g:vista#finders = ['fzf', 'skim']
    let g:vista#renderer#enable_icon = 1
    let g:vista_icon_indent = ['╰─▸ ', '├─▸ ']

```
**Expected behavior**
I expect both buffers to open regardless of the order I open them

**Actual behavior**
`Vista!!` fails to open Vista if NERDTree is already open.

On an unrelated note, I have these icon indent symbols defined in my settings but I have yet to see them in Vista. I was looking at some complex code with a couple indent levels and I never saw the symbols

**Comment by liuchengxu** [comment]
You can't run `Vista!!` when you are still in the nerdtree window as nerdtree buffer has no tags or symbols. You have to go back to the previous window when you press `F7`, and then `F8`.

**Comment by GideonWolfe** [comment]
This makes sense. Do you have any advice on enabling the arrow indent icons? I enabled icons, and I can see them for functions, maps, etc. Just no folder arrows. I can see them in my terminal when I paste them into my init.vim though

**Comment by liuchengxu** [comment]
Please file another issue, better with a minimal vimrc, i don't quite understand the folder arrows.
