### ISSUE TITLE
Arrows do not appear on vista window

### ISSUE THREAD

**Issue by GideonWolfe** [liuchengxu/vista.vim#157]
**Describe the bug**
I expect to see indent arrows like in the screenshot, but instead I see nothing

**Environment:**
```
NVIM v0.5.0-15-g1070c092c
Build type: RelWithDebInfo
```

**Vista info**

```
"""""""""""
" Vista  "
"""""""""""
nmap <F8> :Vista!!<CR>
let g:vista_icon_indent = ["╰─▸ ", "├─▸ "]
let g:vista#renderer#enable_icon = 1
let g:vista_sidebar_width = 50
```

```
    Current FileType: c                                                                        
Avaliable Executives: ['coc', 'ctags']
    Global Variables:
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'vim_lsp']
    let g:vista#finders = ['fzf', 'skim']
    let g:vista#renderer#enable_icon = 1
    let g:vista_icon_indent = ['╰─▸ ', '├─▸ ']
    let g:vista_sidebar_width = 50
```

**Steps to reproduce given the above info**

1. Open file
2. Open Vista
3. Notice lack of arrows

**Expected behavior**
Look like the screenshot on README

**Actual behavior**
No indentation arrows

**Screenshot or gif** (if possible)

**Comment by GideonWolfe** [comment]
Running `Vista coc` instead of `Vista!!` solved 2 issues. 

I can see arrows, better icons, and now I have tags for C code that weren't showing up before. Still all variables show up under `UNKNOWN`. Is there some setup step for C that i'm missing? I have `coc-ccls` installed.

I tried setting my `let g:vista_default_executive = 'coc'`, but when I do my keybind to open `Vista` with `Vista!!`, no window opens if I'm not in a C file. If I am in a C file, I can toggle the window on and off with `Vista!!` one time before it stops working.

adding
```
let g:vista_executive_for = {
      \ 'c': 'coc',
      \ }
```
seemed to fix the issue of the window not opening in most files. But still I don't see the same UI as if I used the coc executive.

**Comment by liuchengxu** [comment]
I have updated the doc. `g:vista_icon_indent` doesn't work for `:Vista ctags`, only for `:Vista coc/ale/lcn/vim_lsp`, for `:Vista ctags` supports tree view, but the LSP executives doesn't yet(this point is already present in the README).

**Comment by GideonWolfe** [comment]
Alright, I can live without indent arrows for Ctags. More important is the issue where I cannot retoggle `Vista` After I have opened and closed it (only in C files)

**Comment by liuchengxu** [comment]
Well, I don't know what's going on. Please create a new issue with minimal vimrc and steps to reproduce.
