### ISSUE TITLE
Hide selected types

### ISSUE THREAD

**Issue by radmen** [liuchengxu/vista.vim#158]
Hey,

I love the way how Vista performs, yet I have one problem. I'm currently working on a project with large files that contain multiple functions etc. When opening Vista  (mostly in `finder` mode) it tries to filter not only through methods/functions but also all of the declared variables. 

This forces me to use the finder in a similar way as I was using FZF prior to installing the extension.

First I need to type the name of the function/method (or part of it) and then append keyword "method/function" so that the results are narrowed to those particular types.

**Describe the solution you'd like**
A config variable declaring what kind of types I'd like to see in the Vista window.

**Describe alternatives you've considered**

Alternatively I'd like to set a variable which defines which types should be hidden :)

**Comment by liuchengxu** [comment]
Use `g:vista_ignore_kinds = ['method']` to ignore the symbols whose kind is method.

**Comment by radmen** [comment]
Thank you! :heart:
