### ISSUE TITLE
vista crashes on opening latex files

### ISSUE THREAD

**Issue by cridemichel** [liuchengxu/vista.vim#161]
**Describe the bug**

open the following latex file:

[prova.tex.gz](https://github.com/liuchengxu/vista.vim/files/3725360/prova.tex.gz)

using the following minimal .vimrc file:
[vimrc_minimal_vista.gz](https://github.com/liuchengxu/vista.vim/files/3725365/vimrc_minimal_vista.gz)

open vista issuing the command
:Vista

vista crashes spawaning a lot messsages I was not able to read

**Environment:**
- OS: Mojave 10.14.6
- Vim/Neovim version: 
```text
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 30 2019 02:59:45)
macOS version
Included patches: 1-2100
Compiled by Homebrew
```
- This plugin version: 
a1422dc7157fa60ab104a70d3b528c6cf9dfe2a0

```text
ctags works correctly on prova.tex file
```
**Vista info**

```vim 
Current FileType:
Avaliable Executives: ['ctags']
    Global Variables:
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'vim_lsp']
    let g:vista#finders = ['fzf', 'skim']
    let g:vista#renderer#enable_icon = 1
    let g:vista#renderer#icons = {'label': ' ', 'subsection': ' ', 'section': ' ', 'subsubsection': ' '}
```

**Steps to reproduce given the above info**

1.
2.
3.
4.

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshot or gif** (if possible)

**Comment by cridemichel** [comment]
why did you close it?

**Comment by liuchengxu** [comment]
Update again, should be fixed.

**Comment by cridemichel** [comment]
it seems so, thank you very much!

Cristiano De Michele
cristiano.demichele@gmail.com

**Comment by cridemichel** [comment]
now when I jump to tag I get sometime this error:

Error detected while processing function vista#cursor#FoldOrJump[16]..vista#jump#TagLine:
line   15:

Press ENTER or type command to continue


Cristiano De Michele
cristiano.demichele@gmail.com

**Comment by liuchengxu** [comment]
Create a new issue.

**Comment by cridemichel** [comment]
…but you can reproduce it using the same prova.tex I guess,
moreover highlight of current tag is not working in latex (in C/C++ it works)

Cristiano De Michele
cristiano.demichele@gmail.com

**Comment by cridemichel** [comment]
you can reproduce the following error

```text
Error detected while processing function vista#cursor#FoldOrJump[16]..vista#jump#TagLine:
line   15:
```
by pressing <CR> on a white line in vista buffer…


Cristiano De Michele
cristiano.demichele@gmail.com
