### ISSUE TITLE
error when editing an empty buffer in new tab created from a window with vista open

### ISSUE THREAD

**Issue by frescoraja** [liuchengxu/vista.vim#164]
**Describe the bug**
When I open a new tab (`:tabnew` command) from a window that has a Vista buffer in it, i get the following error after each new character input:
```
Error detected while processing function <SNR>185_AutoUpdateWithDelay:
line    6:
E121: Undefined variable: t:vista
```

to reproduce:
1) edit a file in nvim
2) execute `:Vista` command to open vista tab
3) execute `:tabnew` command to open a new tab with an empty buffer
4) enter insert mode and start typing

**Environment:**
macOS mojave

NVIM v0.5.0-dev
Build type: Release

dd95a3870ff1d040460d27fdaba5ca73ec84b4bc

**Vista info**

```
    Current FileType: 
Avaliable Executives: ['coc', 'ctags']
    Global Variables:
    let g:vista#executive#ctags#support_json_format = 0
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'vim_lsp']
    let g:vista#finders = ['fzf', 'skim']
    let g:vista#renderer#ctags = 'default'
    let g:vista#renderer#default#vlnum_offset = 3
    let g:vista#renderer#enable_icon = 1
    let g:vista#renderer#icons = {'subroutine': '羚', 'method': '', 'func': '', 'variables': '', 'namespace': '', 'field': '', 'interface': '', 'type': '', 'packages': '', 'property': '襁', 'implementation': '', 'default': '', 'augroup': 'פּ', 'macro': '', 'enumerator': '', 'const': '', 'macros': '', 'map': 'פּ', 'fields': '', 'functions': '', 'enum': '', 'function': '', 'target': '', 'typedef': '', 'variable': '', 'modules': '', 'constant': '', 'struct': '', 'types': '', 'module': '', 'typeParameter': '', 'package': '', 'class': '', 'member': '', 'var': '', 'union': '鬒'}
    let g:vista_default_executive = 'ctags'
    let g:vista_echo_cursor_strategy = 'echo'
    let g:vista_executive_for = {'vim': 'ctags', 'go': 'coc', 'javascript': 'coc', 'javascript.jsx': 'coc'}
    let g:vista_icon_indent = ['╰─▸ ', '├─▸ ']
    let g:vista_sidebar_width = 50
    let g:vista_stay_on_open = 1
    let g:vista_update_on_text_changed = 1
```

**Steps to reproduce given the above info**
1) open a file to edit in nvim
2) execute `:Vista` command to open vista buffer
3) execute `:tabnew` command to open a new tab with an empty buffer
4) enter insert mode and start typing

**Expected behavior**
no errors

**Actual behavior**
errors

**Screenshot or gif** (if possible)
![Screen Shot 2019-10-17 at 1 49 35 PM](https://user-images.githubusercontent.com/1677274/67034076-04c97780-f0e5-11e9-90ac-c20fefcd600d.png)

**Comment by theniceboy** [comment]
still getting the same error @liuchengxu

**Comment by liuchengxu** [comment]
@theniceboy Pull the latest version and see if the error persists.

**Comment by frescoraja** [comment]
@liuchengxu 
thanks for the work. all fixed in latest version

**Comment by theniceboy** [comment]
All fixed! Thanks @liuchengxu
