### ISSUE TITLE
Use per-user tempfiles for ctags

### ISSUE THREAD

**Issue by toupeira** [liuchengxu/vista.vim#167]
**Describe the bug**

Vista creates a temporary directory in `/tmp/vista.vim_ctags_tmp`, owned and writable by the current user.

If you use Vim with multiple users, this causes errors.

**Environment:**
- OS: Linux, Debian sid
- Vim/Neovim version: NVIM v0.4.0-dev, Build type: RelWithDebInfo
- This plugin version: 72c85d2a1793378967a65ddba46d87e05ccebdc8

**Vista info**

```
    Current FileType: startify
Avaliable Executives: ['ctags', 'vim_lsp']
    Global Variables:
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'vim_lsp']
    let g:vista#finders = ['fzf', 'skim']
    let g:vista_blink = [1, 100]
    let g:vista_executive_for = {'typescript': 'vim_lsp', 'ruby': 'vim_lsp', 'javascript': 'vim_lsp'}
    let g:vista_fzf_preview = ['right:hidden:70%']
    let g:vista_icon_indent = ['● ', '▶ ']
    let g:vista_sidebar_width = 40
```

**Steps to reproduce given the above info**

1. `rm -rf /tmp/vista.vim_ctags_tmp`
1. Open a file as `root` and run `:Vista ctags`
1. Open a file as another user and run `:Vista ctags`

**Expected behavior**
No errors.

**Actual behavior**
An error:

```
E482: Can't open file /tmp/vista.vim_ctags_tmp/448280443da920c2cb6918e4b76731e06f42e1e98f58336bbfb48be3332a359a.vim for writing: permission denied 
```

**Possible solutions**

- The quick fix: Include the current user ID in the path.
- The elegant fix: Use a cache directory in the user's home directory. Neovim has `stdpath('cache')` for this, unfortunately Vim doesn't support it.

**Comment by liuchengxu** [comment]
How about using `~/.vista.tmp`?

**Comment by toupeira** [comment]
@liuchengxu that would work too, though it would be nice to avoid polluting `$HOME` :wink: For reference, `stdpath('cache')` in Neovim resolves to the XDG-standard location `~/.cache/nvim`.

I'd be happy to submit a PR for this. What do you think about:

- Using `stdpath('cache') . 'vista'` in Neovim
- Hard-coding `~/.cache/vista` in Vim, or maybe `~/.cache/vim/vista`

**Comment by liuchengxu** [comment]
That would also be nice. Feel free to open up a PR :(.

**Comment by dharrigan** [comment]
I'm hitting this too:

Latest vista and neovim.

If I'm root, then vista will write into the `/tmp/vista.vim_ctags_tmp/....` directory.

If this directory does not exist, it is created as the root user.

As a normal user, if I edit a file, vista will attempt to write into the `/tmp/vista.vim_ctags_tmp/.....` directory for storing ctag information. 

This gives the following error:

```
Error detected while processing function <SNR>75_do_vim_enter[3]..vista#RunForNearestMethodOrFunction[4]
..vista#executive#ctags#Execute[2]..<SNR>159_Dispatch[11]..<SNR>159_Execute[3]..<SNR>159_ApplyExecute[1]
..<SNR>159_BuildCmd[1]..<SNR>159_IntoTemp:                                                              
line   43:                                                                                              
E482: Can't open file /tmp/vista.vim_ctags_tmp/0112dea10100f4ebf90e29f2f98e37d1a9bbbfe5b6667ddee86e3bbcb
f034942.sh for writing: permission denied  
```

This means that I have to remove the `/tmp/vista.vim_ctags_tmp` directory first before opening up the file as a normal user.

I think the permissions on the directory are too restrictive, and need to be perhaps `777` when the `vista.vim_ctags_tmp` directory is created, or as @toupeira says, a better solution is to use the XDG location for temp files.

**Comment by liuchengxu** [comment]
Try the latest commit, if `$TMPDIR` does not exist, vista will use:

1. `stdpath('cache')/vista` for neovim
2. try using `$XDG_CACHE_HOME/vista`.
3. Or `$HOME/.cache/vista`.

**Comment by dharrigan** [comment]
Awesome! Thank you! :-)
