### ISSUE TITLE
not compatiable with coc-explorer

### ISSUE THREAD

**Issue by jidibinlin** [liuchengxu/vista.vim#169]
**Describe the bug**

**Environment:**
- OS: 
- Vim/Neovim version: 
- This plugin version: 

**Vista info**

```
```

**Steps to reproduce given the above info**

1.
2.
3.
4.

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshot or gif** (if possible)

**Comment by liuchengxu** [comment]
>Please understand, that without clear explanations and useful info
the issue may be closed as unreproducible.

**Comment by jidibinlin** [comment]
please pick a look at it. I think the information i supplied is sufficient

**Comment by liuchengxu** [comment]
Please provide a minimal vimrc.

**Comment by jidibinlin** [comment]
```
" vim-plug
call plug#begin('~/.vim/plugged')
	Plug 'jackguo380/vim-lsp-cxx-highlight'
	Plug 'neoclide/coc.nvim', {'branch': 'release'}
	Plug 'morhetz/gruvbox'
	Plug 'vim-airline/vim-airline'
	Plug 'vim-airline/vim-airline-themes'
	Plug 'liuchengxu/space-vim-theme'
	Plug 'mhinz/vim-startify'
	Plug 'Yggdroot/LeaderF', { 'do': './install.sh' }
	Plug 'weirongxu/coc-explorer', {'do': 'yarn install --frozen-lockfile'}
	Plug 'liuchengxu/vista.vim'
call plug#end()

" color themes
set background=dark
colorscheme space_vim_theme

" tabline
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1


" line number
set nu


" leaderf


" coc-explorer
nmap <F3> :CocCommand explorer<CR>

" vista
nmap <F4> :Vista!!<CR>

```

**Comment by jidibinlin** [comment]
Your "plugins" i very good!

**Comment by liuchengxu** [comment]
I don't see a problem with the following vimrc:

```vim
" vim-plug
call plug#begin('~/.vim/plugged')
    Plug 'neoclide/coc.nvim', {'branch': 'release'}
    Plug 'weirongxu/coc-explorer', {'do': 'yarn install --frozen-lockfile'}
    Plug 'liuchengxu/vista.vim'
call plug#end()

" coc-explorer
nmap <Leader>c :CocCommand explorer<CR>

" vista
nmap <Leader>v :Vista!!<CR>
```

**Comment by jidibinlin** [comment]
@liuchengxu you mean you can open files through coc-explorer when coc-explorer and vista were opened at the same time?

**Comment by jidibinlin** [comment]
![2019-10-31_17-05](https://user-images.githubusercontent.com/38578679/67933412-b053eb00-fc00-11e9-93bc-5d7f18c1f907.png)

**Comment by liuchengxu** [comment]
See the message at the bottom carefully.

> Please use the letter on the status to select the window, or use <ESC> to cancel

You should ask at coc-explorer for using it properly.

**Comment by jidibinlin** [comment]
??! I tried  to open file at coc-explorer and get this problem

**Comment by jidibinlin** [comment]
I`m sorry. My fault!

**Comment by jidibinlin** [comment]
Thank you!
