### ISSUE TITLE
python代码能否按照代码出现顺序来展示

### ISSUE THREAD

**Issue by JarodLi** [liuchengxu/vista.vim#173]
请问，python代码能否像tagbar一样按照代码顺序来展示层级关系。 
如：vista将类方法单独归类到“member”下，而 不是挂在类下面

![image](https://user-images.githubusercontent.com/3362590/68521243-1b28b480-02da-11ea-8263-96e4cbaf31cb.png)

tagbar可以将类展开，查看类方法
![image](https://user-images.githubusercontent.com/3362590/68521262-43181800-02da-11ea-9089-509340818f0a.png)

**Comment by liuchengxu** [comment]
`:Vista ctags`.

**Comment by JarodLi** [comment]
Vista ctags并不能解决这个问题

**Comment by liuchengxu** [comment]
>Please understand, that without clear explanations and useful info
the issue may be closed as unreproducible.
