### ISSUE TITLE
Vista resets fillchars

### ISSUE THREAD

**Issue by heroin-moose** [liuchengxu/vista.vim#174]
**Describe the bug**
Vista resets fillchars in all buffers. This means that vertical split chars are getting reset too.

**Steps to reproduce given the above info**
1. set fillchars to 'vert:|,fold:-'
2. Open Vista buffer
3. fillchars are now set to 'fold:' globally

**Expected behavior**
Vista should not modify vertical fillchars. The code in question is

```
+" Get rid of extra fold dashes when using Vim folding
+setlocal fillchars=fold:\ 
```

The change was introduced in commit 
3e89d2ce4ffa6a5775baf9bf4e5a1c38a06780b5.

**Comment by heroin-moose** [comment]
It's not helping, fillchars are still getting reset.

**Comment by liuchengxu** [comment]
I can't reproduce now. Please provide a minimal vimrc and steps to reproduce if that doesn't work fo you.

**Comment by heroin-moose** [comment]
Err... It's actually just and empty .vimrc and ~/.vim/pack/plugins/start/vista.vim with latest Git.

**Comment by liuchengxu** [comment]
If you are saying that `fillchars` are changed in the vista buffer only, that's expected. It will be restored when you leave the vista buffer. If you even don't want this behavior, use an autocmd to keep your own `autocmd FileType vista set fillchars=vert:\|,fold:-`.

**Comment by heroin-moose** [comment]
It's not, that's the point. You call :Vista, then close it, and nothing changes back.

**Comment by heroin-moose** [comment]
Also, do you use neovim? I belive there is a difference between vim and neovim on this, as vim does not have buffer-local fillchars. They are changed globally.

**Comment by liuchengxu** [comment]
I have removed the `fillchars` modification. Now it's up to you what the folded text in the vista buffer looks like.

**Comment by heroin-moose** [comment]
Created a feature request in VIM: https://github.com/vim/vim/issues/5206

**Comment by heroin-moose** [comment]
Also Vista changes global folding color -_-

**Comment by liuchengxu** [comment]
>Also Vista changes global folding color -_-

I don't understand.

**Comment by heroin-moose** [comment]
Before opening Vista buffer:
![before](https://user-images.githubusercontent.com/15263497/68542098-b3499b00-03b9-11ea-8f4a-367e38a047c9.png)

After opening Vista buffer:
![after](https://user-images.githubusercontent.com/15263497/68542100-b8a6e580-03b9-11ea-8981-bd0e1475b304.png)
