### ISSUE TITLE
Respect fzf_colors

### ISSUE THREAD

**Issue by sQVe** [liuchengxu/vista.vim#177]
What is the reasoning behind not respecting the `fzf_colors` setting? I'd like to have the same styling for everything using FZF, or atleast a way to customize `vista.vim` to have the same styling.

Related code: https://github.com/liuchengxu/vista.vim/blob/546f0d7715ef270c17d7540a438ddc6b806ff5b8/autoload/vista/finder/fzf.vim#L82-L92

**Comment by liuchengxu** [comment]
See the comment.

https://github.com/liuchengxu/vista.vim/blob/546f0d7715ef270c17d7540a438ddc6b806ff5b8/autoload/vista/finder/fzf.vim#L80-L81

The syntax highlight means:

https://github.com/liuchengxu/vista.vim/blob/546f0d7715ef270c17d7540a438ddc6b806ff5b8/autoload/vista/finder/fzf.vim#L126

You can try commenting the related lines to see if that works for you. If it does work, I can add an option to not touch `g:fzf_corlos` in vista.vim

**Comment by sQVe** [comment]
@liuchengxu Commenting it out solves the issue. It is now more consistent. It does seem like it doesnt use `['fg', 'Normal']` for the text by default though.

**Comment by liuchengxu** [comment]
I'm not sure it that's an issue of vista.vim

**Comment by sQVe** [comment]
@liuchengxu No, it's probably not. It would be awesome if you could provide an option to keey `fzf_colors` though.

**Comment by sQVe** [comment]
@liuchengxu Awesome. Thank you :pray:
