### ISSUE TITLE
Not updating for new buffers

### ISSUE THREAD

**Issue by sQVe** [liuchengxu/vista.vim#179]
**Describe the bug**
Vista does not update when opening a new buffer.

**Environment:**
- OS: Arch Linux - kernel 5.3.10-arch1-1
- Vim/Neovim version: `NVIM v0.4.3, Build type: Release`
- This plugin version: `8d74f32bebf4cb8a1ca15aa248ac77a17e00b352`

**Vista info**

```
    Current FileType:
Avaliable Executives: ['coc', 'ctags']
    Global Variables:
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'vim_lsc', 'vim_lsp']
    let g:vista#finders = ['fzf', 'skim']
    let g:vista_default_executive = 'coc'
    let g:vista_echo_cursor_strategy = 'floating_win'
    let g:vista_executive_for = {'markdown': 'toc'}
    let g:vista_fzf_preview = ['down:50%']
    let g:vista_sidebar_width = 50
```

**Steps to reproduce given the above info**

1. Open a buffer.
2. Execute :Vista!!
3. Open new buffer.

**Expected behavior**
Vista should update when openinga new buffer.

**Actual behavior**
Vista does not update when opening a new buffer.

**Screenshot or gif** (if possible)
https://asciinema.org/a/280740

**Comment by liuchengxu** [comment]
Can't reproduce. Please provide a minimal vimrc and steps to reproduce.

**Comment by sQVe** [comment]
I can reproduce this with simply `coc.nvim` and `vista.vim` installed and running `:Vista coc`.

**Comment by liuchengxu** [comment]
coc.nvim is a complicated plugin, you have to tell the minimal configurations and steps to help reproduce. Vista already triggers the auto-update when neccessary, see https://github.com/liuchengxu/vista.vim/blob/3e88fd361d09017f4db05ff1213e6fe3a12ede3e/autoload/vista/autocmd.vim#L78-L99

**Comment by sQVe** [comment]
Minimal vimrc:
```vim
set nocompatible

set runtimepath+=~/.local/share/nvim/plugged/coc.nvim
set runtimepath+=~/.local/share/nvim/plugged/vista.vim
```

Steps to reproduce:
  - `nvim -u minimal.vimrc`
  - `:CocInstall coc-tsserver`
  - Open a `js` file
  - `:Vista coc`
  - `Open a different `js` file

**Comment by sQVe** [comment]
@liuchengxu Sadly the fix, https://github.com/liuchengxu/vista.vim/commit/30a9a4679c920b81535e4996dd2de817c6aca053, seems quite unstable. It only works sometimes. When opening largish files it does not update.

**Comment by liuchengxu** [comment]
Actually vista.vim can't help much as it's essentially not an issue of vista.vim. The success of the auto update depends on how fast your language server returns the requested symbols. Vista.vim will send an async request via coc.nvim when the related event is triggered. However, if this request returns no symbols, then vista.vim has nothing to do and the auto update fails. You could increase `30` to a larger number, which is helpful but not the fundamental solution.
