### ISSUE TITLE
Support vimwiki markdown

### ISSUE THREAD

**Issue by edubxb** [liuchengxu/vista.vim#180]
As vimwiki can use Markdown as syntax, would be nice to support it in Vista.

I tried setting the parameter:

`let g:vista_vimwik_executive = 'toc'`

with no luck 😢.

Thanks!

**Comment by liuchengxu** [comment]
It's unsupported. See #141 if you would like to add vimwiki extension, it should not be hard to extend based on the current markdown extension. You could also try `:call vista#extension#markdown#Execute(v:false, v:true)` directly to see if the markdown extension works with vimwiki.

**Comment by ranebrown** [comment]
Vimwiki supports standard markdown syntax which works with the existing markdown extension. Would it be possible to add a list of filetypes that map to markdown and use the existing executive?

This [patch.txt](https://github.com/liuchengxu/vista.vim/files/3991041/patch.txt) seems to work ok but isn't the best option.

**Comment by liuchengxu** [comment]
@ranebrown Thanks for the info. Now vista.vim supports using markdown extension for vimwiki if you set `let g:vista_vimwiki_executive = 'markdown'`. Let me know if that does not work as expected.

**Comment by ranebrown** [comment]
Thanks! Seems to work so far. I'll let you know if I run into any issues.

**Comment by ranebrown** [comment]
@liuchengxu Looks `Vista toc` isn't available for a vimwiki file. Using just `Vista` with `let g:vista_executive_for = {'vimwiki': 'toc', }` opens the markdown toc initially but if you don't select a header and switch back to you main window (`C-w h`) then it switches to the ctag version. Any ideas?

**Comment by liuchengxu** [comment]
@ranebrown  Please pull the lastet commit to see if it helps. And you should use `g:vista_executive_for = {'vimwiki': 'markdown' }`, that means to use the markdown extension for the vimwiki filetype. Using `{'vimwiki': 'toc'}` will try to find `autoload/extension/vimwiki` extension instead.
