### ISSUE TITLE
Make NeoVim's native LSP support available

### ISSUE THREAD

**Issue by weilbith** [liuchengxu/vista.vim#183]
Hey, 👋 
First, thanks for this great plugin!
I would like to ask if besides the integration of all the plugins which support LSP, also the recently merged native LSP support by NeoVim itself could be used? That would be freaking awesome! 🙃

**Comment by liuchengxu** [comment]
I'm not sure I'll use the builtin LSP support of neovim, so I may not add this support myself.

**Comment by h-michael** [comment]
Since the official release is v0.5, I/F may still change until then, so I think it's better to wait a bit longer to support.

**Comment by weilbith** [comment]
Okay, too bad. But no downgrade. I'll first switch from jaguar to this plugin and then I can wait for this feature.

Do you want this issue remain open with a special tag or...?

**Comment by weilbith** [comment]
Hmm okay. So maybe I'll first switch from tagbar to this plugin and then start to implement it on my own in a fork. 🤔 

Should we keep this issue open with some additional tag or..?

**Comment by liuchengxu** [comment]
Resolved by @pwntester in #202 🎉  .
