### ISSUE TITLE
FZF Finder with Coc not working - Dictonary Required 

### ISSUE THREAD

**Issue by jlangston** [liuchengxu/vista.vim#188]
**Describe the bug**
Hi, First off great work with Vista.vim excellent plugin and very useful. I ran info some unexpected behavior that seems to have started with the commit 44ad0da. From then on when I go to run the fzf finder popup on that commit I was getting an error about an undefined `s:data` expression. Now on the latest commit I get an error about a Dictionary being required. j
```Error detected while processing function vista#[33]..vista#finder#Dispatch[7]..vista#finder#fzf#Run[5]..vista#finder#GetSymbols[17]..<SNR>257_IsU
sable:
line    1:
E715: Dictionary required
Error detected while processing function vista#[33]..vista#finder#Dispatch[7]..vista#finder#fzf#Run:
line    5:
E714: List required
```

**Environment:**
- OS: Manjaro
- Vim/Neovim version: v0.4.3
- This plugin version: 60af582d617f7136e36d18e861b3abbb4ee888d

**Vista info**
```
    Current FileType: ruby
Avaliable Executives: ['coc', 'ale']
    Global Variables:
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'vim_lsc', 'vim_lsp']
    let g:vista#finders = ['fzf', 'skim']
    let g:vista_default_executive = 'coc'
```

**Steps to reproduce given the above info**

1.Run `Vista finder` setup with Coc-list and fzf
2.
3.
4.

**Expected behavior**
FZF finder window appears with buffer symbols

**Actual behavior**
Error message above

**Comment by liuchengxu** [comment]
See if #189 helps.

**Comment by jlangston** [comment]
It is working again in that branch.

**Comment by liuchengxu** [comment]
Thanks for confirming. The patch has been merged to master now.
