### ISSUE TITLE
Show TOC for markdown file

### ISSUE THREAD

**Issue by luzhlon** [liuchengxu/vista.vim#19]
If it can show TOC for markdown file in vista's right windows, that is awesome.

**Comment by liuchengxu** [comment]
Is [tagbar-markdown](https://github.com/lvht/tagbar-markdown) what you want? vista.vim could also do the job, but this feature possibly depends on #4 and may also need some additional parsing work at the first glance. I don't know when #4 will be resolved as I don't have to a great motivation to push it at this moment.

**Comment by liuchengxu** [comment]
Just realized that [vim-markdown](https://github.com/plasticboy/vim-markdown) has a command `:Toc`, and also [markdown-drawer](https://github.com/Scuilion/markdown-drawer). So it may be easier than I expected.

**Comment by luzhlon** [comment]
Yes, [tarbar-markdown](https://github.com/lvht/tagbar-markdown) is exactly what i want. But i think vista's UI is more **beautiful**, and vista is more **faster**. 👍 👍 👍

**Comment by liuchengxu** [comment]
@luzhlon Try [this branch](https://github.com/liuchengxu/vista.vim/tree/add-markdown-extension):

<img width="1680" alt="屏幕快照 2019-04-05 下午9 30 39" src="https://user-images.githubusercontent.com/8850248/55631378-73e71a80-57ea-11e9-9784-5d5232e0a111.png">

It's a rough implementation, it is not optimal to show toc in such a way in my opinion, the ideal way is at least to link the highlight of headers to the markdown syntax, e.g., `markdownH1`, but I'll leave it for now, hoping someone else could pick it up.

**Comment by luzhlon** [comment]
谢了大佬，我觉得这已经很不错了。我先试试，如果需要的话，我可以写个外部的解析器。
