### ISSUE TITLE
Really slow when open Vista in a large C++ file

### ISSUE THREAD

**Issue by linjiX** [liuchengxu/vista.vim#190]
**Describe the bug**
In a large C++ file, (For example: [mat.hpp](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/mat.hpp) About 3700 lines)

Vim will get stuck for a long time when open Vista.

**Environment:**
- OS: macOS
- Vim/Neovim version: NVIM v0.4.3 Build type: Release
- This plugin version: 6e91f8a786a9a4b957cae0a1eb5c32855ca7c37b

**Vista info**
```
    Current FileType: cpp
Avaliable Executives: ['ctags']
    Global Variables:
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'vim_lsc', 'vim_lsp']
    let g:vista#finders = ['fzf', 'skim']
```

**Steps to reproduce given the above info**

1. Open  [mat.hpp](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/mat.hpp) by neovim
2. `:Vista`

**Expected and Actual behavior**
Expect to take less time to open Vista,
As a reference, in my machine: (Intel i5-7360U (4) @ 2.30GHz)
Tagbar will stuck my machine about 1-2 seconds in [mat.hpp](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/mat.hpp)
But Vista will stuck about 7-8 seconds.

**Comment by liuchengxu** [comment]
Related to #20 and #184 . The culprit is `s:RenderDescendants` used for the tree view. It's a known design flaw and may not be resolved soon.

```
count  total (s)   self (s)  function
   36  16.366371   9.350819  <SNR>41_RenderDescendants()
 1094   8.312263   5.947254  <SNR>41_DescendantsOf()
```
