### ISSUE TITLE
Jump to tag moves cursor to the begining of the line

### ISSUE THREAD

**Issue by kawing-chiu** [liuchengxu/vista.vim#191]
**Describe the bug**
Before a tag is highlighted in the Vista window, jump to the tag will move the cursor to the begining of the line containing the tag, instead of to the tag.

**Environment:**
- OS: Arch linux
- Vim/Neovim version: NVIM v0.4.3   Build type: Release
- This plugin version: master

**Vista info**
```
    Current FileType: python                                                                                                     
Avaliable Executives: ['ctags', 'lcn']
    Global Variables:
    let g:vista#executive#ctags#support_json_format = 1
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'vim_lsc', 'vim_lsp']
    let g:vista#finders = ['fzf', 'skim']
    let g:vista#renderer#ctags = 'default'
    let g:vista#renderer#default#vlnum_offset = 3
    let g:vista#renderer#enable_icon = 0
    let g:vista#renderer#kind_default_icon = ['╰─▸ ', '├─▸ ']
    let g:vista_blink = [1, 100]
    let g:vista_cursor_delay = 2000
    let g:vista_echo_cursor_strategy = 'floating_win'
    let g:vista_fold_toggle_icons = ['▼', '▶']
    let g:vista_sidebar_width = 40
    let g:vista_top_level_blink = [1, 100]
```

**Steps to reproduce given the above info**
1. Set `g:vista_cursor_delay` to a large value, for example `let g:vista_cursor_delay = 3000`. This will make the bug obvious.
2. Open Vista.
3. Move cursor to Vista's window. Select any tag other than the current tag, then press <Enter> to jump to that tag.

**Expected behavior**
After the jump, cursor should be at the begining of the tag.

**Actual behavior**
After the jump, cursor moved to the begining of the **line**, not the tag.

**Comment by liuchengxu** [comment]
The tag extraction is not 100% reliable, so the strategy is to jump to the beginning when the tag is not found. If you want to improve it, see `vista#jump#TagLine()`.

**Comment by kawing-chiu** [comment]
However, after `g:vista_cursor_delay`, the jump is correct. So it seems that it's a bug because Vista already has enough information.

**Comment by liuchengxu** [comment]
Feel tree to open up a PR then. It's not a critical problem for me.

**Comment by kawing-chiu** [comment]
@liuchengxu Hi, PR created.
