### ISSUE TITLE
Error when at opening vista(:vista) with default executive (ctags)

### ISSUE THREAD

**Issue by tradjincal** [liuchengxu/vista.vim#193]
**Describe the bug**
I installed vista.vim and ran :Vista, then:

```
E118: Too many arguments for function: ch_status
E15: Invalid expression: ch_status(a:channel, {'part': 'out'}) ==# 'buffered'
```

**Environment:**
- OS: <Red Hat 6
- Vim version: 
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  8 2016 15:55:42)
Included patches: 1-2
```
- This plugin version: 923a074e6daa3d90de25d77856d3ccc24c8487ca

- Ctags version: f17ca7731a235b6950b8f02133ec1ff2656bddc7
Compiled as this:
```
./configure --prefix=${HOME}/.local --enable-json --enable-yaml
make
make install
```

**Vista info**

```
    Current FileType: vim
Avaliable Executives: ['ctags']
    Global Variables:
    let g:vista#executive#ctags#support_json_format = 1
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'vim_lsc', 'vim_lsp']
    let g:vista#finders = ['fzf', 'skim']
```

**Steps to reproduce given the above info**

1. execute `:Vista`
2.
3.
4.

**Expected behavior**
I expecte the Vista panel open.

**Actual behavior**
The error describe below is display 

Any idea of what happen?
Thanks in advance.

**Comment by liuchengxu** [comment]
Try upgrading your vim. See https://github.com/rhysd/vim-grammarous/issues/33. The one goal of vista is to embrace the LSP functionality, that also means you have to use the newer vim/neovim for the full feature set obviously.

**Comment by tradjincal** [comment]
I upgrade vim and it is working perfectly now. Thanks for the support.
