### ISSUE TITLE
b:vista_nearest_method_or_function is buggy

### ISSUE THREAD

**Issue by Avi-D-coder** [liuchengxu/vista.vim#205]
`b:vista_nearest_method_or_function` is unset until I run `:Vista`  and then `:bd` in the vista buffer.

**Comment by liuchengxu** [comment]
Please provide the detailed bug report, otherwise no one can help.

**Comment by Avi-D-coder** [comment]
This will reproduce it on neovim
![ezgif-4-3bf79630ab2b](https://user-images.githubusercontent.com/29133776/70212404-36ce8180-1705-11ea-95ea-2cae59320252.gif)
```vim
call plug#begin()
Plug 'liuchengxu/vista.vim'
call plug#end()
function! NearestMethodOrFunction() abort
  return get(b:, 'vista_nearest_method_or_function', '')
endfunction
```

**Comment by liuchengxu** [comment]
>" By default vista.vim never run if you don't call it explicitly.
>"
>" If you want to show the nearest function in your statusline automatically,
>" you can add the following line to your vimrc 
>autocmd VimEnter * call vista#RunForNearestMethodOrFunction()

https://github.com/liuchengxu/vista.vim#show-the-nearest-methodfunction-in-the-statusline

**Comment by Avi-D-coder** [comment]
My bad, airline does not do this.

**Comment by liuchengxu** [comment]
Your PR time for airline then :(.

**Comment by Avi-D-coder** [comment]
All done

**Comment by oblitum** [comment]
This stopped working for me lately.

**Comment by oblitum** [comment]
False alarm, looks like it's working after update now.
