### ISSUE TITLE
wildcard match for vista#render#icons table

### ISSUE THREAD

**Issue by fourjay** [liuchengxu/vista.vim#206]
**Is your feature request related to a problem? Please describe.**

Inconsistent icon mapping for differing tags
"functions" is mapped, but "function" is not.
DIfferent filetypes have differing type tags, running ``ctags --list-kinds | grep fun | sort | uniq -c`` shows most language definitions provide plural, but significant variation, one "function" one "A function" another "function definition" and 9 "function definitions"

**Describe the solution you'd like**
wildcard mapping, such as "func*" to icon.

**Describe alternatives you've considered**
1) A default mapping (this seems like a good idea anyways)
2) mapping only off of short letter tag.

**Comment by liuchengxu** [comment]
There are some edge cases for the wildcard match, e.g., `type` and `typedef`, I believe they should use different icons? Anyway you can use `g:vista#renderer#icons` to extend the default icon mappings. Feel free to open up a PR if there is better way, currently the icon is plainly picked from the `g:vista#renderer#icons` by the key, see https://github.com/liuchengxu/vista.vim/blob/master/autoload/vista/renderer.vim#L55-L61.
