### ISSUE TITLE
clap tags not working - Undefined variable: s:data

### ISSUE THREAD

**Issue by learner-beep** [liuchengxu/vista.vim#208]
_Instructions: 1. Install vim-clap and vista.vim 2.Execute :Clap tags OR :Clap tags ++e=fzf - Both result in the error and no popup comes. (FYI - remaining all :Clap commands works fine)

Error detected while processing function clap#[27]..clap#for[23]..clap#popup#open[13]..clap#_init[10]..652[11]..vista#finder#GetSymbols[26]..vista#executive#ctags#Run[1]..<SNR>293_Dispatch[11]..<SNR>293_Run:
line   11:
E121: Undefined variable: s:data
Error detected while processing function clap#[27]..clap#for[23]..clap#popup#open[13]..clap#_init[10]..652:
line   11:
E714: List required
Press ENTER or type command to continue
Error detected while processing function <SNR>286_popup_filter[21]..640:
line    1:
E121: Undefined variable: s:display_winid
Press ENTER or type command to continue
Error detected while processing function <SNR>286_popup_filter[21]..640:
line    1:
E116: Invalid arguments for function popup_getpos(s:display_winid)
Press ENTER or type command to continue

**Environment (please complete the following information):**
OS: Centos 7
Vim version: 8.1-2410
vim-clap version: Dec 15 commit - a2ee49ec87197dd90c4924563e6c476c8448e798
Have you reproduced with a minimal vimrc: yes

**Comment by liuchengxu** [comment]
It's more like a vista issue, so I tranferred it to this repo.

Can you also provide the sample file your error occured to reproduce?

**Comment by learner-beep** [comment]
1a. I just go to any directory and do 'vi'. Do not  input the file name. Get the same error
1b. Even If I give a file name passed like 'vi a.py' or 'vi a.java' or 'vi a.rb' or 'vi a.scala' or 'vi react.js' or 'vi jenkins' etc ,few more file extensions in different directories tried same problem
I think, It is not specific to a file or directory . 

2. .vimrc has the above minimal config ( the 5 lines)

3a. Also I tried in a directory with tags(manually running 'ctags -R .' in the directory) and later use vi to open , same problem. _But fzf.vim(another) plugin's tags :Tags works fine_
In case ,if there is a way to get fzf.vim :Tags in the popup window , that would also be great !
3b. Tried in a directory without tags generated by opening vi, same problem

If there is any verbose flag to enable logging or any otherway to troubleshoot, please let me know

**Comment by liuchengxu** [comment]
What you have descirbed does not help reproduce this issue. vista.vim does not need tha TAGS files as all is in memeory.

Try pasting the output of `:Vista info` when you see this error.

**Comment by learner-beep** [comment]
:Vista info  , gives below output

 Current FileType: python
Avaliable Executives: ['coc', 'ctags']
    Global Variables:
    let g:vista#executive#ctags#support_json_format = 0
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'nvim_lsp', 'tags', 'vim_lsc', 'vim_lsp']
    let g:vista#finders = ['fzf', 'skim']
    let g:vista#renderer#enable_icon = 1
    let g:vista#renderer#icons = {'function': '', 'variable': ''}
    let g:vista_ctags_cmd = {'haskell': 'hasktags -x -o - -c'}
    let g:vista_default_executive = 'ctags'
    let g:vista_executive_for = {'php': 'vim_lsp', 'cpp': 'vim_lsp'}
    let g:vista_fzf_preview = ['right:50%']
    let g:vista_icon_indent = ['╰─▸ ', '├─▸ ']

**Comment by liuchengxu** [comment]
Not sure if you are using the right ctags, note that only https://github.com/universal-ctags/ctags is supported. What does `ctags --version` say?

**Comment by learner-beep** [comment]
Amazing ! 
BTW its a very nice plugin you have developed. Congrats ! 
Thank you !

I was using wrong one(below - exuberant ). After installing universal, it works fine. 

Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: May  1 2014, 03:27:17
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex

**Comment by learner-beep** [comment]
One doubt : 

Can the below file types be supported ? 
maybe its ctags limitation, but if there is a workaround to support below , it would be great !

html 
yaml (although it works for json) 
ts
shell script
groovy,scala
