### ISSUE TITLE
Special symbols missing?

### ISSUE THREAD

**Issue by wullxz** [liuchengxu/vista.vim#209]
I installed vista.vim and made sure that the powerline fonts are available: 
`sudo apt install fonts-powerline`

I restarted my terminal and X server and can see in my vim-airline bar, that special symbols (the arrows, "Line Number"-Symbol, Git Branch symbol) are now available. 
To test what's wrong, I assigned the unicode value 0192 to be displayed for functions, which works:
```
let g:vista#renderer#icons = {
\   "function": "\u0192",
\   "variable": "\uf71b",
\  }
```
![vista vim](https://user-images.githubusercontent.com/813777/70873064-124b9280-1fac-11ea-9f64-f068801f3b26.png)

But still, as you can see, the other symbols aren't displayed. 
What font (or patch) do I need to show the default symbols?

Environment:
Editor: Vim 8.0
OS: Ubuntu 18.04 on Windows (WSL)

**Comment by liuchengxu** [comment]
I believe some symbols are only avaliable in nerd fonts, and not all powerline fonts behave the same. I personally use these fonts: https://github.com/liuchengxu/space-vim/wiki/tips#programming-fonts. If you don't have the proper font installed, just disable the icon in vista.vim via `let g:vista#renderer#enable_icon = 0`.

**Comment by wullxz** [comment]
Thanks @liuchengxu !
I got "Sauce Code Pro" in semi bold from [here](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/SourceCodePro/Semibold/complete) and installed it like this:
```
mkdir -p ~/.fonts/nerd-fonts/
cd ~/.fonts/nerd-fonts/
curl https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/SourceCodePro/Semibold/complete/Sauce%20Code%20Pro%20Semibold%20Nerd%20Font%20Complete%20Mono.ttf?raw=true -o SauceCodePro.ttf
fc-cache -fv SauceCodePro.ttf
# check if it's there and what name it has:
fc-list | grep -i code
```

I added it to vim using this command in my .vimrc:
```
set guifont=SauceCodePro\ Nerd\ Font\ Mono
```

**Comment by laoshaw** [comment]
> I believe some symbols are only avaliable in nerd fonts, and not all powerline fonts behave the same. I personally use these fonts: https://github.com/liuchengxu/space-vim/wiki/tips#programming-fonts. If you don't have the proper font installed, just disable the icon in vista.vim via `let g:vista#renderer#enable_icon = 0`.

all the icons on my ubuntu 20.04 gnome-terminal are messed up until I set  `let g:vista#renderer#enable_icon = 0` and also disable icons.
