### ISSUE TITLE
Error detected while processing function <SNR>139_on_exit[6]..<SNR>139_ExtractLinewise[2]..vista#parser#ctags#FromExtendedRaw[28]..<SNR>151_LoadData: line   2: E716: Key not present in Dictionary: line, 'text': line.name }

### ISSUE THREAD

**Issue by cstsunfu** [liuchengxu/vista.vim#213]
I have gotten the slightly different bug as Issue 207 reported。

```Error detected while processing function <SNR>30_on_exit[6]..<SNR>30_ApplyExtracted[8]..vista#sidebar#Reload[14]..vista#viewer#Render[1]..<SNR>
34_Render[2]..vista#renderer#default#Render[5]..<SNR>36_Render[64]..<SNR>36_RenderScopeless[5]..vista#renderer#Decorate:
line    2:
E716: Key not present in Dictionary: default).'  '.a:kind
```

You can reproduce the bug by:

1. fitting the configure to your init.vim
2. opening the init.vim by neovim
3. rewriting the init.vim by the command :w 
4. getting the error...

```set runtimepath^=~/.vim runtimepath+=~/.vim/after
autocmd BufWritePost $MYVIMRC source $MYVIMRC
autocmd VimEnter * exe "Vista"
call plug#begin('~/.vim/plugged')
    Plug 'liuchengxu/vista.vim'
        let g:vista_stay_on_open=0
        let g:vista#renderer#icons = {
        \   "function": "\uf794",
        \   "variable": "\uf005",
        \   "variables": "\uf005",
        \   "maps": "\uf279",
        \   "members": "\ufa85",
        \   "classes": "\ue61e",
        \   "autocommand groups": "\uf7c2",
        \  }
call plug#end()
```

感谢你对vim社区的贡献

**Comment by cstsunfu** [comment]
Sorry, the bug seems not been fixed.

**Comment by liuchengxu** [comment]
What does `:echo g:vista#renderer#icons` say when you see the error?

**Comment by cstsunfu** [comment]
@liuchengxu 

When I type the `echo g:vista#renderer#icons` output  is:
`{'autocommand groups': '', 'function': '', 'variables': '', 'classes': '', 'variable': '', 'members': '徭', 'maps': ''}`
I have used the vim-devicons and nerd-fonts.
<img width="1289" alt="Screen Shot 2019-12-27 at 2 20 29 PM" src="https://user-images.githubusercontent.com/24812659/71504504-a3780e80-28b4-11ea-8705-26e4488d7f98.png">

**Comment by liuchengxu** [comment]
Should be fixed now, it's reset by your VIMRC source hook.

**Comment by cstsunfu** [comment]
Yes, it works. Thanks.
