### ISSUE TITLE
Howto eliminate flicker?

### ISSUE THREAD

**Issue by tmpm697** [liuchengxu/vista.vim#216]
**Describe the bug**
Vim uses lazydrawn to renew screen somehow that cause flick.

**Environment:**
- OS: archlinux
- Vim version: latest git
- This plugin version: latest

**Vista info**

```
    Current FileType:
Avaliable Executives: ['ctags', 'vim_lsp']
    Global Variables:
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'nvim_lsp', 'vim_lsc', 'vim_lsp']
    let g:vista#extensions = ['markdown', 'rst']
    let g:vista#finders = ['fzf', 'skim']

```

**Steps to reproduce given the above info**

1. open a file with tags (from ctags)
2. move around between tags
3. observe cursor change from vista when moving cursor between tags
4. sometimes when you stop cursor at some point, it does `flick`

**Expected behavior**
Does not have flick

**Actual behavior**
less flicks than tagbar but still flick at some points.

**Comment by liuchengxu** [comment]
Not sure what the flicker is.

**Comment by ranebrown** [comment]
@liuchengxu I'm seeing this same flickering behavior. It occurs on file save or if the `TextChanged` and `TextChangedI` events are enabled. Could you please reopen? I can provide more information if needed.

**Comment by ranebrown** [comment]
It is definitely related to the screen redraw. I am seeing the same thing when switching windows from the vista window back to the main window. The behavior is much less noticeable with a minimal vimrc but still present.

**Comment by liuchengxu** [comment]
Can't help more with the current report.

**Comment by tmpm697** [comment]
Is that possible to have external binay running in background causing this issue? I think ctags binary is running in background and might produce the issue. I observe the same behavior when using linter/fixer from ale.

**Comment by ranebrown** [comment]
I would definitely like to get this fixed but not really sure how to figure out what is causing it...

**Comment by sealter** [comment]
I have screen flicker problem in vim too.

**Comment by tmpm697** [comment]
Either one or more plugins are using/calling binary in background that cause this issue, you can open nvim with each one of them to figure out, or check [this](https://github.com/neovim/neovim/wiki/FAQ#cursor-flicker-in-tmux) if you use tmux.
