### ISSUE TITLE
Add an option to disable default key mappings

### ISSUE THREAD

**Issue by iv-nn** [liuchengxu/vista.vim#218]
**Is your feature request related to a problem? Please describe.**

I'm using a non standard keyboard layout so the default key mappings for sorting `s` conflict with one of my navigation key.

**Describe the solution you'd like**

An option to disable default key mappings like [vim-abolish](https://github.com/tpope/vim-abolish/blob/7e4da6e78002344d499af9b6d8d5d6fcd7c92125/plugin/abolish.vim#L626) does it for example.

**Describe alternatives you've considered**

Maybe I could remap the key in some `after` config but I doubt that would work given how mappings are set inside `vista#ftplugin#Set` which seems to be called multiple times.

**Additional context**

I can make a PR with an option called `g:vista_no_mappings`.

**Comment by liuchengxu** [comment]
I'm ok with `g:vista_no_mappings`, feel free to PR.
