### ISSUE TITLE
Remove statusline from Vista window

### ISSUE THREAD

**Issue by kkoomen** [liuchengxu/vista.vim#219]
I'm not sure whether #43 is the same question as I have, but I am using [itchyny/lightline.vim](https://github.com/itchyny/lightline.vim) and it's still showing the statusline inside the Vista window. Probably because the `statusline` variable is updated on `BufEnter` by lightline.

I tried to set `let g:vista_disable_statusline = 1` but this did not help at all. I can see the default is `exists('g:loaded_airline') || exists('g:loaded_lightline')` and `exists('g:loaded_lightline')` evaluates to `1` in my vim. 

<img width="1792" alt="Screenshot 2020-01-09 at 23 32 52" src="https://user-images.githubusercontent.com/10693490/72080830-64c46880-3338-11ea-81f6-2dd9d96e4974.png">

**Comment by liuchengxu** [comment]
I don't use the other statusline plugin and don't see the problem in the picture. Please make the report more clear by filling the issue template, providing the minimal vimrc and detailed steps would be helpful.

**Comment by kkoomen** [comment]
> [...] don't see the problem in the picture. 

I don't know how you can say this. See screenshot below. This _is_ the statusline and is still showing.

<img width="1792" alt="Screenshot 2020-01-09 at 23 32 52" src="https://user-images.githubusercontent.com/10693490/72083292-83c4f980-333c-11ea-8994-b54155daf128.png">

**Comment by liuchengxu** [comment]
That's set by your own statusline plugin, not by vista.vim.

**Comment by kkoomen** [comment]
I edited my description by giving you more info.

> That's set by your own statusline plugin, not by vista.vim.

That's the whole idea of this issue! What does `g:vista_disable_statusline`  do then? You are providing a fix for airline and lightline but lightline is not working for me.

**Comment by kkoomen** [comment]
I got the fix.

This is your function:
```
function! vista#statusline#Render() abort
  if vista#statusline#ShouldDisable()
    return
  endif

  if has_key(t:vista, 'bufnr')
    call setbufvar(t:vista.bufnr, '&statusline', vista#statusline#())
  endif
endfunction
```

but you are having this condition:

```
  if vista#statusline#ShouldDisable()
    return
  endif
```

which should be: 

```
  if vista#statusline#ShouldDisable()
    call setbufvar(t:vista.bufnr, '&statusline', '')
    return
  endif
```

Can you add that and merge these changes?

**Comment by kkoomen** [comment]
Can this be re-opened? It's invalid to close this issue.

**Comment by liuchengxu** [comment]
>which should be:
>
>  if vista#statusline#ShouldDisable()
>    call setbufvar(t:vista.bufnr, '&statusline', '')
>    return
>  endif

That's incorrect. I think you get confused here. What a statusline plugin does is actually to set `&statusline` for you. You _fix_ is to reset the statusline to be a empty string, that's obviously not what `g:vista_disable_statusline` should do.

Everything I see is normal. Show me the unexpected bebavior, and what you expected is.

**Comment by kkoomen** [comment]
> Show me the unexpected bebavior, and what you expected is.

Read the issue description.

**Comment by liuchengxu** [comment]
>That's set by your own statusline plugin, not by vista.vim.

**Comment by kkoomen** [comment]
Then can you share how you managed what I want in your README demo? Your demo shows no statusline on the right.

**Comment by liuchengxu** [comment]
That is not what you called `no statusline`. That's the default statusline set by vista.vim in the README demo. I use https://github.com/liuchengxu/eleline.vim in the README demo. Actually you just need to disable your own statusline plugin, then you can the difference.
