### ISSUE TITLE
E46 pops up when hovering symbol types

### ISSUE THREAD

**Issue by gbrlsnchs** [liuchengxu/vista.vim#22]
**Describe the bug**
I get the following error whenever cursor is hovering symbol types (e.g. `Method`, `Function`, `Field`, `Variable`, `Class`):
```
Error detected while processing function vista#cursor#ShowDetail:
line   11:
E46: Cannot change read-only variable "count"
```
**Steps to reproduce**

1. Open a source file that works under LSP
2. Call `:Vista`
3. Move cursor over symbol types

**Expected behavior**
Error shouldn't happen.

**Actual behavior**
The following error pops up:
```
Error detected while processing function vista#cursor#ShowDetail:
line   11:
E46: Cannot change read-only variable "count"
```

**Screenshot or gif**
I hovered `▸ Method`:
![image](https://user-images.githubusercontent.com/7577128/54533221-6b788e00-4968-11e9-85c2-2b690cdda198.png)

**Environment:**
- OS: Debian 9.7 (Stretch)
- Vim/Neovim version:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar  6 2019 09:15:43)
Included patches: 1-996
```
- This plugin version: `a5d77a5b061fc22030cfb3700eaed99ed19abe40`

**Comment by liuchengxu** [comment]
Can't reproduce locally.

<img width="1680" alt="屏幕快照 2019-03-18 下午9 43 38" src="https://user-images.githubusercontent.com/8850248/54534249-ebcddc00-49c6-11e9-8d21-f9df11e05b52.png">

**Comment by gbrlsnchs** [comment]
Are you using coc.nvim to create those symbols? I am using coc.nvim with `bingo` LSP server, could that have something to do with that?

**Comment by liuchengxu** [comment]
I forgot that I switch to neovim for a while :(. I reproduce this issue in vim, but not in neovim. Should be fixed now.

**Comment by gbrlsnchs** [comment]
No problem, I just updated it and it is now working as intended. Thank you very much and good job!
