### ISSUE TITLE
exuberant ctags is not supported?

### ISSUE THREAD

**Issue by zoumi** [liuchengxu/vista.vim#222]
if I set 
`let g:vista_ctags_executable = "exuberant_ctags"`
I got this error
![image](https://user-images.githubusercontent.com/5162901/72216186-e1ce2880-3558-11ea-8a06-b85931063548.png)

if I set 
`let g:vista_ctags_executable = "universal_ctags"`
it works.

both exuberant_ctags.exe and universal_ctags.exe is in the gvim.exe(E:\vim\vim81)

And if I didn't put E:\vim\vim81 to the system environment PATH.
Vista will complaint ctags missing. Should $VIM be a default search dir?

**Comment by liuchengxu** [comment]
README have declared that, only https://github.com/universal-ctags/ctags is supported, I never used exuberant ctags and I won't add that support by myself.

You either put `ctags.exe` in your PATH, or you have to specify the executable path by `g:vista_ctags_executable`. vista.vim doesn't search these executables itself, that's the job of `system()` and `job` of vim.
