### ISSUE TITLE
Duplicated details for fields and variables

### ISSUE THREAD

**Issue by gbrlsnchs** [liuchengxu/vista.vim#23]
**Describe the bug**
When I hover over fields or variables, the details are duplicated. It doesn't happen for other types.

**Steps to reproduce**

1. Call `:Vista`
2. Hover on fields or variables

**Expected behavior**
Unique detail message.

**Actual behavior**
Duplicated details show up.

**Screenshot or gif**
![image](https://user-images.githubusercontent.com/7577128/54544684-e482e000-497e-11e9-8376-7a702b082da2.png)

![image](https://user-images.githubusercontent.com/7577128/54544731-fa90a080-497e-11e9-9f0c-789c8d553e50.png)

**Environment:**
- OS: Debian 9.7 (Stretch)
- Vim/Neovim version:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar  6 2019 09:15:43)
Included patches: 1-996
```
- This plugin version: `036ed923b3d1d4911eeedc07e2b32f5f5b37a5b6`

**Comment by liuchengxu** [comment]
Thanks for the report. Should be fixed now.
