### ISSUE TITLE
Cannot work with coc

### ISSUE THREAD

**Issue by Neur1n** [liuchengxu/vista.vim#235]
**Describe the bug**
Neither `:Vista` nor `:Vista coc` triggers the tag window.

**Environment:**
- OS: Windows 10
- Neovim version: 0.5.0-357-g405f49a9b
- This plugin version: 486d78b04d327fe6704b4f2b27b9c897f7dc6a0b
- I'm using some LSP client:
    - Related Vim LSP client: coc
    - The Vim LSP client version: 7683a8e466af374668dac49cc439fd1791d6a5fc
    - Have you tried updated to the latest version of this LSP client: Yes

**Vista info**
```
 Current FileType: python
Avaliable Executives: ['coc', 'ctags']
    Global Variables:
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'nvim_lsp', 'vim_lsc', 'vim_lsp']
    let g:vista#extensions = ['markdown', 'rst']
    let g:vista#finders = ['fzf', 'skim']
```

**Steps to reproduce given the above info**
Just type in `:Vista` or `:Vista coc`. By the way, by using `:Vista ctags`, the tag window can be triggered.

**Minimal vimrc (neccessary when this issue is about some Vim LSP client):**
```vim
set nocompatible
set runtimepath^=/path/to/vista.vim
set runtimepath^=/path/to/coc.nvim
syntax on
filetype plugin indent on
```

**Expected behavior**
Work with coc.

**Actual behavior**
Type in `:Vista coc` and nothing happens.

**Comment by liuchengxu** [comment]
1. Ensure you have setup coc correctly.
2. `:Vista coc` is async, some language server might take some time to respond, you can try running the command later.

**Comment by Neur1n** [comment]
Sorry, it was due to the MPLS wasn't downloaded successfully.

**Comment by douglarek** [comment]
> Works for me.
> 
>     1. Ensure you have setup coc correctly.
> 
>     2. `:Vista coc` is async, some language server might take some time to respond, you can try running the command later.
> 
> 
> Beyond that, you can check out if coc is ready via `:echo CocAction('documentSymbols')`.

it does not work for me. I am using coc to edit go files.

This is the output of `:echo CocAction('documentSymbols')`:

<img width="1438" alt="Screen Shot 2020-02-06 at 4 54 57 PM" src="https://user-images.githubusercontent.com/1488134/73920959-69f9e080-4901-11ea-85b2-70361da55694.png">

But `:Vista coc` still output nothing:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/1488134/73921102-b5ac8a00-4901-11ea-811e-dc992b162094.png">

**Comment by Iron-E** [comment]
Hello,

I see this action is closed, but I am affected as well. I can type `:Vista coc` and nothing happens.

Here is the output of `:echo CocAction('documentSymbols')`:
```
[{'lnum': 7, 'col': 8, 'range': {'end': {'character': 20, 'line': 6}, 'start': {'character': 7, 'line': 6}}, 'level': 0, 'kind': 'Variable', 'containerName': v:null, 'text': '_loadedRoomId'}, {'lnum': 10, 'col': 12, 'range': {'end': {'character': 23, 'line': 9}, 'start': {'character': 11, 'line': 9}}, 'level': 0, 'kind': 'Property', 'containerName': v:null, 'text': 'loadedRoomId'}, {'lnum': 13, 'col': 6, 'range': {'end': {'character': 30, 'line': 12}, 'start': {'character': 5, 'line': 12}}, 'level': 0, 'kind': 'Function', 'containerName': v:null, 'text': pane_chat_messages_update'}, {'lnum': 57, 'col': 6, 'range': {'end': {'character': 18, 'line': 56}, 'start': 'character': 5, 'line': 56}}, 'level': 0, 'kind': 'Function', 'containerName': v:null, 'text': '_message_sync'}]
```

For context, I am editing Dart files using [coc-flutter](https://github.com/iamcco/coc-flutter).

**Comment by liuchengxu** [comment]
@Iron-E See https://github.com/liuchengxu/vista.vim/issues/237#issuecomment-583859662, `CocAction('documentSymbols')` is not that reliable, and vista.vim can't help more about that.
