### ISSUE TITLE
NearestMethodOrFunction get no value with coc.nvim backend

### ISSUE THREAD

**Issue by xayjin** [liuchengxu/vista.vim#240]
hi, I use coc.nvim, and the vista_default_executive is coc, but NearestMethodOrFunction can't get value.
Can NearestMethodOrFunction work with coc?

I have looked into excecutive/coc.vim, found s:data is not parsering to t:vista, which is used by NearestMethodOrFunction.

**Comment by horseinthesky** [comment]
Same thing for me.

**Comment by liuchengxu** [comment]
Fill the issue template please.
