### ISSUE TITLE
:Vista finder! uses ctags instead of default executive

### ISSUE THREAD

**Issue by Shatur95** [liuchengxu/vista.vim#245]
**Describe the bug**
`:Vista finder!` command ignores specified executive.

**Environment:**
- OS: Arch Linux
- Vim/Neovim version:
```
NVIM v0.5.0-392-gff1730373
Build type: Release
```
- This plugin version: c4435a847364dfdce2747707bb5514ccfe8419f7
- I'm using some LSP client:
    - Related Vim LSP client: nvim_lsp
    - The Vim LSP client version: [latest master as the time of writing](https://github.com/neovim/nvim-lsp/commit/1739274e24087565760b35a789a28bc217308ecf)

**Vista info**

```
    Current FileType: cpp
Avaliable Executives: []
    Global Variables:
    let g:vista#executive#ctags#support_json_format = 0
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'nvim_lsp', 'vim_lsc', 'vim_lsp']
    let g:vista#extensions = ['markdown', 'rst']
    let g:vista#finders = ['fzf', 'skim']
    let g:vista#renderer#ctags = 'default'
    let g:vista#renderer#enable_icon = 1
    let g:vista#renderer#icons = {'subroutine': '羚', 'method': '', 'func': '', 'variables': '', 'namespace': '', 'field': '', 'interface': '', 'type': '', 'packages': '', 'property': '襁', 'implementation': '', 'default': '', 'augroup': 'פּ', 'macro': '', 'enumerator': '', 'const': '', 'macros': '', 'map': 'פּ', 'fields': '', 'functions': '', 'enum': '', 'function': '', 'target': '', 'typedef': '', 'variable': '', 'modules': '', 'constant': '', 'struct': '', 'types': '', 'module': '', 'typeParameter': '', 'package': '', 'class': '', 'member': '', 'var': '', 'union': '鬒'}
    let g:vista#renderer#kind_default_icon = ['╰─▸ ', '├─▸ ']
    let g:vista_default_executive = 'nvim_lsp'
    let g:vista_executive_nvim_lsp_fetching = v:false
    let g:vista_executive_nvim_lsp_reload_only = v:false
    let g:vista_executive_nvim_lsp_should_display = v:false
```

**Steps to reproduce given the above info**

minimal vimrc (neccessary when this issue is about some Vim LSP client):

```vim
let g:vista_default_executive = 'nvim_lsp'
```

1. Run `:Vista finder!`

**Expected behavior**
Shows all tags in project.

**Actual behavior**
Prints:
```
[vista.vim]Fail to run ctags given command: ctags -R -x -- ...
[vista.vim] Empty data for finder
```

**Comment by liuchengxu** [comment]
The tags for project is unsupported for LSP executives.

**Comment by Shatur95** [comment]
I did not know about this, thanks for the information.
Qt Creator has such functionality, but I do not know what it uses for this.

**Comment by liuchengxu** [comment]
LSP has a concept of `workspaceSymbols` similar to the recursive project tags if anyone is interested.

**Comment by Shatur95** [comment]
It would be great to implement it.
I would do it myself, but I'm not familiar with Vim script :(

**Comment by liuchengxu** [comment]
Closing as duplicate as #302.
