### ISSUE TITLE
:G difftool -y is broken

### ISSUE THREAD

**Issue by Shatur95** [liuchengxu/vista.vim#252]
**Describe the bug**
vim-fugitive comand `:G difftool -y` is broken after d1168223df415e45d7944e0b251d08f67f560268 (it works in a1e19503ce2f27a98fd6c03202d0651891aadecf). I don't know how it can be related, because Vista buffer even not opened.

**Environment:**
- OS: ArchLinux
- Vim/Neovim version: 0.4.3
- This plugin version: ed33c4715a31a84e8e2bafc971bc63c9d8882b34 (latest commit at the moment of writing)
- I'm using some LSP client:
    - Related Vim LSP client: `vim_lsp`
    - The Vim LSP client version: f79bf399220070123ca7642b318e5231843eb087 (latest commit at the moment of writing)
    - Have you tried updated to the latest version of this LSP client: Yes

**Vista info**

```
    Current FileType: cpp
Avaliable Executives: ['ctags', 'vim_lsp']
    Global Variables:
    let g:vista#executive#ctags#support_json_format = 1
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'nvim_lsp', 'vim_lsc', 'vim_lsp']
    let g:vista#extensions = ['markdown', 'rst']
    let g:vista#finders = ['fzf', 'skim']
    let g:vista#renderer#ctags = 'default'
    let g:vista#renderer#enable_icon = 1
    let g:vista#renderer#icons = {'subroutine': '羚', 'method': '', 'func': '', 'variables': '', 'namespace': '', 'field': '', 'interface': '', 'type': '', 'packages': '', 'property': '襁', 'implementation': '', 'default': '', 'augroup': 'פּ', 'macro': '', 'enumerator': '', 'const': '', 'macros': '', 'map': 'פּ', 'fields': '', 'functions': '', 'enum': '', 'function': '', 'target': '', 'typedef': '', 'variable': '', 'modules': '', 'constant': '', 'struct': '', 'types': '', 'module': '', 'typeParameter': '', 'package': '', 'class': '', 'member': '', 'var': '', 'union': '鬒'}
    let g:vista#renderer#kind_default_icon = ['╰─▸ ', '├─▸ ']
    let g:vista_executive_for = {'gdscript': 'vim_lsp', 'cpp': 'vim_lsp', 'python': 'vim_lsp'}
```

**Steps to reproduce given the above info**

1. Create some changes in repo.
2. `:G difftool -y`.

**Expected behavior**
This command must show all repo diffs.

**Actual behavior**
I see the following error without diffs
![изображение](https://user-images.githubusercontent.com/22453358/76850711-9f72e180-6850-11ea-8fbf-a498390d7efb.png)

**Comment by liuchengxu** [comment]
Can you also provide a minimal vimrc to help reproduce?

**Comment by Shatur95** [comment]
Sorry for the incomplete information.
The problem is reproduced without any configuration. Just need to have the following minimal plugins installed: [vim-airline](https://github.com/vim-airline/vim-airline), [vim-fugitive](https://github.com/tpope/vim-fugitive) and vista.vim. If I remove vim-airline - the issue will disappear.

**Comment by Shatur95** [comment]
It helped, thank you!
