### ISSUE TITLE
大佬  vista.vim启动速度非常慢 有办法加快吗

### ISSUE THREAD

**Issue by huayue369** [liuchengxu/vista.vim#26]

**Comment by liuchengxu** [comment]
不可能。肯定是你的问题。

如果觉得是 vista.vim 的问题，可以提供最小 vimrc 和重现步骤。

**Comment by huayue369** [comment]
恩 关于速度问题已解决  好像是我映射问题  但又出现一个新问题 好像和goyo插件冲突  只要我打开goyo就会出现错误提示  
<img width="846" alt="屏幕快照 2019-03-25 下午7 33 33" src="https://user-images.githubusercontent.com/32536764/54918600-b16dbd00-4f39-11e9-8066-5966493fe87d.png">

**Comment by liuchengxu** [comment]
请另开 issue 并提供最小 vimrc 和重现步骤。
