### ISSUE TITLE
ts中tsx没有支持

### ISSUE THREAD

**Issue by wellcomez** [liuchengxu/vista.vim#260]
**Is your feature request related to a problem? Please describe.**
ts中ts扩展名支持，但是tsx 没有支持。无法显示函数列表。ts基本正常
**Describe the solution you'd like**
tsx和ts应该在ts 的lsp中可以采用同样的处理。是不是漏了
**Describe alternatives you've considered**

**Additional context**

**Comment by glepnir** [comment]
The filetype of tsx is `typescriptreact`, you can config it by `g:vista_executive_for` like
```vim
let g:vista_executive_for = {
  \ 'typescriptreact': 'coc',
  \ }
```

**Comment by CG-man** [comment]
我这里依然无法解决楼主遇到的问题, 用了 @glepnir   的方案依旧无效, 我需要怎么修改配置吗? 还是我遇到了Bug

**Comment by glepnir** [comment]
@CG-man  
 I can't reproduce your problem with the latest commit vim-clap. 

![image](https://user-images.githubusercontent.com/41671631/90637561-bcc43580-e25e-11ea-9f27-a4a7d300c5a1.png)
