### ISSUE TITLE
Vista seems show wrong symbol icon.

### ISSUE THREAD

**Issue by roachsinai** [liuchengxu/vista.vim#261]
**Describe the bug**

Picture below is just copy from vista.vim README.md

![](https://user-images.githubusercontent.com/8850248/55805524-2b449f80-5b11-11e9-85d4-018c305a5ecb.png)

Found the setting at `/autoload/vista/renderer.vim`

```
let g:vista#renderer#icons = {
\   "function": "\uf794",
\   "variable": "\uf71b",
\  }
```

icon for `variable` `"\uf71b"`, should be

![image](https://user-images.githubusercontent.com/9500049/78096260-bb0ee800-740b-11ea-866f-23dd052fce19.png)

from https://www.fileformat.info/info/unicode/char/f71b/index.htm

But, why got a `x`.

**Environment:**
- OS: Manjaro 19.0.2
- Vim/Neovim version: `VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  1 2020 17:21:03)
包含补丁: 1-343`
- This plugin version: 10a0f5c53aba5cda0f22bbd63d72a0b149f56242

**Comment by roachsinai** [comment]
I got same `x` icon for variable.

**Comment by liuchengxu** [comment]
That's how vim displays this unicode, I have explained in this comment https://github.com/liuchengxu/vista.vim/issues/55#issuecomment-607012224https://github.com/liuchengxu/vista.vim/issues/55#issuecomment-607012224.
