### ISSUE TITLE
update slowly when switching buffer

### ISSUE THREAD

**Issue by JarodLi** [liuchengxu/vista.vim#262]
**Describe the bug**
Switch files in BufExplorer, the vista window update very slow, sometimes not update.   
Maybe this commit(https://github.com/liuchengxu/vista.vim/pull/204) cause the bug， when I rollback the follow change， it works well. 

![image](https://user-images.githubusercontent.com/3362590/78126433-20cb9600-7445-11ea-9b3d-a110dab513e2.png)

**Comment by liuchengxu** [comment]
Use profile to see what the slow part is, `:h profile` and see https://codeinthehole.com/tips/debugging-vim-by-example/#why-is-action-slow .
