### ISSUE TITLE
how do I specify ctag options for a specific file type?

### ISSUE THREAD

**Issue by asknet** [liuchengxu/vista.vim#263]
Hi,
how do I specify ctag options for a specific file type?
I tried this option but it didn't worked

let g:vista_ctags_cmd = {'apexcode': 'ctags --extra=+q --langmap=java:.cls.trigger',}

Thank you!

**Comment by liuchengxu** [comment]
Works for me. `apexcode` must be the corrent filetype, ensure it's right by `:echo &ft`.

**Comment by asknet** [comment]
It's not working at my end. Is there a way to troubleshoot this?

**Comment by asknet** [comment]
@liuchengxu when I add similar changes for tagbar plugin it worked to show tags for this filetype 'apexcode'

let g:tagbar_type_apexcode = {
  \ 'ctagstype' : 'java',
  \ 'kinds'     : [
		\ 'c:class',
		\ 'i:interface',
		\ 'e:enum',
		\ 'f:field',
		\ 'P:property',
		\ 'm:method',
	\ ],
	\ 'sro' : '.',
	\ 'scope2kind' : {
		\ 'enum'      : 'e',
		\ 'interface' : 'i',
		\ 'class'     : 'c',
	\ },
\ }
