### ISSUE TITLE
Highlight Mismatch

### ISSUE THREAD

**Issue by againxx** [liuchengxu/vista.vim#264]
**Describe the bug**
Highlight mismatch, when there is number within square brackets

**Environment:**
- OS: Ubuntu 18.04
- Vim/Neovim version:
NVIM v0.5.0-dev
Build type: RelWithDebInfo
- This plugin version: a4b5386879ef9db9a7967571ca4b534311de87e2
- I'm using some LSP client:
    - Related Vim LSP client: coc
    - Have you tried updated to the latest version of this LSP client: Yes

**Vista info**

    Current FileType: 
    Avaliable Executives: ['coc', 'ctags']
    Global Variables:
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'nvim_lsp', 'vim_lsc', 'vim_lsp']
    let g:vista#extensions = ['markdown', 'rst']
    let g:vista#finders = ['fzf', 'skim']
    let g:vista_blink = [2, 100]
    let g:vista_close_on_jump = 1
    let g:vista_cursor_delay = 400
    let g:vista_default_executive = 'coc'
    let g:vista_echo_cursor = 1
    let g:vista_executive_for = {'vim': 'ctags', 'cpp': 'coc', 'python': 'coc'}
    let g:vista_find_absolute_nearest_method_or_function = 0
    let g:vista_find_nearest_method_or_function_delay = 300
    let g:vista_fold_toggle_icons = ['▼', '▶']
    let g:vista_fzf_preview = ['up:60%']
    let g:vista_icon_indent = ['╰─▸ ', '├─▸ ']
    let g:vista_no_mappings = 0
    let g:vista_sidebar_width = 40
    let g:vista_top_level_blink = [2, 100]
    let g:vista_update_on_text_changed = 0
    let g:vista_update_on_text_changed_delay = 500

**Steps to reproduce given the above info**
1. Open vista finder with fzf preview
2. Vista will highlight some part of the preview boundry and codes into FZFVistaTag and FZFVistaScope higroup, the yellow line in the first and second pictures.
3. Slightly modify the regex will fix it, please see the last picture.

**Expected behavior**
Correct matched highlight
**Actual behavior**
Mismatched highlight

**Screenshot or gif** (if possible)
![vista_problem1](https://user-images.githubusercontent.com/22728604/78483058-d9147980-7778-11ea-9768-21b18139b22d.png)
![vista_problem2](https://user-images.githubusercontent.com/22728604/78483136-ddd92d80-7778-11ea-953f-7710380b2195.png)
![vista_modify](https://user-images.githubusercontent.com/22728604/78483218-e3cf0e80-7778-11ea-8d76-60bef52b8d3b.png)

**Comment by liuchengxu** [comment]
Feel free to send a PR.
