### ISSUE TITLE
:Vista not working for filetype Vim

### ISSUE THREAD

**Issue by qsmy41** [liuchengxu/vista.vim#267]
**Describe the bug**
In files which `filetype=vim`, when I enter the command `:Vista`, nothing pops out. When I enter the command `:Vista finder vim_lsp`, the following error occurs:

```
Error detected while processing function vista#[30]..<SNR>51_HandleArguments[28]..vista#finder#Dispatch[10]..vista#finder#fzf#Run[5]..vista#finder#GetSymbols[38]..<SNR>58_TryAlternatives[16]..vista#executive#ctags#Run[1]..<SNR>62_Dispatch[11]..<SNR>62_Run:
line    8:
E121: Undefined variable: s:data
Error detected while processing function vista#[30]..<SNR>51_HandleArguments[28]..vista#finder#Dispatch[10]..vista#finder#fzf#Run:
line    5:
E714: List required
```
When handling files with other file types, such as tex, python, c, it is fine using coc as lsp executive. Only vim files are not working as expected.

**Environment:**
- OS: MacOS
- Vim/Neovim version: Vi IMproved 8.1
- This plugin version:  04500b9fe83c39cdc07a1ea8e48a81d182f1b864
- I'm using some LSP client:
    - Related Vim LSP client: vim_lsp
    - The Vim LSP client version: ensured it is up-to-date by running `:PlugUpdate`

**Steps to reproduce given the above info**

source file for reproduce the issue: ~/.vimrc OR Path/To/plugged/vista.vim/autoload/vista.vim

minimal vimrc (neccessary when this issue is about some Vim LSP client):

```vim
set nocp

call plug#begin('~/.vim/plugged')
Plug 'liuchengxu/vista.vim'
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
call plug#end()

let g:vista#executives = ['coc', 'ctags', 'lcn', 'vim_lsp']

let g:vista_executive_for = {
  \ 'cpp': 'vim_lsp',
  \ 'php': 'vim_lsp',
  \ 'vim': 'vim_lsp',
  \ }
```

1. source the vimrc
2. install the plugins
3. `:Vista` and `:Vista finder vim_lsp` (or change to vista.vim or any other vim files for testing)

**Expected behavior**
Pop up a side bar with defined variables and functions in the Vimscript shown.

**Actual behavior**
No respond from `:Vista` and error messages from `:Vista finder vim_lsp`.

**Screenshot or gif** (if possible)
![Screenshot 2020-04-07 at 01 33 08](https://user-images.githubusercontent.com/44122119/78617861-9fbf3500-7870-11ea-8c20-c9043aeacdd1.png)
![Screenshot 2020-04-07 at 01 33 50](https://user-images.githubusercontent.com/44122119/78617883-bbc2d680-7870-11ea-8628-b6507987ce96.png)
![Screenshot 2020-04-07 at 01 35 11](https://user-images.githubusercontent.com/44122119/78617890-bf565d80-7870-11ea-897a-e9e2dd1b0738.png)

**Comment by liuchengxu** [comment]
Have you installed the vim language server and ctags? vim_lsp won't work if you don't install the related language server. And vista.vim will fall back to ctags when using `:Vista finder vim_lsp` if it's installed on your system, but you don't have ctags either.

<img width="1680" alt="截屏2020-04-07 上午8 58 06" src="https://user-images.githubusercontent.com/8850248/78618727-f0a14e80-78ad-11ea-9881-d27e8df35b98.png">

**Comment by qsmy41** [comment]
The minimal vimrc has me installed vim_lsp, and in the actual vimrc I have coc with coc_vimlsp extension installed. I believe these two can both be the LSP option for vim, so I think there should not be a problem in setting, let's say coc, to be the LSP for Vimscript. 

Besides, I have installed ctags with `brew install ctags`, and when I use ctags as my LSP option, the side bar pops up, but without anything other than the file name on top. In this case `:Vista` responds, but having no variables or functions in the side tab.

Lastly, in the minimal vimrc, when I look at the output from `:Vista info`, in the second line 'available executives' section, I see 'ctags' being one of them. I believe this means that ctags is installed for me. Same for vim_lsp. Is there any misinterpretation here? Or is there something I am doing wrong in the previous points?

The following image is the output I get from my vimrc, just to show that coc was also one of the available executives, and other potential useful information:
![Screenshot 2020-04-07 at 11 25 15](https://user-images.githubusercontent.com/44122119/78658744-7b8c4400-78c2-11ea-84fb-5c15af84abe9.png)

**Comment by liuchengxu** [comment]
A provider which is avaliable in `:Vista info`  merely says you have installed this plugin, no guarantee about the other settings and that doesn't mean it can work as expected. 

Your vista.vim is absolutely not the latest version from your `:Vista info`. You should firstly update to the latest version and try.

**Comment by qsmy41** [comment]
I did `:PlugUpdate` to ensure that every plugin is up-to-date. Is there anything else you could recommend me to check?

**Comment by liuchengxu** [comment]
Enter `~/.vim/plugged` and ensure vista.vim is the latest version as the output of your `Vista info` is clearly outdated.

**Comment by qsmy41** [comment]
I entered the `/vista.vim` folder and check version with `git remote show origin`, and it shows that I am up to date.

![Screenshot 2020-04-07 at 12 53 06](https://user-images.githubusercontent.com/44122119/78666113-c9a74480-78ce-11ea-9bbf-f60fa2190aab.png)

**Comment by liuchengxu** [comment]
Here is the output of my `:Vista info` with your provided minimal vimrc:

<img width="1680" alt="截屏2020-04-07 下午8 07 10" src="https://user-images.githubusercontent.com/8850248/78667396-6d164a80-790b-11ea-99fc-f4faabe42bc9.png">

vista.vim relays on the API of vim lsp client plugins to fetch the symbols, e.g., `CocActionAsync()` and `CocAction()` for coc.nvim, you can refer to https://github.com/liuchengxu/vista.vim/issues/237#issuecomment-583859662 to  check the coc output. But I don't use vim_lsp, you can add some debugging info in this request https://github.com/liuchengxu/vista.vim/blob/04500b9fe83c39cdc07a1ea8e48a81d182f1b864/autoload/vista/executive/vim_lsp.vim#L62 to see if vim_lsp works as expected.

**Comment by qsmy41** [comment]
The greatest difference is the renderer icons? I got the multiple-line output for icons after I run `:Vista` once. Otherwise if I open a file and immediately `:Vista info`, only two icons will be shown. 

![Screenshot 2020-04-07 at 14 26 41](https://user-images.githubusercontent.com/44122119/78674660-d8e0bf00-78db-11ea-97c6-1ecb153dd817.png)

I actually use coc, vim_lsp is just for testing to see if the problem takes place not just for coc, and for the sake of producing the minimal vimrc. On the coc side, I believe I just need to `:CocInstall coc-vimlsp` and then it should work like other files, like python, latex, etc?

I am not sure about how to debug, as I am not familiar with Vimscript. I tried with very basic `echom "Hello world."` placed under the line you provided, and there is nothing changed, the message is not printed when I do `:Vista` or `:Vista finder vim_lsp`.

**Comment by liuchengxu** [comment]
Like this comment mentioned https://github.com/liuchengxu/vista.vim/issues/237#issuecomment-583859662, the API of coc.nvim used in vista.vim is not stable enough, I don't use coc-vimlsp since last time I tried but it doesn't work well. You can see if other other filetypes can work as expected, e.g., go, if they do, then it's an issue of coc.nvim or the related language server, not vista.vim.

**Comment by qsmy41** [comment]
Thank you for your clarification, I think I will then open an issue in coc to report this problem.
