### ISSUE TITLE
Ctags errors aren't handled gracefully, for example wrong options

### ISSUE THREAD

**Issue by BlueDrink9** [liuchengxu/vista.vim#270]
**Describe the bug**

My ctags.exe (Exuberant Ctags 5.8) doesn't accept the option `--extras`. It does, however, accept the option `--extra`. Note the lack of `s`.

I understand that exuberant is very old, and basically deprecated. Sadly, universal ctags, its replacement, doesn't have an official release yet.

Since Universal ctags doesn't have a windows binary, perhaps Vista should check the ctags version or catch whether the option is invalid, and use the other option instead?
Edit: I take it back, [it does have binaries](https://github.com/universal-ctags/ctags-win32/releases)

See Microsoft/vscode-python#3517 for related discussion.

Personally I'm going to swap to universal, but I suspect other users might not. Errors from ctags cause parsing errors like seen in #253. (PR incoming)

An alternative is making it much more explicit that **universal** ctags is required, and that Exhuberant isn't enough.

**Environment:**
- OS: Windows 10
- Vim/Neovim version: 
- This plugin version: 12243d5
- I'm using ctags:
    - Ctags version:  Exuberant Ctags 5.8

**Vista info**

```
Current FileType: autohotkey
Avaliable Executives: ['ctags', 'lcn']
Global Variables:
let g:vista = {'get_tagline_under_cursor': function('40'), 'winnr': function('38'), 'raw_by_kind': {}, 'tree': {}, 'source': {'fpath': 'C:\Users\user\Documents\AHK scripts\autodisable_workrave.ahk', 'bufnr': 4, 'get_winid': function('42'), 'fname': 'autodisable_workrave.ahk', 'winnr': 1, 'extension': function('47'), 'line': function('45'), 'get_winnr': function('41'), 'filetype': function('43'), 'lines': function('44'), 'winid': 1000, 'line_trimmed': function('46'), 'scope_seperator': function('48')}, 'with_scope': [], 'provider': 'ctags', 'without_scope': [], 'ctags_cmd': 'ctags --format=2 --excmd=pattern --fields=nksSaf --file-scope=yes --sort=no --append=no --extras=   -f- C:\Users\user\.cache\vista\84490bf7eeec727acf5132eeff802df6c706c0a5a82b4fcdc8e64072eb31bbf4.ahk', 'winid': function('39'), 'functions': [], 'raw': [], 'kinds': []}
let g:vista#executive#ctags#support_json_format = 0
let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'nvim_lsp', 'vim_lsc', 'vim_lsp']
let g:vista#extensions = ['markdown', 'rst']
let g:vista#finders = ['fzf', 'skim']
let g:vista_blink = [2, 100]
let g:vista_close_on_jump = 0
let g:vista_cursor_delay = 400
let g:vista_default_executive = 'ctags'
let g:vista_disable_statusline = 1
let g:vista_echo_cursor = 1
let g:vista_executive_for = {'markdown': 'toc'}
let g:vista_find_absolute_nearest_method_or_function = 0
let g:vista_find_nearest_method_or_function_delay = 300
let g:vista_fold_toggle_icons = ['▼', '▶']
let g:vista_fzf_preview = ['right:50%']
let g:vista_icon_indent = ['└ ', '│ ']
let g:vista_ignore_kinds = []
let g:vista_no_mappings = 0
let g:vista_sidebar_position = 'vertical botright'
let g:vista_sidebar_width = 30
let g:vista_stay_on_open = 1
let g:vista_top_level_blink = [2, 100]
let g:vista_update_on_text_changed = 0
let g:vista_update_on_text_changed_delay = 500
```

**Comment by liuchengxu** [comment]
Only https://github.com/universal-ctags/ctags is supported, Exuberant Ctags is not guaranteed.

**Comment by BlueDrink9** [comment]
That should be explicitly stated in the readme

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/vista.vim/commit/62b8da904fb1396534b8daa2f70f1951de128ef0
