### ISSUE TITLE
Help - How does the vista.raw stuff work?

### ISSUE THREAD

**Issue by weilbith** [liuchengxu/vista.vim#277]
Hey,
first I like to thank you for this great plugin!
I already opened a PR to increase the feature completion support of the `nvim_lsp` provider. Now I also want to make sure that the highlighted tag in the Vista window updates continuously while moving in the buffer. Or more general highlight at all. ^^
So as I figured out this feature needs the `g:vista.raw` list which includes an entry for each Vista window tag with additional information (as I see for `ctags`). But because the `nvim_lsp` provider does not fill that list, it does not work. I tried to checkout how it works for the `coc` provider etc. But I still don't get the whole idea.  How is the relation between the buffer line and vista line (`vline`) established or determined? What properties are mandatory for which feature?
I would love to reate this list from the `data` response by `nvim_lsp`. But I'm missing information. Could you help?

**Comment by liuchengxu** [comment]
The magic is this line https://github.com/liuchengxu/vista.vim/pull/272/files#diff-6601fa90639099f69b3fe9622e802d0eR22, which adds `vlnum` field into the original tag info. `vlnum` indicates the line number of current tag in the vista window. `:echo g:vista.raw`, then you can understand it better.

**Comment by weilbith** [comment]
Yeah I saw that already... ^^

Okay, so let's make this more short. Is the reason that this hasn't been implemented for `nvim_lsp` just that nobody did it so far or because it is not easily/at all possible? If it is possible and no contributer with better code structure understanding than myself has time to work on it, I'm willed to dig into it and invest the time.

**Comment by liuchengxu** [comment]
I personally use ctags and coc only, that's the main reason I believe :(. Try to inject the `vlnum` info when renderering the content for `nvim_lsp` `vista#renderer#kind#Render()`, the code is a mess, feel free to refactor it as much as possible.
