### ISSUE TITLE
Golang friendly configuration guide?

### ISSUE THREAD

**Issue by ciehanski** [liuchengxu/vista.vim#282]
**Is your feature request related to a problem? Please describe.**
Seems like I am having issues of how to configure vista.vim with Golang and more specifically `gotags.` I am a recent convert from Tagbar, which was working okay.

**Describe the solution you'd like**
I am hoping other users who may have gotten vista.vim and Golang to play nicely together to share their vista configurations to properly generate tags for Golang. 

**Describe alternatives you've considered**
Using Tagbar in the meantime until I find a working configuration.

**Additional context**
[This](https://imgur.com/a/TOQKacr) is currently what vista.vim is displaying when running :Vista or :Vista ctags with an open *.go file.

**Comment by liuchengxu** [comment]
The picture you posted is not opening a go file, but `init.vim`.

Using ctags without any extra settings.

<img width="436" alt="截屏2020-05-03 上午8 34 13" src="https://user-images.githubusercontent.com/8850248/80895561-e17cb780-8d18-11ea-9f7f-ff9d19bc4cd1.png">

**Comment by ciehanski** [comment]
My apologies, I grabbed a prior screenshot that was incorrect. However, the same issue also applies to my *.go files and really any files at all. I have ctags installed properly and all custom configurations of vista turned off so I am unsure of what the issue could be. [Here](https://imgur.com/a/PVh3qiB) is the proper screenshot I meant to post.

**Comment by liuchengxu** [comment]
Ensure your ctags works as expected in the command line, otherwise it's an issue of your own ctags.

**Comment by ciehanski** [comment]
I had to uninstall `universal-ctags` via brew and reinstall with the `--with-jansson` like you listed in your documentation. Sorry for wasting your time!
