### ISSUE TITLE
Introduce a new variable to change the default ctags command

### ISSUE THREAD

**Issue by derekschrock** [liuchengxu/vista.vim#286]
**Is your feature request related to a problem? Please describe.**
On systems like FreeBSD that [installs universal-ctags](https://github.com/freebsd/freebsd-ports/blob/master/devel/universal-ctags/Makefile#L53) as `uctags` or not "ctags" you can't set the ctags command.   FreeBSD already has `ctags` as part of the base system.  So init. attempts to use vistia will fail.

**Describe the solution you'd like**
When `g:vista_default_executive` is set to `ctags` introduce a new variable that can set the command to something other than `ctags`.  If the new variable is unset the default `ctags` value will be used.

**Describe alternatives you've considered**
- Use `vista_ctags_cmd[...]` for all `a:filetypes`?  I don't believe this is a good idea.
- symlink ctags -> uctags in a dir (`~/bin`) from the `PATH` env.  However, any attempt to use the base system ctags can be cumbersome.

**Comment by liuchengxu** [comment]
How about symlinking the base ctags -> base-ctags and the univeral-ctags -> ctags?

**Comment by derekschrock** [comment]
On Wed, May 13, 2020 at 09:17:01PM EDT, Liu-Cheng Xu wrote:
>    How about symlinking the base ctags -> base-ctags and the univeral-ctags
>    -> ctags?
> 

Possible but I don't know what else might be depending on ctags in PATH
to be real ctags.

**Comment by derekschrock** [comment]
Turns out this does already exist: [g:vista_ctags_executable](https://github.com/liuchengxu/vista.vim/blob/master/doc/vista.txt#L332). Found it this morning while trying to write a patch.
