### ISSUE TITLE
When opening an empty buffer Vista prints "garbage"

### ISSUE THREAD

**Issue by binarypie** [liuchengxu/vista.vim#298]
I have the following vista options set
```
" Vista
map <Leader>v :Vista!!<CR>
let g:vista_default_executive = 'ctags'
let g:vista_fzf_preview = ['right:50%']
let g:vista#renderer#enable_icon = 1
let g:vista_executive_for = {
  \ 'dart': 'vim_lsc',
  \ 'go': 'vim_lsc',
  \ 'javascript': 'vim_lsc',
  \ 'markdown': 'vim_lsc'
  \ }
```

When opening an empty buffer it appears Vista will print "random garbage" into the buffer as removing the plugin removes this issue.
` 1 R^[[>1;4000;15c^[]10;rgb:ebeb/dbdb/b2b2^[\^[]11;rgb:2828/2828/2828^[\`

**Comment by liuchengxu** [comment]
You might want to check it's a same issue with #297.

**Comment by binarypie** [comment]
@liuchengxu I don't use Fish just ZSH but let me switch terminals in case kitty is doing something weird.

**Comment by binarypie** [comment]
Confirmed: Issue is resolved when opening in gnome terminal instead of kitty.
Thank you!
