### ISSUE TITLE
Show the tags in a nested structure

### ISSUE THREAD

**Issue by idanarye** [liuchengxu/vista.vim#30]
Vista lists the tags grouped by type, unlike Tagbar that groups them by structure and nests them. Consider the following screenshot, with the code on the left, Tagbar in the middle, and Vista on the right:

![image](https://user-images.githubusercontent.com/1149255/55039475-f4f52380-502c-11e9-9ee9-fc31b762de74.png)

The Tagbar style gives you a clear overview of the code's structure, while Vista is quite a mess to look at (especially in my example, where different methods have the same name).

Even if the tags were just ordered by their location in the file instead of being grouped by tag type the result would be much nicer. Nesting by indentation is of course a nice bonus, and so is the parameter list (that can when there is overloading)

**Comment by liuchengxu** [comment]
This feature is blocked by #4 and will be resolved when it is fixed.

**Comment by liuchengxu** [comment]
@idanarye  You can the branch https://github.com/liuchengxu/vista.vim/tree/provide-default-renderer for now. I provide an option to render by the line number of tags, but the indentation feature is still missing.

`let g:vista_ctags_renderer = 'default' | Vista show`:

<img width="1680" alt="屏幕快照 2019-03-31 下午5 13 59" src="https://user-images.githubusercontent.com/8850248/55287720-427fe080-53df-11e9-8935-dea4dc49d2d5.png">

**Comment by liuchengxu** [comment]
@idanarye believe I have made some progress on this issue, at least for Python. It would be appreciated to test #58 if you have some time.

My approach is different to the one tagbar used, and I don't know whether it applies everywhere, since the semantics of hierarchy structures is not well defined actually, I can only implement this feature in a heuristic method.

<img width="1680" alt="屏幕快照 2019-04-17 上午7 43 45" src="https://user-images.githubusercontent.com/8850248/56251215-47ce7200-60e5-11e9-8ada-56423f0c385e.png">

<img width="1680" alt="屏幕快照 2019-04-17 上午7 49 15" src="https://user-images.githubusercontent.com/8850248/56251228-53ba3400-60e5-11e9-9051-c382ed0200a0.png">

**Comment by idanarye** [comment]
Still can't handle nested code that well:

![image](https://user-images.githubusercontent.com/1149255/56279294-8299cf80-6110-11e9-8869-1880c9f972af.png)

The code, if you want to test it, is:
```python
class Foo:
    class Bar:
        BAR = 12

        class Baz:
            pass

        class Qux:
            pass

    def qux(self):
        def thing1():
            pass

        if True:
            def thing2():
                pass
        else:
            def thing3():
                pass

        def thing4():
            pass
```

**Comment by liuchengxu** [comment]
Thanks for the test code, will look into it.

**Comment by liuchengxu** [comment]
@idanarye I have improved the algorithm, please try again, the overall nested structure looks right now. There are still some other glitches about the highlight of current tag, but just ignore it for now, I will fix it when the nested display is usable.

<img width="1680" alt="屏幕快照 2019-04-18 下午4 26 02" src="https://user-images.githubusercontent.com/8850248/56347433-d383f380-61f6-11e9-8df8-a85ad3ca2d81.png">

**Comment by idanarye** [comment]
Looks good now!

**Comment by liuchengxu** [comment]
@idanarye I have fixed the problem of highlight the nearby tag. I think it's nearly usable now!

![Kapture 2019-04-19 at 20 48 47](https://user-images.githubusercontent.com/8850248/56424902-a877cd80-62e4-11e9-866b-cbf660c36510.gif)

**Comment by idanarye** [comment]
Looking good!

With this, I'm going to start using Vista to replace not only tagbar but [TToC](https://github.com/tomtom/ttoc_vim) as well.

**Comment by liuchengxu** [comment]
I have finished all the features I wanted in #58. The nested display will be the default behavior.  I'm planning to merge #58 soon, for the problems won't be found until you really use it.
