### ISSUE TITLE
Symbols are not displaying correctly in .vue files

### ISSUE THREAD

**Issue by Steadyx** [liuchengxu/vista.vim#303]
**Describe the bug**
Vista doesn't seem to display all of the symbols for a .vue file, vista also appears to list the symbols incorrectly.

**Environment:**
- OS:  OSX - Catalina - 10.15.5
- Vim/Neovim version: 
     NVIM v0.4.3
     Build type: Release
- I'm using some LSP client:
    - Related Vim LSP client: coc-vetur
    - The Vim LSP client version: 1.1.10
    - Have you tried updated to the latest version of this LSP client: Yes

**Vista info**

```
    Current FileType: vue
Avaliable Executives: ['coc', 'ctags']
    Global Variables:
    let g:vista = {'get_tagline_under_cursor': function('4'), 'winnr': function('2'), 'source': {'fname': '/Users/<usr>/Desktop/vue-test/src/components/test.vue', 'bufnr': 3, 'get_winid': function('6'), 'winid': 1000, 'winnr': 1, 'extension': function('11'), 'line': function('9'), 'get_winnr': function('5'), 'filetype': function('7'), 'lines': function('8'), 'line_trimmed': function('10'), 'scope_seperator': function('12'), 'fpath': '/Users/<usr>/Desktop/vue-test/src/components/test.vue'}, 'winid': function('3')}
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'nvim_lsp', 'vim_lsc', 'vim_lsp']
    let g:vista#extensions = ['markdown', 'rst']
    let g:vista#finders = ['fzf', 'skim']
    let g:vista_blink = [2, 100]
    let g:vista_close_on_jump = 0
    let g:vista_cursor_delay = 400
    let g:vista_default_executive = 'coc'
    let g:vista_disable_statusline = 0
    let g:vista_echo_cursor = 1
    let g:vista_executive_for = {}
    let g:vista_find_absolute_nearest_method_or_function = 0
    let g:vista_find_nearest_method_or_function_delay = 300
    let g:vista_fold_toggle_icons = ['▼', '▶']
    let g:vista_icon_indent = ['└ ', '│ ']
    let g:vista_ignore_kinds = []
    let g:vista_no_mappings = 0
    let g:vista_sidebar_position = 'vertical botright'
    let g:vista_sidebar_width = 30
    let g:vista_stay_on_open = 1
    let g:vista_top_level_blink = [2, 100]
    let g:vista_update_on_text_changed = 0
    let g:vista_update_on_text_changed_delay = 500
```

**Steps to reproduce given the above info**

 Go into a vue project and use the command :Vista 

minimal vimrc (neccessary when this issue is about some Vim LSP client):

```vim
let g:coc_global_extensions = [
 \  'coc-vetur',
 \  'coc-html',
 \  'coc-snippets',
 \  'coc-pairs',
 \  'coc-rls',
 \  'coc-tsserver',
 \  'coc-eslint',
 \  'coc-prettier',
\ ]
```

1. Load a vue project in vim
2. Execute the vista command

**Expected behavior**
Opening a vue project and executing the :Vista command should display all of the symbols correctly including methods, lifecycle hooks and class names in style tags.

**Actual behavior**
Opening a vue project and executing the :Vista command does not list the symbols correctly
**Screenshot or gif** (if possible)
Here's a screenshot in vim using vista
<img width="1440" alt="Screenshot 2020-06-09 at 20 15 21" src="https://user-images.githubusercontent.com/13971238/84190178-6a141380-aa8e-11ea-9da6-f4f2969937df.png">

**Comment by liuchengxu** [comment]
Since you are using the coc executive, there is nothing vista can help with as vista essentially uses the API of coc.nvim `CocAction('documentSymbols')` to get these symbols. You may ask help at the related language server repo or coc.nvim.
