### ISSUE TITLE
Preserve alternate buffer

### ISSUE THREAD

**Issue by Neur1n** [liuchengxu/vista.vim#304]
**Is your feature request related to a problem? Please describe.**
When I open Vista with `:Vista!!` (using ctags), the alternate buffer changes to the Vista buffer. Then once the Vista buffer closed, the alternate buffer lost.

**Describe the solution you'd like**
Maybe using `keepalt` before opening the sidebar?

**Additional context**
I'm using the following configurations:
```vimscript
let g:vista_echo_cursor = 0
let g:vista_close_on_jump = 1
```

**Comment by Neur1n** [comment]
@liuchengxu Which one would you prefer if I make a PR:
1. always keep the original alternate buffer
2. using a flag to determine keeping the alternate buffer or not

**Comment by liuchengxu** [comment]
@Neur1n Honestly I'm never aware of the difference. Since you raised this issue, which is a better option for you? I'm all good with that.

**Comment by Neur1n** [comment]
Sorry, it seems I didn't make myself clear. I meant providing a variable, for example `g:vista_sidebar_keepalt`, for users to decide whether or not to keep the alternate buffer. Actually it is quite easy to achieve. Just add 'keepalt' into `sidebar.vim`:

#### Option 1
```vimscript
function! s:NewWindow() abort
  let open = g:vista_sidebar_position.' '.g:vista_sidebar_width.'new'
  silent execute 'keepalt '.open '__vista__'
  
  " Rest part of the original function.
endfunction
```

#### Option 2
```vimscript
function! s:NewWindow() abort
  let open = g:vista_sidebar_position.' '.g:vista_sidebar_width.'new'
  if get(g:, 'vista_sidebar_keepalt', 1)
    silent execute 'keepalt '.open '__vista__'
  else
    silent execute open '__vista__'
  endif

  " Rest part of the original function.
endfunction
```

It works for me, but I'm not sure if this conflicts with the other parts of this plugin.

**Comment by liuchengxu** [comment]
I'll choose option 2 then.
