### ISSUE TITLE
Floating window preview fails if the file path contains spaces

### ISSUE THREAD

**Issue by TonyWu20** [liuchengxu/vista.vim#307]
**Describe the bug**
编辑路径中含有空格的文件时，Vista finder里的fzf preview无法正常运作。

**Environment:**
- OS: macOS Catalina 10.15.5
- Vim/Neovim version:
NVIM v0.4.3
Build type: Release

- This plugin version: bfd70f620d30dc756d8ae57056b7a67a3fbbff22

- I'm using universal-ctags: 
    - Ctags version: 
Universal Ctags 0.0.0(f6c7064), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jun  4 2020, 14:48:47
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +case-insensitive-filenames, +packc

- I'm using some LSP client:
    - Related Vim LSP client: ale, coc
    - The Vim LSP client version: 
ALE:7265ceb6d050d1a4642741d248f11e4f2abd37e1
coc:d48afceae96412907ef89bc938d46017c9972e32
    - Have you tried updated to the latest version of this LSP client: Yes

**Vista info**

```
    Current FileType: 
Avaliable Executives: ['coc', 'ctags']
    Global Variables:
    let g:vista = {'get_tagline_under_cursor': function('15'), 'winnr': function('13'), 'raw_by_kind': {}, 'tree': {}, 'source': {'fpath': '', 'bufnr': 1, 'get_winid': function('17'), 'fname': '', 'winnr': 1, 'extension': function('22'), 'line': function('20'), 'get_winnr': function('16'), 'filetype': function('18'), 'lines': function('19'), 'winid': 1000, 'line_trimmed': function('21'), 'scope_seperator': function('23')}, 'with_scope': [], 'provider': 'ctags', 'without_scope': [], 'ctags_cmd': 'ctags --format=2 --excmd=pattern --fields=nksSaf --extras=+F --sort=no --append=no --extras=   --output-format=json --fields=-PF -f- /var/folders/2w/b7g8js7j09jgg3990zz2cr0m0000gn/T/c4cdbca5dbd6e4bf8d3305349eb560ab878f248ebe9fa1784bc4fa011c3eb103', 'winid': function('14'), 'functions': [], 'raw': [], 'kinds': []}
    let g:vista#executive#ctags#support_json_format = 1
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'nvim_lsp', 'vim_lsc', 'vim_lsp']
    let g:vista#extensions = ['markdown', 'rst']
    let g:vista#finders = ['fzf', 'skim']
    let g:vista#renderer#ctags = 'default'
    let g:vista#renderer#enable_icon = 1
    let g:vista#renderer#icons = {'subroutine': '羚', 'method': '', 'func': '', 'variables': '', 'namespace': '', 'field': '', 'interface': '', 'type': '', 'packages': '', 'property': '襁', 'implementation': '', 'default': '', 'augroup': 'פּ', 'macro': '', 'enumerator': '', 'const': '', 'macros': '', 'map': 'פּ', 'fields': '', 'functions': '', 'enum': '', 'function': '', 'target': '', 'typedef': '', 'variable': '', 'modules': '', 'constant': '', 'struct': '', 'types': '', 'module': '', 'typeParameter': '', 'package': '', 'class': '', 'member': '', 'var': '', 'union': '鬒'}
    let g:vista_blink = [2, 100]
    let g:vista_close_on_jump = 0
    let g:vista_cursor_delay = 400
    let g:vista_default_executive = 'ctags'
    let g:vista_disable_statusline = 0
    let g:vista_echo_cursor = 1
    let g:vista_executive_for = {}
    let g:vista_find_absolute_nearest_method_or_function = 0
    let g:vista_find_nearest_method_or_function_delay = 300
    let g:vista_fold_toggle_icons = ['▼', '▶']
    let g:vista_fzf_preview = ['right:50%']
    let g:vista_icon_indent = ['╰─▸ ', '├─▸ ']
    let g:vista_ignore_kinds = []
    let g:vista_no_mappings = 0
    let g:vista_sidebar_position = 'vertical botright'
    let g:vista_sidebar_width = 30
    let g:vista_stay_on_open = 1
    let g:vista_top_level_blink = [2, 100]
    let g:vista_update_on_text_changed = 0
    let g:vista_update_on_text_changed_delay = 500
```

**Steps to reproduce given the above info**

source file for reproduce the ctags issue:

minimal vimrc (neccessary when this issue is about some Vim LSP client):

```vim
set nocompatible
set runtimepath^=/path/to/vista.vim
syntax on
filetype plugin indent on
```

1. neovim中打开路径中含有空格的文件（如XXX/Library/Mobile Documents/com\~apple\~CloudDocs/XXX.py)
2. 设置Vista floating window与fzf.vim preview
3. :Vista finder
4. 预览窗口无法正确显示预览内容

**Expected behavior**
预览显示tag在文件中的位置

**Actual behavior**
显示了不完整的文件路径，在空格处中断

**Screenshot or gif** (if possible)
<img width="2560" alt="Screenshot 2020-06-18 at 3 48 26 PM" src="https://user-images.githubusercontent.com/45414421/84994277-091ac880-b17d-11ea-867b-fb2e7bb74884.png">

**Comment by TonyWu20** [comment]
PS: 同样的文件下，单独唤起fzf.vim的preview时是正常的。我不熟悉vim script，找不到vista对文件路径的处理放在哪里。

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/vista.vim/blob/c69f3f12a5ce6bdc99e6926c18dbe2b4583418d5/autoload/vista/finder.vim#L168-L175

#251 might be related, @dkarter . Currently I use vim-clap, so I actually don't how the fzf preview works in vista.vim now.
