### ISSUE TITLE
Display Private Methods in Java

### ISSUE THREAD

**Issue by jasontcole** [liuchengxu/vista.vim#312]
I see that vista supports "Show the visibility (public/private) of tags." but my private java methods and variables do not show.  Is there a way to display these private types that I'm not seeing?

![image](https://user-images.githubusercontent.com/62342797/85934175-22bebd00-b8ad-11ea-9670-4beea512a6ec.png)

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/vista.vim/wiki/faq#no-display-of-publicprivate-signs
