### ISSUE TITLE
使用vista-coc缺少最后一个函数

### ISSUE THREAD

**Issue by laccolith123** [liuchengxu/vista.vim#313]
coc使用ccls
cpp通过class::function()定义函数
![image](https://user-images.githubusercontent.com/19382631/86078454-c9c77280-bac0-11ea-8b49-37f2cbeb4d11.png)

![image](https://user-images.githubusercontent.com/19382631/86078312-6a696280-bac0-11ea-9497-ef30d9494716.png)

**Comment by liuchengxu** [comment]
You are comparing ctags and LSP, vista.vim merely uses the API from coc.nvim. Report to ccls if you think it's an issue of language server, report to coc.nvim if you think it's an issue of language client.

**Comment by howin98** [comment]
the same problem recur in golang with coc-go, i think it is an issue of coc
