### ISSUE TITLE
vista-ctags找不到类定义的函数

### ISSUE THREAD

**Issue by laccolith123** [liuchengxu/vista.vim#314]
通过class::function()定义函数，vista-ctags找不到函数
![image](https://user-images.githubusercontent.com/19382631/86078823-88839280-bac1-11ea-9ed1-4e0ef66f29c6.png)

![image](https://user-images.githubusercontent.com/19382631/86078684-35114480-bac1-11ea-8296-72e827d455cd.png)

**Comment by liuchengxu** [comment]
Essentially duplicate as #123, #211, etc. The current ctags renderer has a big design flaw and needs a complete overhaul, but I no longer work on this as I use the tree view feature rarely now. Someone needs to implement a new ctags renderer, tagbar is a good reference.

**Comment by liuchengxu** [comment]
Closing for #320
