### ISSUE TITLE
E117: Unknown function: vista#RunForNearestMethodOrFunction

### ISSUE THREAD

**Issue by D1mon** [liuchengxu/vista.vim#315]
I previously wrote about the error #247. I simply disabled and did not use the extension. And now I decided to try again, but the error remained. But this time I found the problem.
In the first option - an error (with Plug 'liuchengxu/vista.vim', { 'on': ['Vista'] }) 

```vim
Error detected while processing function <SNR>12_on_window_changed[22]..<SNR>12_init[6]..airl
ine#extensions#load:
line  109:
E117: Unknown function: airline#extensions#vista#init
Error detected while processing function <SNR>12_do_vim_enter:
line    3:
E117: Unknown function: vista#RunForNearestMethodOrFunction
```

init.vim config file:
```vim
call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'liuchengxu/vista.vim', { 'on': ['Vista'] }
" Plug 'liuchengxu/vista.vim'
call plug#end()
```
But not here: Plug 'liuchengxu/vista.vim' - works

nvim same version.
vista.vim - new version (0cbf100215f)

**Comment by liuchengxu** [comment]
`Plug 'liuchengxu/vista.vim', { 'on': ['Vista'] }` will lazy load this plugin, that's why this error happens. Refer to vim-plug for more information.
