### ISSUE TITLE
markdown文件tag开始显示不正常，前换窗口后就正常了

### ISSUE THREAD

**Issue by 66RING** [liuchengxu/vista.vim#317]
不知道这么描述，下面截图，我的配置如下

可能是个很小的bug，并不影响使用(只是需要多点操作)

```
noremap T :Vista!!<CR>
noremap <LEADER>v :silent! Vista finder<CR>
let g:vista_icon_indent = ["╰─▸ ", "├─▸ "]
let g:vista_default_executive = 'ctags'
let g:vista_fzf_preview = ['right:50%']
let g:vista#renderer#enable_icon = 1
let g:vista#renderer#icons = {
\   "function": "\uf794",
\   "variable": "\uf71b",
\  }
```

我应该没有使用lsp，因为:Vista nvim_lsp、vim_lsp...等都试过，都没反应，只有ctags有反应。

但是文档说
> " Note: this option only works the LSP executives, doesn't work for `:Vista ctags`.
> let g:vista_icon_indent = ["╰─▸ ", "├─▸ "]

那么我用ctags的话，是不是应该一直是"不正常"的状态，但是切换一下窗口就“正常”了，而且也工作正常。

刚打开的时候是很普通的vista ctags结构，对于markdown来说是乱序的。

![2020-07-07_16-50](https://user-images.githubusercontent.com/49358576/86755752-759a3080-c074-11ea-90c3-269cfcfae2f6.png)

但是切换了窗口就变成了下面的结构，而且是有序的
> " Note: this option only works the LSP executives, doesn't work for `:Vista ctags`.
> let g:vista_icon_indent = ["╰─▸ ", "├─▸ "]

![2020-07-07_16-50_1](https://user-images.githubusercontent.com/49358576/86756252-d7f33100-c074-11ea-9593-9cd847216cb6.png)
![2020-07-07_16-50_2](https://user-images.githubusercontent.com/49358576/86756290-dde91200-c074-11ea-83a3-6cd22aceec8e.png)

小小问题，打扰了。谢谢

**Comment by fgheng** [comment]
我与他同样的问题，只有重新启动vista才回出现排好顺序的列表
![image](https://user-images.githubusercontent.com/50551377/96338524-45c1e680-10c1-11eb-969e-a791f3f0214f.png)
一旦切回窗口，立刻变为这样了
![image](https://user-images.githubusercontent.com/50551377/96338533-53776c00-10c1-11eb-947f-6a34c4bc8ad8.png)

**Comment by 66RING** [comment]
@fgheng 上面的commit已经修复了我的问题，更新vista试试，我现在用最新的版本没能复现你的问题
