### ISSUE TITLE
Mac OS not very compatible with universal-ctags.

### ISSUE THREAD

**Issue by zququ** [liuchengxu/vista.vim#318]
Mac OS will install ctags by default, which can be resolved by installing the universal-ctags, however neovim will prefer to use the built-in ctags.
For taglist, I can make it by `let Tlist_Ctags_Cmd='/usr/local/bin/ctags'`. 
I want to know how can I solve this problem in vista.vim? Thank you!

**Comment by liuchengxu** [comment]
`:h g:vista_ctags_executable`.
