### ISSUE TITLE
大佬 可不可以加上neovim的悬浮窗支持 这样相信体验更好 毕竟不会出现画面推动代码编辑区的问题 美观是兴趣的原动力啊

### ISSUE THREAD

**Issue by huayue369** [liuchengxu/vista.vim#32]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by liuchengxu** [comment]
预览详情可以用悬浮窗，`:h vista_echo_strategy`. 常驻窗口我觉得没必要，只有开在下面才会有扰动窗口布局的情况，开在两侧不会有。
