### ISSUE TITLE
Do not open buffer in vista

### ISSUE THREAD

**Issue by fgheng** [liuchengxu/vista.vim#324]
**Is your feature request related to a problem? Please describe.**
Hello, I sometimes forget that my cursor is in  vista's window, so I often open a new buffer in vista's window.
if I open a buffer, I hope that vista can give a prompt that the buffer cannot be opened in this window when my cursor is in vista's window.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by liuchengxu** [comment]
Not sure there is a good way to acheive this, let me know if you have some good ideas.
