### ISSUE TITLE
Return to most recent buffer when closing view window

### ISSUE THREAD

**Issue by jdsutherland** [liuchengxu/vista.vim#327]
When the vista view window is closed, the cursor doesn't return back to the most recent buffer. I think the more useful and expected behavior would be to return to the previous buffer. I don't like leaving vista open so I usually just toggle for a peek and close but it's distracting to have to navigate back to the correct split. 

To reproduce, open 2 vsplits, move to leftmost split, open vista, close vista, and cursor will be in right split rather than left split.

**Comment by jdsutherland** [comment]
I just found `g:vista_stay_on_open = 0`. This works better for how I tend to use it. I still think it should return to the most recent buffer on close though.

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/vista.vim/blob/master/autoload/vista/sidebar.vim#L92-L95 The current strategy is jumping back to the previous window.

There is no clear definition of the most recent buffer here, especially when you have nerdtree, startify, etc, some people may prefer to skip these buffers. Let me know if you have some solution about this.

**Comment by jdsutherland** [comment]
Couldn't it be defined as the last split (the same as `<c-w><c-p>`)? I don't know Viml very well but shouldn't it be possible to make it return to the previous split when the vista buffer closes? That mapping works for me.

**Comment by liuchengxu** [comment]
That's what vista does right now. `wincmd p` is equivalent to `<c-w><c-p>`.

**Comment by jdsutherland** [comment]
If you open 2 vsplits and have the cursor in the leftmost split then toggle open/close Vista, the cursor will be in the rightmost split instead of the left split. 

I'm not sure if there is confusion around this scenario or you are getting different behavior than I get.

**Comment by liuchengxu** [comment]
There was indeed an issue about closing the sidebar, which has been fixed in the latest master.

And if you want to go back to the previous window, you have to use `:call vista#sidebar#Close()`, not a plain `:quit`, you can add a vista mapping for that.

**Comment by jdsutherland** [comment]
Looks like that took care of it. Thanks!

**Comment by ur4ltz** [comment]
This issue duplicate #132 
Year for close problem! Super!!
