### ISSUE TITLE
Function icon

### ISSUE THREAD

**Issue by p00f** [liuchengxu/vista.vim#328]
**Is your feature request related to a problem? Please describe.**
Current function icon is the fedora logo, when a separate function glyph exists

**Describe the solution you'd like**
 (f794)

**Describe alternatives you've considered**

**Additional context**

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/vista.vim/blob/master/autoload/vista/renderer.vim#L8-L10, it's already being used.
