### ISSUE TITLE
Group by class for c++

### ISSUE THREAD

**Issue by prehistoric-penguin** [liuchengxu/vista.vim#332]
**Is your feature request related to a problem? Please describe.**
The current layout is grouped by types, which is not easy to read, especially for the long class name and long function names

**Describe the solution you'd like**
I want something similar to visual studio's class view

![img](https://static.packt-cdn.com/products/9781849686709/graphics/6709EN_01_03.jpg)

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/vista.vim/wiki/faq#tree-view
