### ISSUE TITLE
Always missing the last method in c++ implementation file (.c, .cpp, .cc) with coc

### ISSUE THREAD

**Issue by eggeek** [liuchengxu/vista.vim#334]
**Describe the bug**

**Environment:**
- OS: Manjaro
- Vim/Neovim version: NVIM v0.5.0-632-gc219d3eec
- This plugin version: 7f97d30914daea5b542a90eed747d5bd00afbb19
- I'm using universal-ctags: 
    - Ctags version: Exuberant Ctags 5.8
- I'm using some LSP client:
    - Related Vim LSP client: coc
    - The Vim LSP client version: 15f1cb039b65e9a0655411b8fec51fe5f94ab607
    - Have you tried updated to the latest version of this LSP client: Yes

**Vista info**

```
    Current FileType: cpp
Avaliable Executives: ['coc', 'ctags']
    Global Variables:
    let g:vista = {'get_tagline_under_cursor': function('6'), 'winnr': function('4'), 'source': {'fname': 'test.h', 'bufnr': 2, 'get_winid': function('8'), 'winid': 1000, 'wi
nnr': 1, 'extension': function('13'), 'line': function('11'), 'get_winnr': function('7'), 'filetype': function('9'), 'lines': function('10'), 'line_trimmed': function('12'),
'scope_seperator': function('14'), 'fpath': '/home/eggeek/workspace/test/test.h'}, 'winid': function('5'), 'tmps': []}
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'nvim_lsp', 'vim_lsc', 'vim_lsp']
    let g:vista#extensions = ['markdown', 'rst']
    let g:vista#finders = ['clap', 'fzf', 'skim']
    let g:vista#renderer#ctags = 'line'
    let g:vista#renderer#enable_icon = 1
    let g:vista_blink = [2, 100]
    let g:vista_close_on_jump = 0
    let g:vista_cursor_delay = 100
    let g:vista_default_executive = 'ctags'
    let g:vista_disable_statusline = 0
    let g:vista_echo_cursor = 1
    let g:vista_echo_cursor_strategy = 'floating_win'
    let g:vista_executive_for = {'cc': 'coc', 'c': 'coc', 'cpp': 'coc'}
    let g:vista_find_absolute_nearest_method_or_function = 0
    let g:vista_find_nearest_method_or_function_delay = 300
    let g:vista_fold_toggle_icons = ['▼', '▶']
    let g:vista_fzf_preview = ['right:50%']
    let g:vista_icon_indent = ['└ ', '│ ']
    let g:vista_ignore_kinds = []
    let g:vista_no_mappings = 0
    let g:vista_sidebar_position = 'vertical botright'
    let g:vista_sidebar_width = 30
    let g:vista_stay_on_open = 0
    let g:vista_top_level_blink = [2, 100]
    let g:vista_update_on_text_changed = 0
    let g:vista_update_on_text_changed_delay = 500
```

**Steps to reproduce given the above info**

source file for reproduce the ctags issue:

* `test.h`
```c++
class C {
  public:
    C();
    ~C();
  void func1();
  void func2();
  void func3();
};
```

* `test.cc`
```c++
#include "test.h"

void C::func1() { int x = 1; }
void C::func2() { int x = 1; }
void C::func3() { int x = 1; }
```
minimal vimrc (neccessary when this issue is about some Vim LSP client):

```vim
set nocompatible
set runtimepath^=/home/eggeek/.local/share/nvim/plugged/vista.vim
set runtimepath^=/home/eggeek/.local/share/nvim/plugged/coc.nvim
let g:vista_echo_cursor_strategy = "floating_win"
let g:vista_stay_on_open = 0
let g:vista_cursor_delay = 100
let g:vista_fzf_preview = ['right:50%']
let g:vista#renderer#enable_icon = 1
let g:vista#renderer#ctags = "line"
let g:vista_disable_statusline = 0
let g:vista_executive_for = {
      \ 'cpp': 'coc',
      \ 'c'  : 'coc',
      \ 'cc' : 'coc',
      \ }

syntax on
filetype plugin indent on
```

**Expected behavior**
Show `func3`

**Actual behavior**
`func3` missing

**Screenshot or gif** (if possible)

[![asciicast](https://asciinema.org/a/bwTkiQhBb7O5HCV8DJdgHDcOu.svg)](https://asciinema.org/a/bwTkiQhBb7O5HCV8DJdgHDcOu)

**Comment by fky2015** [comment]
Same with `*.go` here.

**Comment by howin98** [comment]
same too

**Comment by liuchengxu** [comment]
vista.vim uses the API of coc.nvim, and from the feedback of the author of coc.nvim, the culprit is probably your language server, see https://github.com/neoclide/coc.nvim/issues/2609. So there is nothing that can be done in this plugin.

**Comment by derekschrock** [comment]
This is an issue with the plugin.  coc is passing the data, vista has the data, but it appears to just skip the last element due to the idx+1 stuff going on here:

https://github.com/liuchengxu/vista.vim/blob/6b65ad1df80b3d0709d010bf2b7fd5ddd7a22678/autoload/vista/renderer/hir/lsp.vim#L29

**Comment by derekschrock** [comment]
@liuchengxu Can this be reopened or should a new issue be filed?

**Comment by liuchengxu** [comment]
The fix looks reasonable, can you send a PR for that? @derekschrock
