### ISSUE TITLE
Colors aren't adjustable and look off with nord theme

### ISSUE THREAD

**Issue by Folling** [liuchengxu/vista.vim#336]
**Describe the bug**
I setup Vista just now, and it seems to be using the wrong colours of the palette.

**Environment:**
- OS: 5.8.5-arch1-1
- Vim/Neovim version: 
NVIM v0.4.4
Build type: Release
This plugin version: Pulled freshly via vim-plug
- I'm using universal-ctags: Yes
    - Ctags version: Universal Ctags 0.0.0(a3c87ab5)
- I'm using some LSP client: Yes
    - Related Vim LSP client: coc
    - The Vim LSP client version: 0.0.78-bdd9a9e140
    - Have you tried updated to the latest version of this LSP client: No - I doubt it's related (I should be on latest though)

**Vista info**
I'll add this if it's required afterwards, I presume it won't be necessary, since this is either an issue on my end, or with vista's colour decisions. 

**Steps to reproduce given the above info**
1. Download [kitty](https://sw.kovidgoyal.net/kitty/index.html)
2. Setup the nord theme manually (no pre-made version available, all you need to do is replace the colours in the kitty config with the ones from the [nord palette](https://www.nordtheme.com/docs/colors-and-palettes).
I've used this as a baseline: <https://gist.github.com/marcusramberg/64010234c95a93d953e8c79fdaf94192>
3. Open a c++ file
4. ???
5. Profit

**Expected behaviour**
I'd expect vista to use the colours as specified for my colour palette properly. Ideally it would be configurable.
The parent-title looks fine, though the children would probably be better off using a lighter colour. Additionally, the highlighted text-colour is invalid.

**Actual behaviour**
See below

**Screenshot or GIF** (if possible)
Here's a screenshot of the Vista preview:
![image](https://user-images.githubusercontent.com/23152870/91841779-38f14c80-ec53-11ea-95a1-7100981c30b4.png)
Especially the selected text is almost unreadable.
For comparison, here's a screenshot of some normal cpp file:
![image](https://user-images.githubusercontent.com/23152870/91840832-9daba780-ec51-11ea-85ae-ac31cbb7fae5.png)
As you can see, the selection is a lot more readable.

I apologise if I just overlooked something simple. I'm not that great with terminals or vim in general. I've checked the entirety of `:help vista-options` and didn't find anything to adjust colours. I've also looked online to see if it's possible to adjust the colours for just one vim window, but wasn't successful. Thank you very much for the extension though, it's exactly what I've been looking for!

**Comment by liuchengxu** [comment]
The highlights in vista are mostly linked to your colorscheme's highlight group, see https://github.com/liuchengxu/vista.vim/blob/master/syntax/vista.vim, so it's not problem of vista. You can change that easily if you prefer another highlight group, ref `:h :hi-default`.
