### ISSUE TITLE
Open sidebar doesn't cycle through executives

### ISSUE THREAD

**Issue by smhc** [liuchengxu/vista.vim#34]
With a default executive of "vim-lsp" there is no cycle to "ctags" executive when opening the sidebar with ":Vista". It does perform this cycling correctly when using ":Vista finder".

This was identified under https://github.com/liuchengxu/vista.vim/pull/33

**Comment by liuchengxu** [comment]
Thanks for raising this. For `:Vista finder`, vista.vim choose to run the executive synchronously, if the current one returns nothing or doesn't exist, then try the other alternatives. But for `:Vista`, the current strategy is to run asynchronously when invoked, so I don't know if it's easy to fallback to others in this cause. Do you think it makes more sense to run in sync way for `:Vista`?

**Comment by liuchengxu** [comment]
Could you give a concrete example for the option you propose? How the flow is?

**Comment by smhc** [comment]
Sure:

let g:vista_default_executive = 'ctags'
let g:vista_filetype_executive = {
\ 'cpp': 'vim-lsp'
\ 'php': 'vim-lsp'
}

Now when I edit a 'cpp' (C/C++) file or a php file Vista will use vim-lsp for symbols.
Any other file I edit (e.g perl, xml, shell, typescript etc) will use ctags.

Generally people will install only a small set of LSP servers for files they work on most.  LSP servers need to be explicitly installed per filetype, unlike ctags which supports many file types. Thus it seems reasonable for these to be explicitly listed by the user as they are added.

This proposal is fully backwards compatible, it is just a fairly small (but useful) enhancement on the current behaviour.

**Comment by liuchengxu** [comment]
Can you take a look at https://github.com/liuchengxu/vista.vim/commit/469611261760a5fd615fc649ba44381cd28cbe9e. I add two options:

```vim
" g:vista_{&filetype}_executive = 'vim_lsp'
let g:vista_cpp_executive = 'vim_lsp'

let g:vista_executive_for = {'cpp': 'vim_lsp'}
```

Either one is set vista.vim will use that instead of the default executive.

**Comment by smhc** [comment]
I think that would work fine.
However personally I'd only have the one method to configure it. Having multiple has the additional complexity of precedence and documentation.

- The 'map' configuration method is probably more traditional for users to configure.
- The 'vista_{&filetype}_executive' method might be easier for LSP plugin authors to set if they wish to automatically enable it for the user.

I'd probably go with the 'map' method, but it is up to you.
