### ISSUE TITLE
Key not present in Dictionary 

### ISSUE THREAD

**Issue by rmGFW** [liuchengxu/vista.vim#340]
**Describe the bug**

open json file then come out such  error
Error detected while processing function <SNR>152_on_exit[11]..<SNR>152_ExtractLinewise[2]..vista#parser#ctags#FromExtendedRaw[36]..<SNR>194_LoadData:
line   15:
E716: Key not present in Dictionary: line, 'text': get(line, 'name', '') }

**Environment:**
- OS: 
macos 
- Vim/Neovim version: 
NVIM v0.5.0-nightly-5-g5581ac8
- This plugin version: 
7f97d30914daea5b542a90eed747d5bd00afbb19
- I'm using universal-ctags: 
    - Ctags version: 
- I'm using some LSP client:
coc-json
    - Related Vim LSP client: 
    - The Vim LSP client version:
    - Have you tried updated to the latest version of this LSP client: Yes/No

**Vista info**

```
```

**Steps to reproduce given the above info**

source file for reproduce the ctags issue:

minimal vimrc (neccessary when this issue is about some Vim LSP client):

```vim
set nocompatible
set runtimepath^=/path/to/vista.vim
syntax on
filetype plugin indent on
```

1.
2.
3.
4.

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshot or gif** (if possible)

**Comment by liuchengxu** [comment]
You can add this debugging statement:

```diff
diff --git a/autoload/vista/parser/ctags.vim b/autoload/vista/parser/ctags.vim
index 67a8448..d6fd6e0 100644
--- a/autoload/vista/parser/ctags.vim
+++ b/autoload/vista/parser/ctags.vim
@@ -4,6 +4,7 @@

 function! s:LoadData(container, line) abort
   let line = a:line
+  call vista#Debug('Loading data:', line)

   let kind = line.kind

```
and enable the logging feature to help what's going on here:

```vim
  " Add this in your vimrc
  let g:vista_log_file = expand('~/vista.log') 
```
