### ISSUE TITLE
最新版与lightline的插件有冲突

### ISSUE THREAD

**Issue by applejwjcat** [liuchengxu/vista.vim#345]
**Describe the bug**
每次执行Vista时，最下方的命令行区域就会上升一行，所以我多次执行以后就变成了这样
<img width="1440" alt="截屏2020-09-28 下午6 13 59" src="https://user-images.githubusercontent.com/45581427/94420464-c6727e80-01b6-11eb-9187-7f7abbc2dfed.png">

并且，当我关闭了Vista时，最下方的函数栏并没有关掉，大概是这个样子：
<img width="1440" alt="截屏2020-09-28 下午6 14 12" src="https://user-images.githubusercontent.com/45581427/94420913-65977600-01b7-11eb-9549-89ea04dbb8b5.png">
能不能设置一个选项，将这个函数栏关掉。
我是用作者推荐的lightline配置实验的，所以我觉得这应该是个bug。
我很喜欢这个开源软件，也希望它能变的更好。加油，作者大大！

**Environment:**
- OS: MacOS
- Vim/Neovim version: 0.4.4
- This plugin version: 9c9adf16db3445005181751f0d3db143d58fe24d
- I'm using universal-ctags: yes
    - Ctags version: Universal Ctags 0.0.0(86bdb84), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Sep 27 2020, 16:43:54
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +case-insensitive-filenames, +packcc
- I'm using some LSP client:
    - Related Vim LSP client: coc
    - The Vim LSP client version:newest
    - Have you tried updated to the latest version of this LSP client: Yes

**Vista info**

```
```

**Steps to reproduce given the above info**

source file for reproduce the ctags issue:

minimal vimrc (neccessary when this issue is about some Vim LSP client):

```vim
set nocompatible
set runtimepath^=/path/to/vista.vim
syntax on
filetype plugin indent on
```

1.
2.
3.
4.

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshot or gif** (if possible)

**Comment by liuchengxu** [comment]
Have you tried to reproduce with a minimal vimrc? What's the last working commit if you think it's a vista regression?

**Comment by applejwjcat** [comment]
yes, I used the mini vim, only installed vista and lightline plugins, and use the configuration in the vista's Readme, I think it is a bug

**Comment by applejwjcat** [comment]
And I test it in my arch system, it also has the bug. I'm confirmed that it did't happen before!!

**Comment by liuchengxu** [comment]
Please post your minimal vimrc and exact steps to reproduce, also please help spot the last working commit. I can take a look if you provide these info, otherwise I may not spend time on it as I personally don't use lightline.

**Comment by applejwjcat** [comment]
I'am sorry, I add some configuration that I didn't know, there is no bug! thanks for your reply! I'm sorry to bother you.
