### ISSUE TITLE
question: weird symbol in side bar

### ISSUE THREAD

**Issue by ssh352** [liuchengxu/vista.vim#350]
It is the first time I tried vista. I've launched the side bar via :Vista coc. However the weird characters appear in the side bar. I use iterm2 and latest NeoVim. Thank you.
 
<img width="2552" alt="Screen Shot 2020-10-31 at 5 59 04 PM" src="https://user-images.githubusercontent.com/41779116/97776425-cb09c880-1ba2-11eb-9d9b-20b7f79a56d3.png">

**Comment by liuchengxu** [comment]
`let g:vista#renderer#enable_icon = 0`.
