### ISSUE TITLE
search content in dir?

### ISSUE THREAD

**Issue by zdmgmail** [liuchengxu/vista.vim#351]
How can I use `vista` search dir and show all symbols,tags?  all may be add this feture?

**Comment by zdmgmail** [comment]
` :silent! Vista finder coc` hope this can search dir

**Comment by liuchengxu** [comment]
`:Vista finder! ctags` can search the tags recursively.

LSP has a concept of workspace symbols, which is similiar to search the project tags, but it's unimplemented yet, see #302.
