### ISSUE TITLE
How to close vista automatically when vista left alone

### ISSUE THREAD

**Issue by Yihen** [liuchengxu/vista.vim#358]
which param should be set in vista.vim config  so that vista can closed automatically when vista left alone?

**Comment by liuchengxu** [comment]
No, but you can add the following hook to your vimrc similiar to nerdtree:

```vim
autocmd bufenter * if (winnr("$") == 1 && &filetype =~# 'vista') | q | endif
```

**Comment by Yihen** [comment]
@liuchengxu  Thanks for your good suggestion. It works.
