### ISSUE TITLE
vista window auto scroll to center the cursor

### ISSUE THREAD

**Issue by jieteki** [liuchengxu/vista.vim#368]
When jump one tag from vista window, if the tag in vista window is not vertical centered, it's automaticly centered after a small delay. like someone is hitting `zz` to center that line.

Is there any way to stop that behaviour? that centering action make vista window moving its buffer position all the ways.

Thanks!

**Comment by liuchengxu** [comment]
Use `let g:vista_enable_centering_jump = 0`.
