### ISSUE TITLE
Hi, is there any way to configure the key map to open or close tag tree

### ISSUE THREAD

**Issue by alanding1989** [liuchengxu/vista.vim#37]
**Is your feature request related to a problem? Please describe.**
no, 

**Describe the solution you'd like**
I want to change the default FoldOrJump key map to another key, e,g o, no change just add is also ok. o is very close to touch...:)

**Describe alternatives you've considered**

**Additional context**

**Comment by liuchengxu** [comment]
```vim
autocmd FileType vista nnoremap <buffer> <silent> aa :<c-u>call vista#cursor#FoldOrJump()<CR>
```

**Comment by alanding1989** [comment]
> ```viml
> autocmd FileType vista nnoremap <buffer> <silent> aa :<c-u>call vista#cursor#FoldOrJump()<CR>
> ```

thank you for quickly reply, it works very well, I have already removed all the tagbar related plugins :+1:
