### ISSUE TITLE
Configure symbols to show

### ISSUE THREAD

**Issue by gennaro-tedesco** [liuchengxu/vista.vim#373]
**Is your feature request related to a problem? Please describe.**
Reduce the number of symbols shown in the sidebar (or in the fzf preview)

**Describe the solution you'd like**
It can be useful to introduce a configuration by which you can decide what symbols to show, along the lines of
```
let g:vista_symbols = {'class', 'function', 'variable', ...}
```

**Additional context**
The reason behind this request is to avoid Vista showing variables if not needed. Some file types consist mostly of variables declarations (think for instance of configuration files or properties) and in that case the Vista preview looks a little clunky.

**Related issue**
Perhaps [this other issue](https://github.com/liuchengxu/vista.vim/issues/266) is asking for the same, I could not however well understand.

**Comment by liuchengxu** [comment]
You can use `g:vista_ignore_kinds` to filter out the unwanted symbols, see https://github.com/liuchengxu/vista.vim/commit/a1422dc7157fa60ab104a70d3b528c6cf9dfe2a0.

**Comment by gennaro-tedesco** [comment]
Great, thank you!
