### ISSUE TITLE
Toggle Vista in current split

### ISSUE THREAD

**Issue by Chocrates** [liuchengxu/vista.vim#376]
👋 Hi All,

When I toggle Vista with two vertical splits, the vista panel always opens on the far right.
Is there a way to get Vista to open in the current split rather than the far right always?

**Comment by liuchengxu** [comment]
You can use `let g:vista_sidebar_open_cmd = '30vsplit'` now.

**Comment by Chocrates** [comment]
wow thank you so much @liuchengxu!
