### ISSUE TITLE
can not show icon when the GUI Font was set as Fira Code 

### ISSUE THREAD

**Issue by zombo** [liuchengxu/vista.vim#377]
Hi, Liu.

It may be not a bug. 

In my machine , Win 10 + Vim 8.2 , the icon show as   when I set GUI Font as Fira_Code_Retina or Fira_Code.

I don't know it is the problem of vista or font.

So, if it is nothing with vista, please close this comment.

thank you.

**Comment by liuchengxu** [comment]
You just need to use the nerdfont https://www.nerdfonts.com/font-downloads.
