### ISSUE TITLE
Add ability to silently trigger Vista functionalities

### ISSUE THREAD

**Issue by andersevenrud** [liuchengxu/vista.vim#39]
**Is your feature request related to a problem? Please describe.**

To display the current method/function your cursor is inside it is possible to add this to the vim configuration:

```vim
function! NearestMethodOrFunction() abort
  return get(b:, 'vista_nearest_method_or_function', '')
endfunction

set statusline+=%{NearestMethodOrFunction()}
```

However,  this does not work unless you've opened up Vista with `:Vista`. So if you want this functionality but don't want the actual Vista pane open, you have to perform an extra action.

**Describe the solution you'd like**

A way to "silently trigger" Vista functionalities like this without having to open & close the pane.

Provide a function that is callable when you open a buffer, or maybe a configuration option to automatically do this when a file is opened ?

**Describe alternatives you've considered**

Currently I'm just considering making a keybinding that opens and closes the pane.

**Additional context**

This issue was created in relation to https://github.com/neoclide/coc.nvim/issues/512#issuecomment-478116844

**Comment by liuchengxu** [comment]
Add the following line to your vimrc:

```vim
autocmd VimEnter * call vista#RunForNearestMethodOrFunction()
```

**Comment by andersevenrud** [comment]
Works like a charm. Thanks!

**Comment by lanox** [comment]
this the the git rev i am using 3c222b3ffbc78552e419c6e084cdbf88405794f2

**Comment by yanzhang0219** [comment]
Hello @liuchengxu ,

I found that it doesn't work if I set the `g:vista_default_executive` to `coc`. 

After setting it to `coc`, I opened a buffer and tried to run `:call vista#RunForNearestMethodOrFunction()` explicitly, it worked, however, it doesn't work automatically by setting `autocmd`.

Thank you very much.
