### ISSUE TITLE
Indent icon setting does not work for coc executive

### ISSUE THREAD

**Issue by yanzhang0219** [liuchengxu/vista.vim#393]
**Describe the bug**
`let g:vista_icon_indent` doesn't work for the `coc` executive. In README, I saw "this option only works the LSP executives", does is mean that it only works for the `vim_lsp` executive, or all LSP based executives? 

Thank you so much.

**Environment:**
- OS:  macOS
- Vim/Neovim version: 
   NVIM v0.5.0-dev+314b222c2
   Build type: Release
- This plugin version:  the latest
- I'm using some LSP client:
    - Related Vim LSP client:  coc
    - The Vim LSP client version:
    - Have you tried updated to the latest version of this LSP client: Yes

**Vista info**

    Current FileType: javascript
Avaliable Executives: ['coc', 'ctags']
    Global Variables:
    let g:vista = {'get_tagline_under_cursor': function('36'), 'winnr': function('34'), 'silent': v:false, 'source': {'fpath': '/Users/yanzhang/gitrepos/leetcode-cli/lib/cli.js', 'bufnr': 2, 'get_winid': function('38'), 'fname': 'lib/cli.js', 'winnr': 1, 'extension': function('43'), 'line': function('41'), 'get_winnr': function('37'), 'filetype': function('39'), 'lines': function('40'), 'winid': 1000, 'line_trimmed': function('42'), 'scope_seperator': function('44')}, 'provider': 'coc', 'winid': function('35'), 'tmps': []}
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'nvim_lsp', 'vim_lsc', 'vim_lsp']
    let g:vista#extensions = ['markdown', 'rst']
    let g:vista#finders = ['clap', 'fzf', 'skim']
    let g:vista#render#enable_icon = 1
    let g:vista_blink = [2, 100]
    let g:vista_close_on_fzf_select = 0
    let g:vista_close_on_jump = 0
    let g:vista_cursor_delay = 400
    let g:vista_default_executive = 'coc'
    let g:vista_disable_statusline = 0
    let g:vista_echo_cursor = 1
    let g:vista_enable_centering_jump = 1
    let g:vista_executive_for = {}
    let g:vista_find_absolute_nearest_method_or_function = 0
    let g:vista_find_nearest_method_or_function_delay = 300
    let g:vista_fold_toggle_icons = ['▼', '▶']
    let g:vista_fzf_preview = ['right:50%']
    let g:vista_icon_indent = ['╰─▸ ', '├─▸ ']
    let g:vista_ignore_kinds = []
    let g:vista_no_mappings = 0
    let g:vista_sidebar_position = 'vertical botright'
    let g:vista_sidebar_width = 50
    let g:vista_stay_on_open = 1
    let g:vista_top_level_blink = [2, 100]
    let g:vista_update_on_text_changed = 0
    let g:vista_update_on_text_changed_delay = 500

**Steps to reproduce given the above info**

Just open any file. I opened a `js` file for the testing.

Thank you.

**Comment by liuchengxu** [comment]
Sorry for the late reply, I have updated the comment about `g:vista_icon_indent`, which works only for the kind renderer.

**Comment by yanzhang0219** [comment]
Thank you. So it means that `g:vista_icon_indent` only works for the `ctags` and `g:vista#renderer#ctags` must be set to `kind`, right?

**Comment by liuchengxu** [comment]
Not really, both LSP and ctags can use the kind renderer.

Rocky Zhang ***@***.***> 于2021年3月31日周三 下午11:55写道：

**Comment by yanzhang0219** [comment]
How to set the kind renderer to LSP? `g:vista#renderer#lsp`? I cannot this in the help doc. Thanks.

**Comment by liuchengxu** [comment]
No such option, `coc` uses the tree renderer, the other LSP clients use the
kind renderer.

Rocky Zhang ***@***.***> 于2021年4月1日周四 上午8:46写道：

**Comment by yanzhang0219** [comment]
Okay. So what you mean is that if I use LSP clients other than coc, the default renderer is kind, right? Thanks.

**Comment by liuchengxu** [comment]
Yes, the other LSP clients only support the kind renderer right now.

**Comment by yanzhang0219** [comment]
I see. Thank your.
