### ISSUE TITLE
Boost project wise ctags finder via ptags

### ISSUE THREAD

**Issue by liuchengxu** [liuchengxu/vista.vim#40]
https://github.com/dalance/ptags

**Comment by djtal** [comment]
I've tried setting up `g: vista_ctags_executable ` to `ptags` but seem to have broke vista tag view. Don't know how to play with that.

**Comment by liuchengxu** [comment]
I think vista.vim is supposed to be able to work with ptags if only you provide the right ctags options for ptags, but I haven't looked into this feature yet. What's more, I rarely search tags project wise, so this is low priority. If you are willing to help, I suggest you first try in the command line, making sure the  ptags and ctags command gives you the same output.

**Comment by littletiny** [comment]
It seems to [gtags](https://www.gnu.org/software/global/) also break tag view.

**Comment by liuchengxu** [comment]
@littletiny I don't think gtags has an option to print the output to STDOUT. Hence gtags is not supported at the moment. vista.vim does not handle the process of tags file, all operations are in memory.
