### ISSUE TITLE
Support to set default finder for Vista finder

### ISSUE THREAD

**Issue by kuoe0** [liuchengxu/vista.vim#400]
**Is your feature request related to a problem? Please describe.**
I'd like to replace fzf with vim-clap and hope there could be a way to use vim-clap as the default finder. Then I could search tags by typing `:Vista finder` instead of `:Vista finder clap`.

**Describe the solution you'd like**
Adding a new variable for Vista to set default finder.

**Comment by liuchengxu** [comment]
It's feasible to define a new command in your vimrc for that:

```vim
command! VistaFinderClap Vista finder clap
```
