### ISSUE TITLE
notificaiton: change in JSON output format in Universal Ctags

### ISSUE THREAD

**Issue by masatake** [liuchengxu/vista.vim#404]
I'm a maintainer of Universal Ctags. We have a plan to change the output format of JSON output mode.

The order of "key: value" pair in the output entries will change. Here is the diff of the test case:

https://github.com/universal-ctags/ctags/pull/3067/commits/ff5e6cfbb46bfd34d197da36b2460e5bc3eebf8d#diff-6ebd67e4a4ab603e72132048ee71d08d4933a5338097fd1e77bc5b7c6d25315c

I expect vista.vim may read a tag entry as a JSON object and the order of pairs is hidden in the JSON object.
So the change introduces no impact on vista.vim. However, I had to modify the test case contributed from vista.vim.
So I report the change here.

Close this issue if the change is acceptable.

**Comment by liuchengxu** [comment]
Thanks @masatake , this change is fine to vista.vim as we don't rely on the order of items.

**Comment by masatake** [comment]
Thank you.
