### ISSUE TITLE
Overwrite `spell` option for preview windows

### ISSUE THREAD

**Issue by lygamac** [liuchengxu/vista.vim#424]
**Is your feature request related to a problem? Please describe.**
Preview of folds uses the same filetype as the document. However it doesn't inherit the options.

With `spell` enabled with the default `spell=en`, previewing any fold in a document will show `spellbad` for every other language despite having the correct `spell` set in the document. (For example, by adding `// vim:spelllang=es` or `// vim:spelllang=CJK` at the end of the document.)

**Describe the solution you'd like**
Add an option to inherit documents options (not only global options), or able to disable spell completely for the preview window.

**Describe alternatives you've considered**
`autocmd` with preview windows. However it didn't worked.

**Additional context**
![image](https://user-images.githubusercontent.com/49118209/162170376-f1b75b8d-b651-4a6f-b1a8-f1e1a2f74dff.png)

**Comment by liuchengxu** [comment]
I think it makes sense to disable the spell check completely in the preview window, now it does.
