### ISSUE TITLE
Add an option for disabling rendering the statusline of vista window for other statusline plugins

### ISSUE THREAD

**Issue by gbrlsnchs** [liuchengxu/vista.vim#43]
**Describe the bug**
When hovering a symbol in the side view while having `let g:vista_echo_cursor_strategy = 'floating_win'` in config, the Airline statusline enters in an infinite reset loop, overloading one of my CPU cores.

**Steps to reproduce**

1.
```viml
let g:vista_echo_cursor_strategy = 'floating_win'
```
2. `:Vista`
3. Hover any symbol

**Expected behavior**
No reset loop, normal Airline statusline.

**Actual behavior**
Statusline enters in a loop of setting and unsetting the Airline statusline.

**Environment:**
- OS: Debian GNU/Linux 9.7 (stretch)
- Vim/Neovim version: 
```
NVIM v0.4.0-430-g8698830cb
Build type: RelWithDebInfo
```

- This plugin version: 543453159841d84868c49c0c4e8771a1a3c00f15

**Comment by liuchengxu** [comment]
I don't see a problem with such a minimal vimrc:

```vim
set nocompatible

call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'liuchengxu/vista.vim'
call plug#end()

let g:vista_echo_cursor_strategy = 'floating_win'
```

**Comment by gbrlsnchs** [comment]
Thanks, it might be some Airline extension, I will investigate further, although I'll probably switch Airline for Lightline.

**Comment by liuchengxu** [comment]
Closing then, feel free to reopen if you find it's a problem of vista.vim.

**Comment by gbrlsnchs** [comment]
@liuchengxu I confirmed that it is caused by [enricobacis/vim-airline-clock](https://github.com/enricobacis/vim-airline-clock). Airline statusline is disabled by Vista.vim (is it?) and the clock keeps resetting the Airline statusline. Once it's reset, someone (maybe Vista.vim?) disables it again until the clock refreshes (I have set a 1 sec. interval).

**Comment by liuchengxu** [comment]
I don't think so. vista.vim always only renders the statusline of vista window and never touches the other windows' statusline.

**Comment by gbrlsnchs** [comment]
Sorry, I think I wasn't clear enough. I'm only talking about Vista.vim window's statusline. It doesn't affect other windows, in fact. Still, Vista.vim's statusline keeps resetting when the clock extension refreshes the statusline as it forces Airline and Vista.vim drops it immediately.

Since I'll drop the clock extension, it's not a really big deal but other users might have problems with it. Any reasons for Vista.vim setting its own statusline and hence disabling Airline? It causes a visual discrepancy for fancy statusline users.

**Comment by liuchengxu** [comment]
I see. vista.vim should provide an option for disabling the builtin statusline renderer.

**Comment by liuchengxu** [comment]
Now the statusline renderer in vista.vim is disabled by default if have airline or lightline plugins installed. Or you can set it explicitly:

```vim
let g:vista_disable_statusline = 1
```

**Comment by gbrlsnchs** [comment]
Cool. Thank you!
