### ISSUE TITLE
Potential bug in `Run()` of `nvim_lsp.vim`

### ISSUE THREAD

**Issue by lizhemingi** [liuchengxu/vista.vim#438]
**Describe the bug**
From second time run `Vista finder nvim_lsp` in a new file will give the stale output which is the result of last file.

**Environment:**
- OS: Ubuntu 18.04
- Vim/Neovim version: NVIM v0.8.0-dev+105-ge5f6f2096
- This plugin version: f9c8c8ad4135346a945e1ebfb00b723976d92dfc
- I'm using some LSP client:
    - Related Vim LSP client: nvim_lsp

**Steps to reproduce given the above info**

1. open a new code file let's say `a.rs`, and run `Vista finder nvim_lsp`, this will give the right output.
2. open another code file let's say `b.rs`, and run `Vista finder nvim_lsp`, this will give the output same with `a.rs`, and it's not the correct output of `b.rs`.
3. keep on `b.rs` and run another time `Vista finder nvim_lsp`, this time will give the correct output of `b.rs`.
4. after first file, every new file will give the stale output of first run `Vista finder nvim_lsp` and second run is correct.

**Expected behavior**
Every run of `Vista finder nvim_lsp` will give the right output.

**Screenshot or gif** (if possible)
Run on https://github.com/liuchengxu/vim-clap
1. open `crates/matcher/src/substring.rs` and run `Vista finder nvim_lsp`
![image](https://user-images.githubusercontent.com/9639449/189565160-29d6424e-2efc-4f17-9f4c-ae3c549b34c3.png)
2. open `crates/matcher/src/mod.rs` and run `Vista finder nvim_lsp`
![image](https://user-images.githubusercontent.com/9639449/189565243-32349dc5-7d66-4527-977e-588eb2af054f.png)
3. keep on `crates/matcher/src/mod.rs` and run another time `Vista finder nvim_lsp`
![image](https://user-images.githubusercontent.com/9639449/189565397-43aaa3fa-f5d0-493d-9530-5f8a16237a1e.png)

**Potential root cause**
1. Every time a new file is opened and run `Vista finder nvim_lsp`, cache will be empty so a `vista#executive#nvim_lsp#Run` and then `s:Run` will be call. 
2. I think it's designed to call `s:RunAsync()` and wait for at least the data has been written or we can say `vista#executive#nvim_lsp#SetData` has been call.
3. But **`g:vista_executive_nvim_lsp_fetching` is not reset to `true` in `s:Run` before `call s:RunAsync()`**, so from second time we call `s:Run`, it will not be blocked to wait for `s:RunAsync` finish, so the `s:data` in `nvim_lsp.vim` will be stale.

**If you agree with the potential bug I found, I can send a pr to fix it**.  Looking forward to your response.  Thank you.

**Comment by lizhemingi** [comment]
@liuchengxu Hi, could you please take a look on this issue ?

**Comment by liuchengxu** [comment]
I'm not actively using nvim_lsp, but it looks reasonable to me with a quick look, feel free to send a PR.
