### ISSUE TITLE
问题反馈 拜托了

### ISSUE THREAD

**Issue by huayue369** [liuchengxu/vista.vim#45]
vista开启悬浮窗支持后，只要把光标移动到标签之上，触发悬浮窗就会不断的出现该状况。弹出这两个映射命令。
![Untitled](https://user-images.githubusercontent.com/32536764/55376971-8a207c80-5545-11e9-83a8-b3dab0ce1c5a.gif)

这是fzf调用rg的映射
<img width="679" alt="屏幕快照 2019-04-02 下午12 46 43" src="https://user-images.githubusercontent.com/32536764/55376942-652c0980-5545-11e9-8d1e-007774b990b1.png">
还有
<img width="757" alt="屏幕快照 2019-04-02 下午12 45 55" src="https://user-images.githubusercontent.com/32536764/55376952-7543e900-5545-11e9-8307-1736352c9004.png">
请问这是什么原因

**Comment by liuchengxu** [comment]
无法复现，是你自己配置的问题。

另外：

1. issue 可以 reopen, 同一个问题不用开两个 issue。
2. 报 issue 要将必要信息的描述清楚，至少应该填好 issue template.

**Comment by huayue369** [comment]
哦哦 谢谢
