### ISSUE TITLE
Unsupported kind: 'w' for --go-kinds option

### ISSUE THREAD

**Issue by pacmanzou** [liuchengxu/vista.vim#461]
![image](https://github.com/liuchengxu/vista.vim/assets/56422464/272d2aff-e730-426f-87ad-3b10e25bd8cb)
你好,ctags并没有w对于go,是否可以修改它在vista.vim里?

然后另一个问题是禁止icon的这个命令在lua配置(lazy.nvim)里面并不生效,在vim-plug里面是正常的,这是否是我的写法问题?如下图
![image](https://github.com/liuchengxu/vista.vim/assets/56422464/1b4285e6-2416-4e44-adc9-38c76170a4b6)

**Comment by pacmanzou** [comment]
vim.cmd("let g:vista#renderer#enable_icon = 0"),这种写法可以我知道

**Comment by zetatez** [comment]
pls try:

```lua
vim.g['vista#renderer#enable_icon'] = 0
vim.g.vista_executive_for = {
  go = 'nvim_lsp',
}
```

**Comment by pacmanzou** [comment]
> Please try
> 
> ```lua
> vim.g['vista#renderer#enable_icon'] = 0
> vim.g.vista_executive_for = {
>   go = 'nvim_lsp',
> }
> ```
> 
> or, you can clone the repo, and change the file `autoload/vista/types/uctags/go.vim` to fit the ctags supported options.

好的,谢谢,命令正常执行了.我其实是想维护者去更新这个`ctags --go-kinds`问题,我知道在go.vim删除含'w'参数的一行可以像我期待的去运行,但又不想提pr(问题是我本地的关系就尴尬了).

**Comment by pacmanzou** [comment]
现在使用coc去代替ctags,关闭issue了
