### ISSUE TITLE
Tree view for ctags

### ISSUE THREAD

**Issue by jiangyinzuo** [liuchengxu/vista.vim#462]
**Is your feature request related to a problem? Please describe.**

The [tagbar.vim](https://github.com/preservim/tagbar) plugin supports parsing ctags and provides a tree view functionality.

<img width="953" alt="image" src="https://github.com/liuchengxu/vista.vim/assets/40995042/088fffa0-2f85-4be8-adc6-ea74a86ef07a">

In vista.vim, we can also obtain a tree view using LSP (such as `:Vista coc`).

<img width="938" alt="image" src="https://github.com/liuchengxu/vista.vim/assets/40995042/d4485fb6-9dba-4103-995f-9a21597c8904">

Indeed,  `:Vista ctags` provides a flat view rather than a tree view.
<img width="943" alt="image" src="https://github.com/liuchengxu/vista.vim/assets/40995042/e6e5f0c9-de15-47e8-8438-bfdf88159b9e">

So is it possible to support tree view for `:Vista ctags`？

**Describe the solution you'd like**

Perhaps we can utilize the fields in the ctags file format to obtain the tree view.
```
a	foo.cpp	/^	int a = 1;$/;"	v	namespace:foo::bar::baz1::baz2	typeref:typename:int
bar	foo.cpp	/^namespace foo::bar {$/;"	n	namespace:foo	file:
bar	foo.cpp	/^namespace foo::bar::baz3 { }$/;"	n	namespace:foo	file:
baz1	foo.cpp	/^	namespace baz1::baz2 {$/;"	n	namespace:foo::bar	file:
baz2	foo.cpp	/^	namespace baz1::baz2 {$/;"	n	namespace:foo::bar::baz1	file:
baz3	foo.cpp	/^namespace foo::bar::baz3 { }$/;"	n	namespace:foo::bar	file:
foo	foo.cpp	/^namespace foo::bar {$/;"	n	file:
foo	foo.cpp	/^namespace foo::bar::baz3 { }$/;"	n	file:
zz	foo.cpp	/^	void zz() {}$/;"	f	namespace:foo::bar::baz1::baz2	typeref:typename:void

```

**Comment by liuchengxu** [comment]
The tree view is already supported by `:Vista ctags`, there is some space for improvement though (https://github.com/liuchengxu/vista.vim/issues/320).
