### ISSUE TITLE
Any plan for  https://github.com/yegappan/lsp

### ISSUE THREAD

**Issue by leoatchina** [liuchengxu/vista.vim#468]
It is a repo written in pure vim9script, and full lsp features.

**Comment by liuchengxu** [comment]
PR is always welcome, but I personally won't invest more in developing new features for this plugin. My main focus will be [the plugins of vim-clap](https://liuchengxu.github.io/vim-clap/plugins/plugins.html#ctags), which are still experimental and unpublicized. The ctags plugin of vim-clap may be a (_better_) replacement of vista.vim in future.
