### ISSUE TITLE
E121: Undefined variable: kind when run :Vista

### ISSUE THREAD

**Issue by Sinderella** [liuchengxu/vista.vim#49]
**Describe the bug**
I recently updated the plugin and when vim loads the sidebar automatically, it gives me the following error messages:

```
Error detected while processing function <SNR>182_on_exit[4]..<SNR>182_ExtractLinewise[5]..vista#parser#ctags#FromExtendedRaw[12]..<SNR>196_ParseTagfield:
line    9:
E121: Undefined variable: kind
Press ENTER or type command to continue
Error detected while processing function <SNR>182_on_exit[4]..<SNR>182_ExtractLinewise[5]..vista#parser#ctags#FromExtendedRaw[12]..<SNR>196_ParseTagfield:
line    9:
E116: Invalid arguments for function index
Press ENTER or type command to continue
Error detected while processing function <SNR>182_on_exit[4]..<SNR>182_ExtractLinewise[5]..vista#parser#ctags#FromExtendedRaw[12]..<SNR>196_ParseTagfield:
line    9:
E15: Invalid expression: index(t:vista.kinds, kind) == -1
```

**Environment:**
- OS: Linux Mint 19
- Vim/Neovim version: NVIM v0.4.0-386-gced980ff1 
- This plugin version: c20cb84833e9e8fa730f98f92303f724e0a007d

**Minimal vimrc to reproduce**

```vim
call plug#begin('~/.vim/plugged')
Plug 'liuchengxu/vista.vim'
call plug#end()
```

**Steps to reproduce given the above minimal vimrc**

1. Install the plugin using vimplug
2. Open a file with vim
3. Run `:Vista`

**Expected behavior**
It shouldn't give the error messages as it was fine before the last update.

**Actual behavior**
Display error messages.

**Screenshot or gif** (if possible)
See the error messages above.

**Comment by liuchengxu** [comment]
Sorry for the inconvenience, should work as before now. vista.vim is still in a rapid development, if you do prefer a stable one, please pin to a commit.

**Comment by Sinderella** [comment]
No worries, it's a great plugin, and testing and raising issues would be the only thing I can help for the moment.
