### ISSUE TITLE
Error when searching in outline view with coc

### ISSUE THREAD

**Issue by elliothatch** [liuchengxu/vista.vim#52]
I'm using Vista with coc for editing Typescript in Neovim v0.3.4. When I press the slash button in the Vista window I get the following error:

```
Error detected while processing function vista#finder#fzf#Run[36]..<SNR>101_TryAlternatives[7]..vista#executive#vim_lsp#Run[1]..<SNR>104_HasAvaliableServers:
line    1:
E117: Unknown function: lsp#get_whitelisted_servers
E116: Invalid arguments for function filter
E15: Invalid expression: filter(lsp#get_whitelisted_servers(), 'lsp#capabilities#has_document_symbol_provider(v:val)')
```
Running `:Vista finder` in the same file works fine with no error. The slash behavior also works fine with JSON filetype (only other filetype I've tested).

I just have this one line in my init.vim:

`let g:vista_default_executive = 'coc'`

Thanks

**Comment by liuchengxu** [comment]
Please fill the issue template.

**Comment by elliothatch** [comment]
**Describe the bug**
I'm using Vista with coc for editing Typescript. When I press the slash button in the Vista window I get an error and am unable to search for symbols.

**Environment:**
- OS: Arch Linux x86_64 kernel 5.0.6-arch1-1-ARCH
- Vim/Neovim version: NVIM v0.3.4 Build type: Release
- This plugin version: 258d068839e786bcae394645c8a96b74fd05e15b

**Minimal vimrc to reproduce**

```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}
Plug 'neoclide/coc-tsserver', {'do': 'yarn install --frozen-lockfile'}
Plug 'sheerun/vim-polyglot' " without typescript syntax highlighting, the :Vista command does nothing?
Plug 'liuchengxu/vista.vim'
call plug#end()
 
let g:vista_default_executive = 'coc'
```

**Steps to reproduce given the above minimal vimrc**

1. Open Typescript file.
2. Run `:Vista`
3. Press `/` (slash)

**Expected behavior**
I can search the symbols in the Vista window.

**Actual behavior**
This error appears:

```
Error detected while processing function vista#finder#fzf#Run[36]..<SNR>101_TryAlternatives[7]..vista#executive#vim_lsp#Run[1]..<SNR>104_HasAvaliableServers:
line    1:
E117: Unknown function: lsp#get_whitelisted_servers
E116: Invalid arguments for function filter
E15: Invalid expression: filter(lsp#get_whitelisted_servers(), 'lsp#capabilities#has_document_symbol_provider(v:val)')
```
