### ISSUE TITLE
Vista window's width ignoring configuration value after first render

### ISSUE THREAD

**Issue by bigardone** [liuchengxu/vista.vim#53]
**Describe the bug**

I have set the `g:vista_sidebar_width` option to `60`, but after the first time it shows the window, it then resets the width to its default value.

**Environment:**

- OS: Mac OS
- Vim/Neovim version: Neovim 0.3.4
- This plugin version: `5fef8e3`

**Minimal vimrc to reproduce**

```vim
" Vista configuration
let g:vista_default_executive = 'coc'
let g:vista_close_on_jump = 1
let g:vista_blink  = [0, 0]
let g:vista_sidebar_width = 60
let g:vista_finder_alternative_executives = ['coc']
let g:vista#renderer#enable_icon = 0
map <C-m> :Vista coc<CR>
```

**How to reproduce**

1. Press `<C-m>` to open Vista's view.
2. Press `q` to close it.
3. Press `<C-m>` again.

### First render
![image](https://user-images.githubusercontent.com/1090272/55856872-eb5ed600-5b6b-11e9-81d5-b8e0f3bc1e02.png)

### Next renders
![image](https://user-images.githubusercontent.com/1090272/55856922-0c272b80-5b6c-11e9-99cc-84f0537056e1.png)

**Comment by liuchengxu** [comment]
Please pull the latest commit, should be fixed.

**Comment by bigardone** [comment]
Working like a charm now, thanks! 🎉
