### ISSUE TITLE
Airline support

### ISSUE THREAD

**Issue by lanox** [liuchengxu/vista.vim#54]
Hi, 

I was wondering ```RunForNearestMethodOrFunction``` is this supported on Airline ? 

Also is it possible to have Vista open on startup ?

**Comment by liuchengxu** [comment]
See this section https://github.com/liuchengxu/vista.vim#show-the-nearest-methodfunction-in-the-statusline to run vista.vim on startup.

It should be easy to support vista.vim on vim-airline, but I recently don't use airline, so I may not add this support myself.

**Comment by lanox** [comment]
@liuchengxu  not sure I see what I am looking there, but will take another look.

also quick question regarding floating_win it seems to blink  when you move to function and its kind of annoying is it possible to make sure it doesn't blink

Thanks for you work

**Comment by liuchengxu** [comment]
If you think there is a problem with the floating win, you should raise another issue and describe it carefully, otherwise I can't help about it.

**Comment by lanox** [comment]
No problems, I will open another issue, altho I am still not sure how to load this on startup.

**Comment by liuchengxu** [comment]
Just add this line your vimrc, then vista.vim will run on startup:

```vim
autocmd VimEnter * call vista#RunForNearestMethodOrFunction()
```

**Comment by lanox** [comment]
That is what I tried but got this on error
```
Error detected while processing VimEnter Autocommands for "*":
E117: Unknown function: vista#RunForNearestMethodOrFunction
```

**Comment by liuchengxu** [comment]
Have you updated to the latest version?

**Comment by lanox** [comment]
To be honest i just discovered this plugin, so yes i have latest, and I just tried updating it and it says I have latest.

**Comment by liuchengxu** [comment]
This feature has been added since #39, so I can only suggest you make sure that you are really using the right version.

**Comment by lanox** [comment]
this the the git rev i am using 3c222b3
and NVIM v0.4.0-dev

**Comment by liuchengxu** [comment]
Can you open the file `autoload/vista.vim` to see if the function is in there?

**Comment by lanox** [comment]
this is what I see in that file.

```
function! vista#RunForNearestMethodOrFunction() abort
  let [bufnr, winnr, fname, fpath] = [bufnr('%'), winnr(), expand('%'), expand('%:p')]
  call vista#source#Update(bufnr, winnr, fname, fpath)
  let executive = get(g:, 'vista_default_executive', 'ctags')
  call vista#executive#{executive}#Execute(v:false, v:false)
```

**Comment by liuchengxu** [comment]
Then what does `:call vista#RunForNearestMethodOrFunction` say?

**Comment by lanox** [comment]
Missing parentheses: vista#RunForNearestMethodOrFunction

**Comment by liuchengxu** [comment]
Oh, my bad, should be `:call vista#RunForNearestMethodOrFunction()`.

**Comment by lanox** [comment]
I updated the comment before as I though you might of missed it.

**Comment by liuchengxu** [comment]
No error with `:call vista#RunForNearestMethodOrFunction()`? Then it's probably that vista.vim has not been added to your runtimepath when calling the function. You should check your vimrc to ensure it's initialized before your call.

**Comment by lanox** [comment]
That is work considering all else work ..

**Comment by liuchengxu** [comment]
What is `:scriptnames`?

You should post your vimrc to fix this quickly.

**Comment by lanox** [comment]
my vimrc is bit complicated as it's in seperate files etc. Look dont worry about I will continue to look in to it.

It's strange I am having issue only with  this plugin, i have other functions/plugins that I use and they seem to be working fine.

**Comment by liuchengxu** [comment]
This problem should be utterly easy to resolve, just ensure that it's initialized correctly and vim can find the right path. It's all on your own vimrc.

**Comment by lanox** [comment]
You can see my minimal config in there, however even with minimal it still doesn't work.
https://asciinema.org/a/K8we8huUfL9I5XAwvSW2xDIq1
