### ISSUE TITLE
floating_window constantly blinks.

### ISSUE THREAD

**Issue by lanox** [liuchengxu/vista.vim#55]
**Describe the bug**
when function selected floating window seems to blink.

**Environment:**
- OS: 10.14.3 (18D109)
- Neovim version: v0.4.0-dev
- This plugin version: 3c222b3ffbc78552e419c6e084cdbf88405794f2

**Steps to reproduce given the above minimal vimrc**
Open a file that contains method/function move your mouse to any function, floating window will show up and start blinking.

**Expected behavior**
floating window to pop up but not blink.

**Comment by liuchengxu** [comment]
Can you reproduce with this mini-vimrc?

```vim
call plug#begin('~/.vim/plugged')
Plug 'liuchengxu/vista.vim'
call plug#end()

let g:vista_echo_cursor_strategy = 'floating_win'
```

Open nvim with `nvim -u mini-vimrc`.

**Comment by lanox** [comment]
[https://asciinema.org/a/eXskOuP2VmhsXClky8GSC7MJK](url)

**Comment by liuchengxu** [comment]
You are not using the minimal vimrc, I'm seeing the airline plugin.

**Comment by lanox** [comment]
sorry I have update the url with right link I paste old link

**Comment by liuchengxu** [comment]
Still using the airline plugin, open vim via `vi -u mini-vimrc`.

**Comment by lanox** [comment]
Well that is embarrassing.

https://asciinema.org/a/4QAjfSg1UkSm8J7HDvfDixxML

**Comment by liuchengxu** [comment]
I don't know what's wrong in your case, I have no problem with the above minimal vimrc. You have to figure it out by yourself.

**Comment by lanox** [comment]
Thanks for your help.

**Comment by lanox** [comment]
I found what the problem was, it was delimitMate plugin that was making it blink, dunno why. 

And the reason I saw no tags on minimal vimrc was because of my ctags not been installed properly.

**Comment by liuchengxu** [comment]
Concerning this issue, a reproducible vimrc with minimal plugins and configuration would be appreciated, I don't have much time to debug other plugins.

**Comment by lanox** [comment]
You should be able to reproduce the issue with the config below, just as a FYI I am not suggesting you start investigating other plugins, I am simply saying those where the plugins causing the issue I reported,

```
call plug#begin('~/.vim/plugged')
Plug 'liuchengxu/vista.vim'
Plug 'Raimondi/delimitMate'
Plug 'TaDaa/vimade' 
call plug#end()

let g:vista_echo_cursor_strategy = 'floating_win'
```

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/vista.vim/commit/3465da23dab6dcac54a9f8f36d4064edf94e0d73 seemingly fixes this issue, I now see no blinks with the above minimal vimrc. You can try it to see if the blink still exists.

**Comment by liuchengxu** [comment]
I have confirmed that the blink does not happen in my machine, feel free to reopen if it doesn't work for you.

**Comment by lanox** [comment]
Thanks that worked @liuchengxu

**Comment by roachsinai** [comment]
> Still using the airline plugin, open vim via `vi -u mini-vimrc`.

Found it should be `vi -Nu mini-vimrc`.

**Comment by roachsinai** [comment]
And what's more, I have set `let g:vista_echo_cursor_strategy = 'floating_win'`, but what I got is a `scroll` effect! While no this confusion with a mini-vimrc.

Maybe some plugin involved!

**Comment by roachsinai** [comment]
![vista](https://user-images.githubusercontent.com/9500049/78094830-1d65e980-7408-11ea-864a-3e076efbd156.gif)

**Comment by liuchengxu** [comment]
@roachsinai Everything I see works as expected. You misundetstand the `scroll` option. Set `g:vista_echo_cursor_strategy` to `scroll`, you'll what the real `scroll` effect is. `scroll` here means to position the cursorline in the source file to the tagline.

**Comment by roachsinai** [comment]
While my fault that have set `let g:vista_echo_cursor = 0`. By the way @liuchengxu could you tell me the font you're using?

**Comment by liuchengxu** [comment]
Not sure which kind of font you are saying, here are my often used ones. https://github.com/liuchengxu/space-vim/wiki/tips#programming-fonts

**Comment by roachsinai** [comment]
![](https://user-images.githubusercontent.com/8850248/55805524-2b449f80-5b11-11e9-85d4-018c305a5ecb.png)

I want to konw the font you showed in above picture.

And I have a question, 

```
let g:vista#renderer#icons = {
\   "function": "\uf794",
\   "variable": "\uf71b",
\  }
```

`"\uf71b"`, should be

![image](https://user-images.githubusercontent.com/9500049/78096260-bb0ee800-740b-11ea-866f-23dd052fce19.png)

from https://www.fileformat.info/info/unicode/char/f71b/index.htm

But, why got a `x`.

**Comment by liuchengxu** [comment]
@roachsinai https://unix.stackexchange.com/questions/61118/how-to-enter-non-ascii-characters-using-hex-or-octal-codes-in-vi, try you self. And please do not leave comments under the unrelated issues.
