### ISSUE TITLE
大佬 不好意思 这次更新后 打开vista没有任何内容显示。。。。

### ISSUE THREAD

**Issue by huayue369** [liuchengxu/vista.vim#64]
、、、

"vista配置{{{
"
" 
function! NearestMethodOrFunction() abort
  return get(b:, 'vista_nearest_method_or_function', '')
endfunction
" 启用悬浮窗预览
let g:vista_echo_cursor_strategy ='floating_win'
" 侧边栏宽度.
let g:vista_sidebar_width = 30
" 设置为0，以禁用光标移动时的回显.
let g:vista_echo_cursor = 1
" 当前游标上显示详细符号信息的时间延迟.
let g:vista_cursor_delay = 400
" 跳转到一个符号时，自动关闭vista窗口.
let g:vista_close_on_jump = 0
"打开vista窗口后移动到它.
let g:vista_stay_on_open = 1
" 跳转到标记后闪烁光标2次，间隔100ms.
let g:vista_blink = [2, 100]
" 图标美化
let g:vista#renderer#enable_icon = 1
let g:vista#renderer#icons = {
\   "function": "\uf30b",
\   "variable": "\uf5c0",
\  }
" 展示样式
let g:vista_icon_indent = ["╰─▸ ", "├─▸ "]
" Executive used when opening vista sidebar without specifying it.
" Avaliable: 'coc', 'ctags'. 'ctags' by default.
" 优先选择lsp作为标签来源，其次ctags
let g:vista_cpp_executive = 'vim_lsp'
let g:vista_default_executive = 'ctags'
" To enable fzf's preview window set g:vista_fzf_preview.
" The elements of g:vista_fzf_preview will be passed as arguments to fzf#vim#with_preview()
" For example:
let g:vista_fzf_preview = ['right:50%']
let g:vista_finder_alternative_executives = ['coc']
"}}}vista配置
、、、
这是本人配置

**Comment by huayue369** [comment]
![Untitled](https://user-images.githubusercontent.com/32536764/56497577-b326a280-6530-11e9-9bab-bf8ee77b1f44.gif)

**Comment by liuchengxu** [comment]
提供最小 vimrc 和重现步骤，我这里没问题。

**Comment by huayue369** [comment]
<img width="837" alt="屏幕快照 2019-04-23 下午5 13 29" src="https://user-images.githubusercontent.com/32536764/56569336-5e942d80-65eb-11e9-918e-c30fc4ad2d01.png">
这是现在的所有配置，但还是不显示任何内容  这是这次更新后出现的问题
<img width="837" alt="屏幕快照 2019-04-23 下午5 12 28" src="https://user-images.githubusercontent.com/32536764/56569455-90a58f80-65eb-11e9-9e76-e34009f9ba93.png">
<img width="584" alt="屏幕快照 2019-04-23 下午5 17 56" src="https://user-images.githubusercontent.com/32536764/56569559-c5194b80-65eb-11e9-82f1-6c37dcd7868b.png">
Mac
neovim最新

**Comment by liuchengxu** [comment]
贴可以复制的代码，我没办法拷贝图片。

**Comment by huayue369** [comment]
call plug#begin('~/.cache/plugged')
Plug 'liuchengxu/vista.vim'
call plug#end()

"vista配置{{{

" 启用悬浮窗预览
let g:vista_echo_cursor_strategy ='floating_win'
" 侧边栏宽度.
let g:vista_sidebar_width = 30
" 设置为0，以禁用光标移动时的回显.
let g:vista_echo_cursor = 1
" 当前游标上显示详细符号信息的时间延迟.
let g:vista_cursor_delay = 400
" 跳转到一个符号时，自动关闭vista窗口.
let g:vista_close_on_jump = 0
"打开vista窗口后移动到它.
let g:vista_stay_on_open = 1
" 跳转到标记后闪烁光标2次，间隔100ms.
let g:vista_blink = [2, 100]
" 展示样式
let g:vista_icon_indent = ["╰─▸ ", "├─▸ "]

" 系统寄存器粘贴复制键{{{
nmap <C-p> "+gp
vmap <C-p> "+gp
vmap <C-y> "+y
" }}}系统寄存器粘贴复制键

" mouse {{{
set mouse+=a
set mousehide
" }}} mouse

**Comment by liuchengxu** [comment]
<img width="1680" alt="屏幕快照 2019-04-23 下午5 50 40" src="https://user-images.githubusercontent.com/8850248/56571839-61dde800-65f0-11e9-97d9-872fb3d93e2e.png">

vimrc 无法复现，是你自己本地的问题。

```vim
call plug#begin('~/.vim/plugged')
Plug 'liuchengxu/vista.vim'
call plug#end()

"vista配置{{{

" 启用悬浮窗预览
let g:vista_echo_cursor_strategy ='floating_win'
" 侧边栏宽度.
let g:vista_sidebar_width = 30
" 设置为0，以禁用光标移动时的回显.
let g:vista_echo_cursor = 1
" 当前游标上显示详细符号信息的时间延迟.
let g:vista_cursor_delay = 400
" 跳转到一个符号时，自动关闭vista窗口.
let g:vista_close_on_jump = 0
"打开vista窗口后移动到它.
let g:vista_stay_on_open = 1
" 跳转到标记后闪烁光标2次，间隔100ms.
let g:vista_blink = [2, 100]
" 展示样式
let g:vista_icon_indent = ["╰─▸ ", "├─▸ "]

" 系统寄存器粘贴复制键{{{
nmap "+gp
vmap "+gp
vmap "+y
" }}}系统寄存器粘贴复制键

" mouse {{{
set mouse+=a
set mousehide
" }}} mouse
```

**Comment by huayue369** [comment]
哦  vista coc命令又正常 但vista ctags不能正常显示 是不是我的ctags出问题了? 我用ctags -R在目录下创建了标签还是无法正常显示。。。但fzf的Btags命令能够正常显示标签！对了  我用gutentags统一管理tags标签文件 会不会导致vista找不到标签文件啊  或者无法识别标签文件的命名？
<img width="589" alt="屏幕快照 2019-04-24 下午1 11 51" src="https://user-images.githubusercontent.com/32536764/56633896-91453100-6692-11e9-9209-dbd151b8907b.png">
这是我的所有标签文件，不知道有人遇到我这问题没有
我把所有插件重装，neovim重装还是没用，我用的Universal Ctags

**Comment by liuchengxu** [comment]
vista.vim 都是内存操作，不用 tags 文件。

**Comment by huayue369** [comment]
哦 已确定就ctags出问题了  包括md coc-lsp都没问题 。。。。。能力有限解决不了。。。。谢谢大佬了  不知道和电脑权限有关系没有。。。

**Comment by huayue369** [comment]
大佬 这次更新 该问题已恢复正常
