### ISSUE TITLE
Error detected while processing function <SNR>170_on_exit[6].., with neovim in ubuntu 18.04

### ISSUE THREAD

**Issue by leoatchina** [liuchengxu/vista.vim#66]
**Describe the bug**
As the title, an error raised when use neovim  in  Ubuntu18.04
```
Error detected while processing function <SNR>170_on_exit[6]..<SNR>170_ApplyExtracted[14]..vista#viewer#Display[1]..<SNR>176_Render[2]..vista#renderer#default#Render[5]..<SNR>178_Re
nder[1]..303:
line    3:
E716: Key not present in Dictionary: sro
Press ENTER or type command to continue
Error detected while processing function <SNR>170_on_exit[6]..<SNR>170_ApplyExtracted[14]..vista#viewer#Display[1]..<SNR>176_Render[2]..vista#renderer#default#Render[5]..<SNR>178_Re
nder[1]..303:
line    3:
E15: Invalid expression: g:vista#types#uctags#{filetype}#['sro']
Press ENTER or type command to continue
Error detected while processing function <SNR>170_on_exit[6]..<SNR>170_ApplyExtracted[14]..vista#viewer#Display[1]..<SNR>176_Render:
line    2:
E171: Missing :endif
Press ENTER or type command to continue
Error detected while processing function <SNR>170_on_exit[6]..<SNR>170_ApplyExtracted:
line   14:
E171: Missing :endif

```

**Environment:**
- OS: Ubuntu 18.04 ( macos with neovim 0.3.4 works good)
- Neovim version: NVIM 0.3.1,   and `Vim8` **works good**
- This plugin version: 268a88df5a62fa35b5f4794df5ee60a0be9ba1f7
- ctags version:
```
Universal Ctags 0.0.0(9630c392), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Apr 25 2019, 07:36:22
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +json, +interactive, +packcc

```

**Vista info**

                                                                                                                                                                                
Current FileType: vim
Avaliable Executives: ['ctags']
Global Variables:
let g:vista#executives = ['coc', 'ctags', 'lcn', 'vim_lsp']
let g:vista#renderer#enable_icon = 0
let g:vista_default_executive = 'ctags'
let g:vista_echo_cursor = 0
let g:vista_icon_indent = ['╰─ ', '├─ ']
let g:vista_sidebar_position = 'vertical topleft'
let g:vista_stay_on_open = 0
~

**Steps to reproduce given the above info**

just run `:Vista`

**Expected behavior**
This is the screenshot of Vim8, the same OS, the same config
![image](https://user-images.githubusercontent.com/4470821/56739878-55998c80-67a2-11e9-999e-8b31c93a13e5.png)

Neovim 0.3.4 in macOS 10.13.6
![image](https://user-images.githubusercontent.com/4470821/56740600-d7d68080-67a3-11e9-8881-dcff61ce4660.png)

**Actual behavior**
See below

**Screenshot or gif** (if possible)
![image](https://user-images.githubusercontent.com/4470821/56739665-d3a96380-67a1-11e9-88aa-7ded54f0560f.png)

**Comment by liuchengxu** [comment]
What does `:echo g:vista#types#uctags#vim#` and `:echo g:vista#types#uctags#vim#['sro']` say?

In addition, have you copied the completed output from `:Vista info`? The Global Variables section should contain `let g:vista#executive#ctags#support_json_format = 1/0`.

**Comment by leoatchina** [comment]
Just open README in vista.vim


echo g:vista#types#uctags#vim#
```
{'lang': 'vim', 'kinds': {'a': {'long': 'autocommand groups', 'fold': 1, 'stl': 1}, 'c': {'long': 'commands', 'fold': 0, 'stl': 0}, 'f': {'long': 'functions', 'fold': 0, 'stl': 1},
'v': {'long': 'variables', 'fold': 1, 'stl': 0}, 'm': {'long': 'maps', 'fold': 1, 'stl': 0}, 'n': {'long': 'vimball filenames', 'fold': 0, 'stl': 1}}}
```


echo g:vista#types#uctags#vim#['sro']
```
E716: Key not present in Dictionary: sro
E15: Invalid expression: g:vista#types#uctags#vim#['sro']
```


Vista info
```
    Current FileType: markdown
Avaliable Executives: ['ctags']
    Global Variables:
    let g:vista#executive#ctags#support_json_format = 1
    let g:vista#executives = ['coc', 'ctags', 'lcn', 'vim_lsp']
    let g:vista#renderer#ctags = 'default'
    let g:vista#renderer#enable_icon = 0
    let g:vista#renderer#icons = {'subroutine': '洛', 'method': '', 'func': '', 'variables': '', 'namespace': '', 'field': '綠', 'interface': '禍', 'type': '', 'packages': '',
 'property': '襁', 'implementation': '', 'default': '', 'augroup': 'פּ', 'macro': '', 'enumerator': '', 'const': '', 'macros': '', 'map': 'פּ', 'fields': '綠', 'functions': '' ,
 'enum': '', 'function': '', 'target': '', 'typedef': '', 'variable': '', 'modules': '', 'constant': '', 'struct': 'פּ', 'types': '', 'module': '', 'typeParameter': '', 'pa
ckage': '', 'class': '', 'member': '', 'var': '', 'union': '鬒'}
    let g:vista_default_executive = 'ctags'
    let g:vista_echo_cursor = 0
    let g:vista_icon_indent = ['╰─ ', '├─ ']
    let g:vista_sidebar_position = 'vertical topleft'
    let g:vista_stay_on_open = 0
```

**Comment by leoatchina** [comment]
And since I installed LCN with neovim,  i have tried `Vista lcn`, nothing happend.

**Comment by leoatchina** [comment]
Sorry, it's my mistake. I have tried neovim again ,  and found the errors  happend with `vim` and `markdown`, `js`. Worked well with `php`, `python`. I will try some other type of source files.

**Comment by liuchengxu** [comment]
`:Vista` and then `:echo t:vista.source.scope_seperator()`, see if any errors, both in vim and neovim.

**Comment by leoatchina** [comment]
Just read `markdown` file
The results of `vim` is just a single `.` ?
when `neovim`
![image](https://user-images.githubusercontent.com/4470821/56780942-dba1eb80-6813-11e9-8f52-88d1a4c427cf.png)

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/vista.vim/blob/268a88df5a62fa35b5f4794df5ee60a0be9ba1f7/autoload/vista/source.vim#L48-L52

Then I think neovim should be blamed for not catching the exception.

**Comment by liuchengxu** [comment]
Please pull the latest version to see if the error persists.

**Comment by leoatchina** [comment]
ok, that works
