### ISSUE TITLE
Sort symbols

### ISSUE THREAD

**Issue by Sacules** [liuchengxu/vista.vim#67]
Hi, is it possible to sort the symbols alphabetically? Currently they appear according to the order they were declared, but it could be useful to be able to sort them.

**Comment by liuchengxu** [comment]
You mean to sort all the symbols under some category/struct or even the category should be displayed in some order? And I'm curious how that is useful, could you give an example?

**Comment by Sacules** [comment]
Just the symbols under a same category, yes. I find it useful when going through a new codebase to read the functions and methods in alphabetical order - usually related code starts with similar wording. This way it looks very similar to generated documentation like Doxygen and Godoc, and makes navigation easier.

![Imgur](https://i.imgur.com/A3DXeK6.png) ![Imgur](https://i.imgur.com/5kkMobD.png)

Here's the original order on a Scala file vs a mockup I made - it certainly feels a lot cleaner. Plus, this could go in handy with a hierarchical tree for certain data in the future.

**Comment by liuchengxu** [comment]
vista.vim now supports renders ctags in a hierarchical way, this feature was introduced in #58.

For LSP, to my knowledge, the hierarchicalDocumentSymbolSupport needs both the LSP server and client support,  it is not ubiquitous yet. But that's possible as long as the hierarchical info could be requested.

This feature is not hard to implement. I will take a look when I get some time.

**Comment by liuchengxu** [comment]
@Sacules You can use `s` in the vista window to sort the symbols back and forth.

**Comment by Sacules** [comment]
Works great! Thanks!
