### ISSUE TITLE
ctags running fail

### ISSUE THREAD

**Issue by jongheeyun** [liuchengxu/vista.vim#69]
**Describe the bug**
ctags runs fail.

**Environment:**
- OS:  macOS
- Neovim version: 0.4
- This plugin version: 1ea2ca78b782eefb897fbc1a9fa7e5d433436341

** If this issue is related to ctags, please also provide the source file you run Vista on.
https://github.com/google/shaka-player

**Vista info**

    Current FileType: 
Avaliable Executives: ['coc', 'ctags']
    Global Variables:
    let g:vista#executive#ctags#support_json_format = 0
    let g:vista#executives = ['coc', 'ctags', 'lcn', 'vim_lsp']
    let g:vista_default_executive = 'ctags'

**Steps to reproduce given the above info**

1. git clone Shaka repo
2. run command ":Vista finder coc" in nvim

**Expected behavior**
Shows symbol/tags

**Actual behavior**
[vista.vim]Fail to run ctags: ctags --format=2 --excmd=pattern --fields=nksSaf --extras= --file-scope=yes --sort=no --append=no --language-force=javascript --javascript-kinds=cpC
fvgm -f- /var/folders/_y/d89_j12d2xq_cnlh8v6btwpw0000gn/T/nvimDqvMz2/18.js
[vista.vim] Empty data for finder

**Comment by liuchengxu** [comment]
Can't reproduce with these steps.

```bash
cd /tmp
git clone https://github.com/google/shaka-player.git --depth=1
cd shaka-player
nvim lib/util/event_manager.js
```

`:Vista finder coc`:


<img width="1680" alt="屏幕快照 2019-04-28 下午10 23 44" src="https://user-images.githubusercontent.com/8850248/56865775-592c4e00-6a04-11e9-8baf-171b9ccea515.png">

**Comment by jongheeyun** [comment]
I installed universal ctags and run :Vista finder ctags and I got below screenshot.
Universal ctags built with json option.
<img width="930" alt="Screen Shot 2019-05-02 at 10 41 04 PM" src="https://user-images.githubusercontent.com/5599997/57079586-9a39a080-6d2b-11e9-890a-6371f1721b69.png">

But I got below result with :Vista ctags command.
Can I get symbol list with universal ctags like your screenshot?
<img width="929" alt="Screen Shot 2019-05-02 at 10 44 30 PM" src="https://user-images.githubusercontent.com/5599997/57079742-f997b080-6d2b-11e9-9e28-44b0682f9ac8.png">

**Comment by liuchengxu** [comment]
@jongheeyun `:Vista ctags` rendering nothing on `lib/util/event_manager.js` is unrelated to this issue. 

It's a problem of the `default` renderer of vista.vim. All tags from `lib/util/event_manager.js` has a scope field and vista.vim can't find the root of them correctly, which leads to the failure of `default` renderer. Please file another one for better triage.

**Comment by jongheeyun** [comment]
@liuchengxu   I set default finder as ctags than I can see symbols now. Thanks.

**Comment by TranquilTravis** [comment]
> @liuchengxu I set default finder as ctags than I can see symbols now. Thanks.

I face the same problem. Could you specify which option did you set?
