### ISSUE TITLE
neovim hang when call 'Vista lcn' and 'Vista finder lcn'

### ISSUE THREAD

**Issue by alextooter** [liuchengxu/vista.vim#71]
**Describe the bug**
I am using neovim 0.4.0 Nvim development (prerelease) build. from here :https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz 
And using LanguageClient-neovim plugin.Using default setting for python.

Then I map two key like this:
**nnoremap \<F2\> :Vista lcn\<CR\>**
**nnoremap \<F3\> :Vista finder lcn\<CR\>**

After setting those, I start a empty neovim with nothing opened,then press F2, and F3, neovim is hang,not response at all.

**Environment:**
macOS 10.14.4
NVIM v0.4.0-647-gf86f0a8bc

**Vista info**
    Current FileType: 
Avaliable Executives: ['ctags', 'lcn']
    Global Variables:
    let g:vista#executives = ['coc', 'ctags', 'lcn', 'vim_lsp']
    let g:vista_echo_cursor_strategy = 'floating_win'
    let g:vista_icon_indent = ['▸ ', '']

**Comment by liuchengxu** [comment]
Can't reproduce in my machine. Could you provide a minimal vimrc?

**Comment by alextooter** [comment]
> Can't reproduce in my machine. Could you provide a minimal vimrc?

my vimrc:

let g:LanguageClient_serverCommands = {
    \ 'rust': ['~/.cargo/bin/rustup', 'run', 'stable', 'rls'],
    \ 'javascript': ['/usr/local/bin/javascript-typescript-stdio'],
    \ 'javascript.jsx': ['tcp://127.0.0.1:2089'],
    \ 'python': ['/usr/local/bin/pyls'],
    \ 'ruby': ['~/.rbenv/shims/solargraph', 'stdio'],
    \ 'c': ['/usr/local/bin/ccls'],
    \ 'cpp': ['/usr/local/bin/ccls'],
    \ 'objc': ['/usr/local/bin/ccls'],
    \ }

let g:vista_icon_indent = ["▸ ", ""]
let g:vista_echo_cursor_strategy="floating_win"

map \<F1\> :NERDTreeToggle\<CR\>
nnoremap \<F2\> :Vista lcn\<CR\>
nnoremap \<F3\> :Vista finder lcn\<CR\>
map \<F4\> :FZF\<CR\>
nnoremap \<F5\> :call LanguageClient_contextMenu()\<CR\>

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/vista.vim/blob/ab6098382d618475d47581fc08683257a29df0cb/autoload/vista/executive/lcn.vim#L47-L57

I know what is going on. LanguageClient-neovim does not provide a sync version of getting document symbols itself, so I use the sleep strategy to mock the async way, which is also LCN currently used to run synchronously. Since you essentially are running `LanguageClient#textDocument_documentSymbol` on a empty file which never returns by LCN, then your neovim hangs.

This is not the normal use case and can't be fixed as it counts on LCN, so I suggest you just don't use it like that.

**Comment by alextooter** [comment]
> [vista.vim/autoload/vista/executive/lcn.vim](https://github.com/liuchengxu/vista.vim/blob/ab6098382d618475d47581fc08683257a29df0cb/autoload/vista/executive/lcn.vim#L47-L57)
> 
> Lines 47 to 57 in [ab60983](/liuchengxu/vista.vim/commit/ab6098382d618475d47581fc08683257a29df0cb)
>  function! s:Run() abort 
>    if !exists('*LanguageClient#textDocument_documentSymbol') 
>      return 
>    endif 
>    call s:RunAsync() 
>    let s:fetching = v:true 
>    while s:fetching 
>      sleep 100m 
>    endwhile 
>    return get(s:, 'data', {}) 
>  endfunction 
> 
> I know what is going on. LanguageClient-neovim does not provide a sync version of getting document symbols itself, so I use the async version and sleep strategy to mock the sync one , which is also LCN currently used to run synchronously. Since you are essentially running `LanguageClient#textDocument_documentSymbol` on an empty file which never returns by LCN, then your neovim hangs.
> 
> This is not the normal use case and can't be fixed as it counts on LCN, so I suggest you just don't use it like that.

I have test on a simple python file,such as test.py,which have following code:

big_dict = {}
with open("test_log.txt") as f_in:
    for line in f_in:
        items = line.strip().split(' ')
        key = items[0]
        if key not in big_dict:
            big_dict[key] = set([])
        for i in items[1:]:
            big_dict[key].add(i)

print ("total keys:", len(big_dict))


press F2 then F3, neovim hand too.

I have test on empty file and not empty file this afternoon,then I think empty file case may easy for you debug,it's my fault only report the empty file case.

**Comment by liuchengxu** [comment]
Unforturately, I still can't reproduce with this minimal vimrc with test.py you posted:

```bash
call plug#begin('~/.vim/plugged')
Plug 'autozimu/LanguageClient-neovim'
Plug 'liuchengxu/vista.vim'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
call plug#end()

let g:LanguageClient_serverCommands = {
\ 'python': ['/usr/local/bin/pyls'],
\ 'c': ['/usr/local/bin/ccls'],
\ 'cpp': ['/usr/local/bin/ccls'],
\ 'objc': ['/usr/local/bin/ccls'],
\ }

let g:vista_icon_indent = ["▸ ", ""]
let g:vista_echo_cursor_strategy="floating_win"

nnoremap vl :Vista lcn<CR>
nnoremap vf :Vista finder lcn<CR>
```

And for `:Vista finder lcn`, it will fall back to ctags automatically.

<img width="1680" alt="屏幕快照 2019-05-01 上午9 39 58" src="https://user-images.githubusercontent.com/8850248/57002876-25fce100-6bf5-11e9-9fdf-a055571931cb.png">

**Comment by alextooter** [comment]
> Unforturately, I still can't reproduce with this minimal vimrc with test.py you posted:
> 
> ```shell
> call plug#begin('~/.vim/plugged')
> Plug 'autozimu/LanguageClient-neovim'
> Plug 'liuchengxu/vista.vim'
> Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
> call plug#end()
> 
> let g:LanguageClient_serverCommands = {
> \ 'python': ['/usr/local/bin/pyls'],
> \ 'c': ['/usr/local/bin/ccls'],
> \ 'cpp': ['/usr/local/bin/ccls'],
> \ 'objc': ['/usr/local/bin/ccls'],
> \ }
> 
> let g:vista_icon_indent = ["▸ ", ""]
> let g:vista_echo_cursor_strategy="floating_win"
> 
> nnoremap vl :Vista lcn<CR>
> nnoremap vf :Vista finder lcn<CR>
> ```
> 
> And for `:Vista finder lcn`, it will fall back to ctags automatically.
> 
> <img alt="屏幕快照 2019-05-01 上午9 39 58" width="1680" src="https://user-images.githubusercontent.com/8850248/57002876-25fce100-6bf5-11e9-9fdf-a055571931cb.png">
> 
> Edit:
> 
> I forgot to install `pyls`. With `pyls` installed, everything works fine.
> 
> <img alt="屏幕快照 2019-05-01 上午9 44 17" width="1680" src="https://user-images.githubusercontent.com/8850248/57002973-ca7f2300-6bf5-11e9-9143-f6469ebb7c82.png">
I call 'Vista lcn' see the same thing on the right. if I Moving cursor from tag window to code window, then call 'Vista finder lcn', it works fine. If cursor stay in tag window,call 'Vista finder lcn',neovim will hang.

**Comment by liuchengxu** [comment]
@alextooter The latest version should fix this issue.
