### ISSUE TITLE
More pretty kind icons

### ISSUE THREAD

**Issue by liuchengxu** [liuchengxu/vista.vim#74]
<img width="773" alt="屏幕快照 2019-05-01 上午9 56 45" src="https://user-images.githubusercontent.com/8850248/57003186-9278df80-6bf7-11e9-85a7-48c45a72937b.png">

We could make vista.vim like the screenshot above via the unicode symbols for the vanity:(. In order to achieve that, you'll have to install some special fonts, e.g., [nerd fonts](https://nerdfonts.com/), even change your terminal emulator as not every terminal emulator could render these symbols properly to my knowledge.

Feel free to comment in this issue if you have any ideas.

<img width="279" alt="屏幕快照 2019-05-01 上午10 06 08" src="https://user-images.githubusercontent.com/8850248/57003363-c3a5df80-6bf8-11e9-9ba8-7cce8b0406ef.png">

- https://unicode.org/charts/nameslist/n_1F100.html
- https://en.wikipedia.org/wiki/Enclosed_Alphanumerics

**Comment by jongheeyun** [comment]
Which font should I use for them?
My nvim shows like this. I'm using monaco font and powerline fonts on the Mac.

<img width="262" alt="Screen Shot 2019-05-02 at 11 32 09 PM" src="https://user-images.githubusercontent.com/5599997/57082897-9c532d80-6d32-11e9-864c-3903b888ec76.png">

**Comment by liuchengxu** [comment]
@jongheeyun https://nerdfonts.com/

**Comment by jongheeyun** [comment]
@liuchengxu Thank you very much.

**Comment by lanox** [comment]
@liuchengxu how can I make vista look like in screenshot you posted, I am using Droid Sens Mono nerd font.

**Comment by liuchengxu** [comment]
@lanox `:h g:vista#renderer#enable_icon`.

**Comment by lanox** [comment]
@liuchengxu ah thanks, I had that enabled already, but I miss read when you said we could make it look like this.

**Comment by liuchengxu** [comment]
@lanox Then what do you expect?

**Comment by lanox** [comment]
> <img alt="屏幕快照 2019-05-01 上午9 56 45" width="773" src="https://user-images.githubusercontent.com/8850248/57003186-9278df80-6bf7-11e9-85a7-48c45a72937b.png">

Sorry I was replaying from my phone, I was referring to image above how could I make it look like that. 

currently my config looks like the image below.
<img width="233" alt="Screen Shot 2019-05-06 at 9 48 01 am" src="https://user-images.githubusercontent.com/7599183/57202046-1cec8500-6fe4-11e9-85d2-88dd23d74a3b.png">

**Comment by liuchengxu** [comment]
This makes more sense for `:Vista ctags` since it supports nested display. For the `kind` renderer, used for LSP symbols, I don't see any benefit. vista.vim already have the icon support, the next step is to tweak them for better display.

<img width="397" alt="屏幕快照 2019-05-06 上午7 58 49" src="https://user-images.githubusercontent.com/8850248/57202168-d7748b80-6fd4-11e9-9be9-7d6abd92eb3b.png">

**Comment by lanox** [comment]
That looks nice.

**Comment by easy-boy** [comment]
为什么我的是这样的？怎么修改图标呢？
![深度截图_选择区域_20190602100829](https://user-images.githubusercontent.com/23730441/58755822-8e095480-851e-11e9-9317-fc2bef3a849f.png)
