### ISSUE TITLE
Symbol are not update when entering window

### ISSUE THREAD

**Issue by free-easy** [liuchengxu/vista.vim#8]
AFAICT, it seems that the auto update is handled by this `autocmd`

```vim
    autocmd BufWritePost,BufReadPost,CursorHold * call
                \ s:AutoUpdate(fnamemodify(expand('<afile>'), ':p'))
```

Is it a feature or a bug?

**Comment by liuchengxu** [comment]
This is the normal practice, almost every plugin would take advantage of these events. I believe `BufReadPost` will trigger the auto update when you enter a new window, but due to the auto update is asynchronous, so you may feel it's not being updated if the async task takes some time.
