### ISSUE TITLE
let g:vista_sidebar_position = 'vertical topleft' does not work correctly

### ISSUE THREAD

**Issue by brglng** [liuchengxu/vista.vim#81]
**Describe the bug**
With `let g:vista_sidebar_position = 'vertical topleft'`, vista window should always open on the left side. However it only opens on the left side for the first time.

**Environment:**
- OS: macOS 10.14.4
- Vim/Neovim version: NVIM v0.4.0-dev
- This plugin version: 3797c49de5156aa16873927174a1545e77cb4fc3

**Vista info**

**Steps to reproduce given the above info**

1. Open vista window
2. Use `q` to quit vista window
3. Use `:Vista` or `:Vista!!` to open vista window again
4. See if the vista window is open on the left

**Expected behavior**
The vista window should always open on the left.

**Actual behavior**
The vista window is open on the left only for the first time.

**Screenshot or gif** (if possible)

![vista](https://user-images.githubusercontent.com/1525226/57617715-0b8f1400-75b4-11e9-839e-03d401210064.gif)

**Comment by liuchengxu** [comment]
Thanks for the report, please pull the latest commit.
