### ISSUE TITLE
Vista fails on c++ anonymous namespaces

### ISSUE THREAD

**Issue by kchibisov** [liuchengxu/vista.vim#83]
vista fails with:
```
Error detected while processing function <SNR>127_on_exit[6]..<SNR>127_ApplyExtracted[8]..vista#sidebar#Reload[14]..vista#viewer#Render[1]..<SNR>133_Render[2]..vista#renderer#default#Render[5]..<SNR>135_Render[40]..<SNR>135_RenderScopele
ss:
line   30:
E684: list index out of range: -1
```
**Describe the bug**
`vista` can't handle c++ anonymous namespaces with `ctags`.

**Environment:**
- OS: Arch Linux
- Vim/Neovim version: `NVIM v0.3.5`
- This plugin version: `ddd965201ecbe6f98042ba2f2c85fdc6fb205ec8`

Test case
```cpp
namespace {
    extern int foo();
}
```
**Vista info**
```
    Current FileType: vim
Avaliable Executives: ['ctags', 'lcn']
    Global Variables:
    let g:vista#executives = ['coc', 'ctags', 'lcn', 'vim_lsp']
    let g:vista_cursor_delay = 0
    let g:vista_sidebar_width = 35
    let g:vista_stay_on_open = 0
```
**Steps to reproduce given the above info**
Toggle vista

**Expected behavior**
show tags in anonymous namespace (e.g. generate name like __anonymous__1 2 3 etc. )

**Actual behavior**
Error

**Comment by liuchengxu** [comment]
This is a special case that ctags does not treat the anonymous namespace tag as the other ones. So I did a fix accordingly, but I'm not sure if there are some other filetypes having this issue.
