### ISSUE TITLE
Error when calling CocActionAsync('documentSymbols')

### ISSUE THREAD

**Issue by bigardone** [liuchengxu/vista.vim#85]
**Describe the bug**
I just updated Coc, and Vista stopped working, throwing this error

```
[vista.vim]Error when calling CocActionAsync('documentSymbols')
```

**Environment:**
- OS: macOS
- Vim/Neovim version: NVIM v0.3.5 Build type: Release
- This plugin version: 4b96ca52986e12f03e5dd54528ce0145156e165a

**Vista info**

```
    Current FileType: elixir
Avaliable Executives: ['coc', 'ctags']
    Global Variables:
    let g:vista#executives = ['coc', 'ctags', 'lcn', 'vim_lsp']
    let g:vista#renderer#enable_icon = 0
    let g:vista_blink = [0, 0]
    let g:vista_close_on_jump = 1
    let g:vista_default_executive = 'coc'
    let g:vista_echo_cursor = 0
    let g:vista_finder_alternative_executives = ['coc']
    let g:vista_sidebar_width = 60
```

**Steps to reproduce given the above info**

1. Run `:Vista` on the current buffer, or open any file supported by Coc/Vista, or save any file.
2. Error pops up.

**Expected behavior**
Display Vista's window with symbols.

**Actual behavior**
Error rises.

**Screenshot or gif** (if possible)

![image](https://user-images.githubusercontent.com/1090272/58305247-b050f300-7df7-11e9-81bb-e8908af07a46.png)

**Comment by liuchengxu** [comment]
I can't reproduce in a go file with the latest coc.nvim. I have pushed a commit to show the error message when it fails. You can pull it to see what is going on.

**Comment by bigardone** [comment]
Sure! Here it is

`[vista.vim]Error when calling CocActionAsync('documentSymbols'): 'service not started'`

**Comment by liuchengxu** [comment]
Obviously, your service not started. That's not a problem of vista. You have to ensure your coc works as expected.

**Comment by bigardone** [comment]
Yeah, sorry for the inconvenience. It is nothing related to Vista but to Coc. I'll address the issue to them. Anyways, thanks for the help :)

**Comment by abelthf** [comment]
I have the same problem after an update with CocUpdate, was the first report resolved?

**Comment by creeper4004** [comment]
> I have the same problem after an update with CocUpdate, was the first report resolved?

you solve it?

**Comment by Zebradil** [comment]
I'm having similar issue.
```
[vista.vim] Error when calling CocActionAsync('documentSymbols'): 'Cannot read property ''getDocumentSymbols'' of undefined'
```
Searching through neoclide/coc.nvim issues didn't reveal much. Not sure where to dig further.

**Comment by ChristianChiarulli** [comment]
Why is this issue closed? Did anyone resolve it?

**Comment by liuchengxu** [comment]
IMO vista.vim can do nothing about this as it merely calls this API. Anyway vista.vim introduced the logging feature since #319, you can use it to help debug.

**Comment by Lexx666** [comment]
The logging feature does not seem to tell anything about it, as no log entry occurs when the error ist displayed. All I got was:
```
2020-07-20 12:36:29 ["new last_event:",["BufWritePost",1]]
2020-07-20 12:36:29 ["tracking new buffer 1"]
2020-07-20 12:36:29 ["event.BufWritePost processing auto update for buffer 1"]
```

**Comment by liuchengxu** [comment]
@Lexx666 You have to add the neccessary debugging statements on your own, as the existing log doesn't trace everything. Try injecting some logs in `autoload/executive/coc.vim` if you want to debug it.

**Comment by smhc** [comment]
Why is Vista callling this on startup? Shouldn't it be deferred until the panel is opened?
It seems to be a race condition where Vista is calling the coc command before the service is initialised, which will always take time.

**Comment by liuchengxu** [comment]
>It seems to be a race condition where Vista is calling the coc command before the service is initialised, which will always take time. IMHO it shouldn't be calling anything at all at startup.

No. That API merely returns nothing at that time. The main purpose of `autocmd VimEnter * call vista#RunForNearestMethodOrFunction()` is to invoke the vista hooks so that the tags can be updated automatically later even you don't open the vista panel, see https://github.com/liuchengxu/vista.vim/blob/master/autoload/vista.vim#L110-L118.

**Comment by smhc** [comment]
I receive :
```
[vista.vim] Error when calling CocActionAsync('documentSymbols'): 'Cannot read property ''getDocumentSymbols'' of undefined'
```
even when starting vim on a non-supported filetype. It occurs at startup, without any autocmds to invoke vista. I was referring to the fact the documentation states 'vista.vim never run if you don't call it explicitly.', but it clearly is running, the error is coming from https://github.com/liuchengxu/vista.vim/blob/fe30ae1b48187c3916f8fa8e9b6c57afe21ea3e1/autoload/vista/executive/coc.vim#L43

**Comment by liuchengxu** [comment]
That's not possible. See https://github.com/liuchengxu/vista.vim/blob/master/plugin/vista.vim, you must have some vista related autocmd hook enabled or invoke `:Vista` explicitly.

**Comment by smhc** [comment]
You're right - it is an airline issue. Setting:
```
let g:airline#extensions#vista#enabled = 0
```
fixes the startup error.

**Comment by hballard** [comment]
I receive the exact same error at @smhc ...as soon as I open my editor (Neovim).  I do not have any VIsta related autocmd hooks nor do I invoke it explicitly.  But, it seems to be be running when I have this setting enabled:

`let g:vista_default_executive = 'coc'
`

I guess I could just use `let g:vista_executive_for` for specific file types, but I was trying to have "coc" be my default and then using `g:vista_finder_alternative_executives` to fall back to "ctags" if "coc" was not available.  

The setting `let g: vista_default_executive = 'coc'` was working with COC until a few weeks ago, but then this error started showing up when I initially opened my editor, I assume after an update.

**Comment by hballard** [comment]
That was the change in behavior I describe above...but I fixed my error by changing a couple other settings.  So, you can disregard my previous comment.

**Comment by Lexx666** [comment]
> You're right - it is an airline issue. Setting:
> 
> ```
> let g:airline#extensions#vista#enabled = 0
> ```
> 
> fixes the startup error.

This fixes it for me too.
Airline tests on `if get(g:, 'airline#extensions#vista#enabled', 1) && exists(':Vista')` and it wants to call `vista#RunForNearestMethodOrFunction()` on `VimEnter`
