### ISSUE TITLE
how to set visita symbol then like your readme pic

### ISSUE THREAD

**Issue by taigacute** [liuchengxu/vista.vim#88]
**Describe the bug**
hi  first of all  ,a great plugin, but i got this ,not look like your pic
![1](https://user-images.githubusercontent.com/41671631/58404691-4440ea00-8098-11e9-8d39-1136aed58fcd.png)
![2](https://user-images.githubusercontent.com/41671631/58404702-4a36cb00-8098-11e9-9b3d-e7730609ee79.png)
how to set?

**Environment:**
- OS: macos 10. 13.6
- Vim/Neovim version: nvim 0.4.0-dev
- This plugin version: the latest

**Vista info**

```
```

**Steps to reproduce given the above info**

N/A

**Expected behavior**
look like your readme pic

**Actual behavior**
N/A

**Screenshot or gif** (if possible)
N/A

**Comment by liuchengxu** [comment]
LSP renderers don't support tree view at the moment as many language servers don't have the hierarchy support, the screenshot in README is `:Vista ctags`.

**Comment by taigacute** [comment]
@liuchengxu  thanks
