### ISSUE TITLE
Incorrect selection over current symbol in Vista

### ISSUE THREAD

**Issue by oblitum** [liuchengxu/vista.vim#89]
**Describe the bug**

When moving the cursor over the symbols in Vista window, it automatically highlights the current one, but the selection is often broken.

**Environment:**
- OS: ArchLinux
- Vim/Neovim version: NVIM v0.4.0-808-g62d5137c8
- This plugin version: cd60644
- Source used:
  ```cpp
  namespace {
  void foo(int a, int b);
  void bar(int a, int b);
  }
  
  int main() {
  }
  ```
- Using coc.nvim + ccls.

**Vista info**

```
    Current FileType: cpp
Avaliable Executives: ['coc', 'ctags']
    Global Variables:
    let g:vista#executives = ['coc', 'ctags', 'lcn', 'vim_lsp']
    let g:vista_executive_for = {'typescript': 'coc', 'go': 'coc', 'c': 'coc', 'javascript': 'coc', 'html': 'coc', 'rust': 'coc', 'cpp': 'coc', 'css': 'coc', 'python': 'coc'}
    let g:vista_icon_indent = ['╰─🞂 ', '├─🞂 ']
    let g:vista_sidebar_width = 60
```

**Steps to reproduce given the above info**

1. `:Vista coc`
2. Move cursor vertically

**Expected behavior**
Some better selection/indication behavior.

**Actual behavior**
Bad symbol selection.

**Screenshot or gif** (if possible)

![00:43:52_28-05-2019](https://user-images.githubusercontent.com/1269815/58449916-03ba8e00-80e3-11e9-86f2-0cdb369036bb.png)

**Comment by liuchengxu** [comment]
Could you also provide the ccls config in coc? I can't see the anonymous namespace given your sample code.

```vim
call plug#begin('~/.vim/plugged')
Plug 'liuchengxu/vista.vim'
Plug 'neoclide/coc.nvim'
call plug#end()

let g:vista#executives = ['coc', 'ctags', 'lcn', 'vim_lsp']
let g:vista_executive_for = {'typescript': 'coc', 'go': 'coc', 'c': 'coc', 'javascript': 'coc', 'html': 'coc', 'rust': 'coc', 'cpp': 'coc', 'css': 'coc', 'python': 'coc'}
let g:vista_icon_indent = ['╰─🞂 ', '├─🞂 ']
let g:vista_sidebar_width = 60
```

```
      "ccls":{
         "command":"ccls",
         "filetypes":["c", "cpp", "objc", "objcpp" ],
         "rootPatterns":[ ".ccls", "compile_commands.json", ".vim/", ".git/", ".hg/" ],
         "initializationOptions":{
            "cacheDirectory":"/tmp/ccls"
         }
      },
```

**Comment by oblitum** [comment]
My coc cls configuration is the same, but this is my `.ccls` file for the sample code, I'm using libc++:

```
%clang
-Wall
-Wextra
%c -std=gnu11
%c -Wno-unused-parameter
%cpp -pedantic
%cpp -std=c++17
%cpp -stdlib=libc++
```

**Comment by oblitum** [comment]
I'm using ccls from AUR (ccls 0.20190314-2): https://aur.archlinux.org/packages/ccls

**Comment by liuchengxu** [comment]
Still can't see the namespaces in my machine. You could try what is wrong with this function `s:GetInfoUnderCursor` which is expected to return the right tag.

https://github.com/liuchengxu/vista.vim/blob/4b96ca52986e12f03e5dd54528ce0145156e165a/autoload/vista/cursor.vim#L35

**Comment by oblitum** [comment]
hi @liuchengxu, I get this out of that function when hovering `foo`: `['├─🞂 ', 'void foo(int a, int b);']`.

**Comment by oblitum** [comment]
There's no `(anonymous namespace)::` in the result. I guess this gets difficult to solve if you can't reproduce. No idea how this ends up diverging.
