### ISSUE TITLE
Add a way to jump to next tag

### ISSUE THREAD

**Issue by blayz3r** [liuchengxu/vista.vim#94]
**Is your feature request related to a problem? Please describe.**

**Add a way to jump to next tag**

**Additional context**
https://github.com/majutsushi/tagbar/blob/387bbadda98e1376ff3871aa461b1f0abd4ece70/doc/tagbar.txt#L327

**Comment by liuchengxu** [comment]
Try #95.

**Comment by blayz3r** [comment]
Excellent thanks for the quick turnaround. Works as expected.
