### ISSUE TITLE
Make Popup non-intrusive

### ISSUE THREAD

**Issue by blayz3r** [liuchengxu/vista.vim#96]
**Describe the bug**
**Vim Popups are too big and in the way. Background color could also be darker than** **colorscheme.**

**Environment:**
- OS: 
- Vim/Neovim version: 
- This plugin version: 

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.
![2019-06-07_0-00-08](https://user-images.githubusercontent.com/12205650/59080666-eaba9580-88b7-11e9-8f22-a267c8d759e6.png)
![2019-06-07_0-06-35](https://user-images.githubusercontent.com/12205650/59080712-32412180-88b8-11e9-94d8-2fbaed6cf5df.png)

**Screenshot or gif** (if possible)

**Comment by liuchengxu** [comment]
You use open the vista sidebar on the right until I push a fix.

**Comment by blayz3r** [comment]
Sounds good. Thanks for the great work and early adoption.

**Comment by liuchengxu** [comment]
See if #97 works.

**Comment by blayz3r** [comment]
Yes, that is a lot better.
