### ISSUE TITLE
Add an option for the cursor to stay in the Vista window after jumping to definition

### ISSUE THREAD

**Issue by daveyarwood** [liuchengxu/vista.vim#98]
**Is your feature request related to a problem? Please describe.**
As an alternative to preview, I like to jump to the definition and see if it's the one that I wanted to jump to. Once I've found the one I want, I close the Vista window via a keybinding.

This mostly works well, but when the definition I jumped to is not the one I wanted, I have to move back into the Vista window manually to choose another one.

**Describe the solution you'd like**
An option like `g:vista_stay_on_jump` to allow me to configure Vista to keep my cursor in the Vista window after jumping to a definition.

**Describe alternatives you've considered**
I can't think of any alternatives at the moment.

**Comment by liuchengxu** [comment]
Try  adding `let g:vista_echo_cursor_strategy = 'scroll'` to your vimrc.

**Comment by daveyarwood** [comment]
Nice -- I like that! That solves my problem, thanks :)
