### ISSUE TITLE
Support ALE

### ISSUE THREAD

**Issue by gbrlsnchs** [liuchengxu/vista.vim#99]
**Is your feature request related to a problem? Please describe.**
You can now make LSP requests via ALE using the API requested [here](https://github.com/w0rp/ale/issues/2474).

**Describe the solution you'd like**
Vista.vim to use the new ALE API to show symbols.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by liuchengxu** [comment]
Try #105 and let me know if there are any problems.

**Comment by gbrlsnchs** [comment]
Thanks @liuchengxu! Great work!
